// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class AttachmentsClient {
public:
    explicit AttachmentsClient(TofuPilot& client) noexcept : client_(client) {}

    class InitializeBuilder;
    InitializeBuilder initialize();
    class FinalizeBuilder;
    FinalizeBuilder finalize();

private:
    TofuPilot& client_;
};

class AttachmentsClient::InitializeBuilder {
public:
    explicit InitializeBuilder(TofuPilot& client) noexcept : client_(client) {}

    InitializeBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }
    InitializeBuilder& body(AttachmentInitializeRequest b) {
        name_ = std::move(b.name);
        return *this;
    }

    InitializeBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    InitializeBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    AttachmentInitializeResponse send() {

        std::string path = "/v2/attachments";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            AttachmentInitializeRequest req_body;
            if (!name_.has_value()) throw ValidationError("missing required field: name");
            req_body.name = name_.value();
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("POST", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return AttachmentInitializeResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<AttachmentInitializeResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> name_;
    RequestConfig request_config_;
};

class AttachmentsClient::FinalizeBuilder {
public:
    explicit FinalizeBuilder(TofuPilot& client) noexcept : client_(client) {}

    FinalizeBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    FinalizeBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    FinalizeBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    AttachmentFinalizeResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/attachments/" + detail::url_encode(id_.value()) + "/finalize";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("POST", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return AttachmentFinalizeResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<AttachmentFinalizeResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

inline AttachmentsClient::InitializeBuilder AttachmentsClient::initialize() {
    return InitializeBuilder(client_);
}
inline AttachmentsClient::FinalizeBuilder AttachmentsClient::finalize() {
    return FinalizeBuilder(client_);
}

} // namespace tofupilot
