// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class DeploymentsClient {
public:
    explicit DeploymentsClient(TofuPilot& client) noexcept : client_(client) {}

    class ListBuilder;
    ListBuilder list();
    class GetBuilder;
    GetBuilder get();

private:
    TofuPilot& client_;
};

class DeploymentsClient::ListBuilder {
public:
    explicit ListBuilder(TofuPilot& client) noexcept : client_(client) {}

    ListBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& environments(std::vector<Environment> value) {
        environments_ = std::move(value);
        return *this;
    }
    ListBuilder& build_statuses(std::vector<DeploymentGetStatus> value) {
        build_statuses_ = std::move(value);
        return *this;
    }
    ListBuilder& pushed(bool value) {
        pushed_ = std::move(value);
        return *this;
    }
    ListBuilder& branch_names(std::vector<std::string> value) {
        branch_names_ = std::move(value);
        return *this;
    }
    ListBuilder& author_usernames(std::vector<std::string> value) {
        author_usernames_ = std::move(value);
        return *this;
    }
    ListBuilder& deployed_after(std::string value) {
        deployed_after_ = std::move(value);
        return *this;
    }
    ListBuilder& deployed_before(std::string value) {
        deployed_before_ = std::move(value);
        return *this;
    }
    ListBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }
    ListBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }
    ListBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    ListBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    ListBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    DeploymentListResponse send() {

        std::string path = "/v2/deployments";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (procedure_ids_.has_value()) {
                for (const auto& item : procedure_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (environments_.has_value()) {
                for (const auto& item : environments_.value()) {
                    if (!first) qs << "&";
                    qs << "environments=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (build_statuses_.has_value()) {
                for (const auto& item : build_statuses_.value()) {
                    if (!first) qs << "&";
                    qs << "build_statuses=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (pushed_.has_value()) {
                if (!first) qs << "&";
                qs << "pushed=" << detail::url_encode(detail::to_query_string(pushed_.value()));
                first = false;
            }
            if (branch_names_.has_value()) {
                for (const auto& item : branch_names_.value()) {
                    if (!first) qs << "&";
                    qs << "branch_names=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (author_usernames_.has_value()) {
                for (const auto& item : author_usernames_.value()) {
                    if (!first) qs << "&";
                    qs << "author_usernames=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (deployed_after_.has_value()) {
                if (!first) qs << "&";
                qs << "deployed_after=" << detail::url_encode(detail::to_query_string(deployed_after_.value()));
                first = false;
            }
            if (deployed_before_.has_value()) {
                if (!first) qs << "&";
                qs << "deployed_before=" << detail::url_encode(detail::to_query_string(deployed_before_.value()));
                first = false;
            }
            if (search_query_.has_value()) {
                if (!first) qs << "&";
                qs << "search_query=" << detail::url_encode(detail::to_query_string(search_query_.value()));
                first = false;
            }
            if (limit_.has_value()) {
                if (!first) qs << "&";
                qs << "limit=" << detail::url_encode(detail::to_query_string(limit_.value()));
                first = false;
            }
            if (cursor_.has_value()) {
                if (!first) qs << "&";
                qs << "cursor=" << detail::url_encode(detail::to_query_string(cursor_.value()));
                first = false;
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return DeploymentListResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<DeploymentListResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<std::vector<Environment>> environments_;
    std::optional<std::vector<DeploymentGetStatus>> build_statuses_;
    std::optional<bool> pushed_;
    std::optional<std::vector<std::string>> branch_names_;
    std::optional<std::vector<std::string>> author_usernames_;
    std::optional<std::string> deployed_after_;
    std::optional<std::string> deployed_before_;
    std::optional<std::string> search_query_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    RequestConfig request_config_;
};

class DeploymentsClient::GetBuilder {
public:
    explicit GetBuilder(TofuPilot& client) noexcept : client_(client) {}

    GetBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    GetBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    DeploymentGetResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/deployments/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return DeploymentGetResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<DeploymentGetResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

inline DeploymentsClient::ListBuilder DeploymentsClient::list() {
    return ListBuilder(client_);
}
inline DeploymentsClient::GetBuilder DeploymentsClient::get() {
    return GetBuilder(client_);
}

} // namespace tofupilot
