// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <cstdio>
#include <string>
#include <type_traits>

#include <nlohmann/json.hpp>

namespace tofupilot {
namespace detail {

inline std::string url_encode(const std::string& value) {
    std::string encoded;
    encoded.reserve(value.size() * 2);
    for (unsigned char c : value) {
        if (std::isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
            encoded += static_cast<char>(c);
        } else {
            char buf[4];
            std::snprintf(buf, sizeof(buf), "%%%02X", c);
            encoded += buf;
        }
    }
    return encoded;
}

inline std::string to_query_string(const std::string& v) { return v; }
inline std::string to_query_string(bool v) { return v ? "true" : "false"; }

template<typename T, std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool>, int> = 0>
std::string to_query_string(T v) { return std::to_string(v); }

inline std::string to_query_string(double v) {
    char buf[64];
    std::snprintf(buf, sizeof(buf), "%.17g", v);
    return buf;
}

template<typename T, std::enable_if_t<!std::is_integral_v<T> && !std::is_floating_point_v<T> && !std::is_same_v<T, std::string>, int> = 0>
std::string to_query_string(const T& v) {
    nlohmann::json j = v;
    if (j.is_string()) return j.get<std::string>();
    return j.dump();
}

} // namespace detail
} // namespace tofupilot
