// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

namespace tofupilot {

struct ApiErrorIssue {
    std::string message;
};

inline void from_json(const nlohmann::json& j, ApiErrorIssue& v) {
    if (j.contains("message")) v.message = j["message"].get<std::string>();
}

struct ApiError {
    std::string message;
    std::string code;
    std::vector<ApiErrorIssue> issues;

    std::string to_string() const {
        std::string result = message;
        if (!issues.empty()) {
            result += " (";
            for (size_t i = 0; i < issues.size(); ++i) {
                if (i > 0) result += ", ";
                result += issues[i].message;
            }
            result += ")";
        }
        return result;
    }
};

inline void from_json(const nlohmann::json& j, ApiError& v) {
    if (j.contains("message") && j["message"].is_string()) v.message = j["message"].get<std::string>();
    if (j.contains("code") && j["code"].is_string()) v.code = j["code"].get<std::string>();
    if (j.contains("issues") && j["issues"].is_array()) v.issues = j["issues"].get<std::vector<ApiErrorIssue>>();
}

class ApiException : public std::runtime_error {
public:
    ApiException(int status_code, const std::string& body)
        : std::runtime_error("HTTP " + std::to_string(status_code) + ": " + body)
        , status_code_(status_code)
        , body_(body) {
        try {
            error_ = nlohmann::json::parse(body).get<ApiError>();
        } catch (const nlohmann::json::exception&) {
            error_.message = body;
            error_.code = std::to_string(status_code);
        }
    }

    ApiException(int status_code, ApiError error)
        : std::runtime_error(error.to_string())
        , status_code_(status_code)
        , error_(std::move(error))      // init before body_ (declaration order)
        , body_(error_.to_string()) {}

    int status_code() const noexcept { return status_code_; }
    const ApiError& error() const noexcept { return error_; }
    const std::string& body() const noexcept { return body_; }

private:
    int status_code_;
    ApiError error_;
    std::string body_;
};

class BadRequestError : public ApiException { public: using ApiException::ApiException; };
class UnauthorizedError : public ApiException { public: using ApiException::ApiException; };
class ForbiddenError : public ApiException { public: using ApiException::ApiException; };
class NotFoundError : public ApiException { public: using ApiException::ApiException; };
class ConflictError : public ApiException { public: using ApiException::ApiException; };
class UnprocessableContentError : public ApiException { public: using ApiException::ApiException; };
class RateLimitedError : public ApiException { public: using ApiException::ApiException; };
class InternalServerError : public ApiException { public: using ApiException::ApiException; };
class BadGatewayError : public ApiException { public: using ApiException::ApiException; };

class ValidationError : public std::runtime_error {
public:
    explicit ValidationError(const std::string& message) : std::runtime_error(message) {}
};

class HttpError : public std::runtime_error {
public:
    explicit HttpError(const std::string& message) : std::runtime_error(message) {}
};

[[noreturn]] inline void throw_for_status(int status_code, const std::string& body) {
    switch (status_code) {
        case 400: throw BadRequestError(status_code, body);
        case 401: throw UnauthorizedError(status_code, body);
        case 403: throw ForbiddenError(status_code, body);
        case 404: throw NotFoundError(status_code, body);
        case 409: throw ConflictError(status_code, body);
        case 422: throw UnprocessableContentError(status_code, body);
        case 429: throw RateLimitedError(status_code, body);
        case 500: throw InternalServerError(status_code, body);
        case 502: throw BadGatewayError(status_code, body);
        default:  throw ApiException(status_code, body);
    }
}

/// Only transient errors: 429, 502, 503, 504. NOT 500/501/505.
inline bool is_retryable_status(int status_code) noexcept {
    return status_code == 429 || status_code == 502
        || status_code == 503 || status_code == 504;
}

} // namespace tofupilot
