// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class MeasurementsClient {
public:
    explicit MeasurementsClient(TofuPilot& client) noexcept : client_(client) {}

    class ListBuilder;
    ListBuilder list();
    class GetBuilder;
    GetBuilder get();

private:
    TofuPilot& client_;
};

class MeasurementsClient::ListBuilder {
public:
    explicit ListBuilder(TofuPilot& client) noexcept : client_(client) {}

    ListBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }
    ListBuilder& phase_name(std::string value) {
        phase_name_ = std::move(value);
        return *this;
    }
    ListBuilder& measurement_name(std::string value) {
        measurement_name_ = std::move(value);
        return *this;
    }
    ListBuilder& phase_names(std::vector<std::string> value) {
        phase_names_ = std::move(value);
        return *this;
    }
    ListBuilder& outcomes(std::vector<LogGetOutcome> value) {
        outcomes_ = std::move(value);
        return *this;
    }
    ListBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }
    ListBuilder& duration_min(std::string value) {
        duration_min_ = std::move(value);
        return *this;
    }
    ListBuilder& duration_max(std::string value) {
        duration_max_ = std::move(value);
        return *this;
    }
    ListBuilder& deployment_ids(std::vector<std::string> value) {
        deployment_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& procedure_versions(std::vector<std::string> value) {
        procedure_versions_ = std::move(value);
        return *this;
    }
    ListBuilder& environments(std::vector<Environment> value) {
        environments_ = std::move(value);
        return *this;
    }
    ListBuilder& serial_numbers(std::vector<std::string> value) {
        serial_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& part_numbers(std::vector<std::string> value) {
        part_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& revision_numbers(std::vector<std::string> value) {
        revision_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& batch_numbers(std::vector<std::string> value) {
        batch_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& operated_by_ids(std::vector<std::string> value) {
        operated_by_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& created_by_station_ids(std::vector<std::string> value) {
        created_by_station_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& created_by_user_ids(std::vector<std::string> value) {
        created_by_user_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& started_after(std::string value) {
        started_after_ = std::move(value);
        return *this;
    }
    ListBuilder& started_before(std::string value) {
        started_before_ = std::move(value);
        return *this;
    }
    ListBuilder& exclude_retries(bool value) {
        exclude_retries_ = std::move(value);
        return *this;
    }
    ListBuilder& value_min(double value) {
        value_min_ = std::move(value);
        return *this;
    }
    ListBuilder& value_max(double value) {
        value_max_ = std::move(value);
        return *this;
    }
    ListBuilder& value_bool(bool value) {
        value_bool_ = std::move(value);
        return *this;
    }
    ListBuilder& value_strings(std::vector<std::string> value) {
        value_strings_ = std::move(value);
        return *this;
    }
    ListBuilder& measurement_outcomes(std::vector<Outcome> value) {
        measurement_outcomes_ = std::move(value);
        return *this;
    }
    ListBuilder& measurement_types(std::vector<MeasurementType> value) {
        measurement_types_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_by(MeasurementListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }
    ListBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }
    ListBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    ListBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    ListBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    MeasurementListResponse send() {

        std::string path = "/v2/measurements";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (procedure_id_.has_value()) {
                if (!first) qs << "&";
                qs << "procedure_id=" << detail::url_encode(detail::to_query_string(procedure_id_.value()));
                first = false;
            }
            if (phase_name_.has_value()) {
                if (!first) qs << "&";
                qs << "phase_name=" << detail::url_encode(detail::to_query_string(phase_name_.value()));
                first = false;
            }
            if (measurement_name_.has_value()) {
                if (!first) qs << "&";
                qs << "measurement_name=" << detail::url_encode(detail::to_query_string(measurement_name_.value()));
                first = false;
            }
            if (phase_names_.has_value()) {
                for (const auto& item : phase_names_.value()) {
                    if (!first) qs << "&";
                    qs << "phase_names=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (outcomes_.has_value()) {
                for (const auto& item : outcomes_.value()) {
                    if (!first) qs << "&";
                    qs << "outcomes=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (ids_.has_value()) {
                for (const auto& item : ids_.value()) {
                    if (!first) qs << "&";
                    qs << "ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (duration_min_.has_value()) {
                if (!first) qs << "&";
                qs << "duration_min=" << detail::url_encode(detail::to_query_string(duration_min_.value()));
                first = false;
            }
            if (duration_max_.has_value()) {
                if (!first) qs << "&";
                qs << "duration_max=" << detail::url_encode(detail::to_query_string(duration_max_.value()));
                first = false;
            }
            if (deployment_ids_.has_value()) {
                for (const auto& item : deployment_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "deployment_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (procedure_versions_.has_value()) {
                for (const auto& item : procedure_versions_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_versions=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (environments_.has_value()) {
                for (const auto& item : environments_.value()) {
                    if (!first) qs << "&";
                    qs << "environments=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (serial_numbers_.has_value()) {
                for (const auto& item : serial_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "serial_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (part_numbers_.has_value()) {
                for (const auto& item : part_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "part_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (revision_numbers_.has_value()) {
                for (const auto& item : revision_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "revision_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (batch_numbers_.has_value()) {
                for (const auto& item : batch_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "batch_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (operated_by_ids_.has_value()) {
                for (const auto& item : operated_by_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "operated_by_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (created_by_station_ids_.has_value()) {
                for (const auto& item : created_by_station_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "created_by_station_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (created_by_user_ids_.has_value()) {
                for (const auto& item : created_by_user_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "created_by_user_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (started_after_.has_value()) {
                if (!first) qs << "&";
                qs << "started_after=" << detail::url_encode(detail::to_query_string(started_after_.value()));
                first = false;
            }
            if (started_before_.has_value()) {
                if (!first) qs << "&";
                qs << "started_before=" << detail::url_encode(detail::to_query_string(started_before_.value()));
                first = false;
            }
            if (exclude_retries_.has_value()) {
                if (!first) qs << "&";
                qs << "exclude_retries=" << detail::url_encode(detail::to_query_string(exclude_retries_.value()));
                first = false;
            }
            if (value_min_.has_value()) {
                if (!first) qs << "&";
                qs << "value_min=" << detail::url_encode(detail::to_query_string(value_min_.value()));
                first = false;
            }
            if (value_max_.has_value()) {
                if (!first) qs << "&";
                qs << "value_max=" << detail::url_encode(detail::to_query_string(value_max_.value()));
                first = false;
            }
            if (value_bool_.has_value()) {
                if (!first) qs << "&";
                qs << "value_bool=" << detail::url_encode(detail::to_query_string(value_bool_.value()));
                first = false;
            }
            if (value_strings_.has_value()) {
                for (const auto& item : value_strings_.value()) {
                    if (!first) qs << "&";
                    qs << "value_strings=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (measurement_outcomes_.has_value()) {
                for (const auto& item : measurement_outcomes_.value()) {
                    if (!first) qs << "&";
                    qs << "measurement_outcomes=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (measurement_types_.has_value()) {
                for (const auto& item : measurement_types_.value()) {
                    if (!first) qs << "&";
                    qs << "measurement_types=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (sort_by_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_by=" << detail::url_encode(detail::to_query_string(sort_by_.value()));
                first = false;
            }
            if (sort_order_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_order=" << detail::url_encode(detail::to_query_string(sort_order_.value()));
                first = false;
            }
            if (limit_.has_value()) {
                if (!first) qs << "&";
                qs << "limit=" << detail::url_encode(detail::to_query_string(limit_.value()));
                first = false;
            }
            if (cursor_.has_value()) {
                if (!first) qs << "&";
                qs << "cursor=" << detail::url_encode(detail::to_query_string(cursor_.value()));
                first = false;
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return MeasurementListResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<MeasurementListResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> procedure_id_;
    std::optional<std::string> phase_name_;
    std::optional<std::string> measurement_name_;
    std::optional<std::vector<std::string>> phase_names_;
    std::optional<std::vector<LogGetOutcome>> outcomes_;
    std::optional<std::vector<std::string>> ids_;
    std::optional<std::string> duration_min_;
    std::optional<std::string> duration_max_;
    std::optional<std::vector<std::string>> deployment_ids_;
    std::optional<std::vector<std::string>> procedure_versions_;
    std::optional<std::vector<Environment>> environments_;
    std::optional<std::vector<std::string>> serial_numbers_;
    std::optional<std::vector<std::string>> part_numbers_;
    std::optional<std::vector<std::string>> revision_numbers_;
    std::optional<std::vector<std::string>> batch_numbers_;
    std::optional<std::vector<std::string>> operated_by_ids_;
    std::optional<std::vector<std::string>> created_by_station_ids_;
    std::optional<std::vector<std::string>> created_by_user_ids_;
    std::optional<std::string> started_after_;
    std::optional<std::string> started_before_;
    std::optional<bool> exclude_retries_;
    std::optional<double> value_min_;
    std::optional<double> value_max_;
    std::optional<bool> value_bool_;
    std::optional<std::vector<std::string>> value_strings_;
    std::optional<std::vector<Outcome>> measurement_outcomes_;
    std::optional<std::vector<MeasurementType>> measurement_types_;
    std::optional<MeasurementListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    RequestConfig request_config_;
};

class MeasurementsClient::GetBuilder {
public:
    explicit GetBuilder(TofuPilot& client) noexcept : client_(client) {}

    GetBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    GetBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    MeasurementGetResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/measurements/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return MeasurementGetResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<MeasurementGetResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

inline MeasurementsClient::ListBuilder MeasurementsClient::list() {
    return ListBuilder(client_);
}
inline MeasurementsClient::GetBuilder MeasurementsClient::get() {
    return GetBuilder(client_);
}

} // namespace tofupilot
