// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class PartsClient {
public:
    explicit PartsClient(TofuPilot& client) noexcept : client_(client) {}

    class ListBuilder;
    ListBuilder list();
    class CreateBuilder;
    CreateBuilder create();
    class GetBuilder;
    GetBuilder get();
    class DeleteBuilder;
    DeleteBuilder delete_();
    class UpdateBuilder;
    UpdateBuilder update();

private:
    TofuPilot& client_;
};

class PartsClient::ListBuilder {
public:
    explicit ListBuilder(TofuPilot& client) noexcept : client_(client) {}

    ListBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }
    ListBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }
    ListBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }
    ListBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_by(PartListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }

    ListBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    ListBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    PartListResponse send() {

        std::string path = "/v2/parts";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (limit_.has_value()) {
                if (!first) qs << "&";
                qs << "limit=" << detail::url_encode(detail::to_query_string(limit_.value()));
                first = false;
            }
            if (cursor_.has_value()) {
                if (!first) qs << "&";
                qs << "cursor=" << detail::url_encode(detail::to_query_string(cursor_.value()));
                first = false;
            }
            if (search_query_.has_value()) {
                if (!first) qs << "&";
                qs << "search_query=" << detail::url_encode(detail::to_query_string(search_query_.value()));
                first = false;
            }
            if (procedure_ids_.has_value()) {
                for (const auto& item : procedure_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (sort_by_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_by=" << detail::url_encode(detail::to_query_string(sort_by_.value()));
                first = false;
            }
            if (sort_order_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_order=" << detail::url_encode(detail::to_query_string(sort_order_.value()));
                first = false;
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return PartListResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<PartListResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<PartListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
    RequestConfig request_config_;
};

class PartsClient::CreateBuilder {
public:
    explicit CreateBuilder(TofuPilot& client) noexcept : client_(client) {}

    CreateBuilder& number(std::string value) {
        number_ = std::move(value);
        return *this;
    }
    CreateBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }
    CreateBuilder& revision_number(std::string value) {
        revision_number_ = std::move(value);
        return *this;
    }
    CreateBuilder& body(PartCreateRequest b) {
        number_ = std::move(b.number);
        if (b.name.has_value()) name_ = std::move(b.name);
        if (b.revision_number.has_value()) revision_number_ = std::move(b.revision_number);
        return *this;
    }

    CreateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    CreateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    PartCreateResponse send() {

        std::string path = "/v2/parts";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            PartCreateRequest req_body;
            if (!number_.has_value()) throw ValidationError("missing required field: number");
            req_body.number = number_.value();
            req_body.name = name_;
            req_body.revision_number = revision_number_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("POST", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return PartCreateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<PartCreateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> number_;
    std::optional<std::string> name_;
    std::optional<std::string> revision_number_;
    RequestConfig request_config_;
};

class PartsClient::GetBuilder {
public:
    explicit GetBuilder(TofuPilot& client) noexcept : client_(client) {}

    GetBuilder& number(std::string value) {
        number_ = std::move(value);
        return *this;
    }

    GetBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    PartGetResponse send() {
        if (!number_.has_value()) throw ValidationError("missing required path parameter: number");

        std::string path = "/v2/parts/" + detail::url_encode(number_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return PartGetResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<PartGetResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> number_;
    RequestConfig request_config_;
};

class PartsClient::DeleteBuilder {
public:
    explicit DeleteBuilder(TofuPilot& client) noexcept : client_(client) {}

    DeleteBuilder& number(std::string value) {
        number_ = std::move(value);
        return *this;
    }

    DeleteBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    DeleteBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    PartDeleteResponse send() {
        if (!number_.has_value()) throw ValidationError("missing required path parameter: number");

        std::string path = "/v2/parts/" + detail::url_encode(number_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("DELETE", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return PartDeleteResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<PartDeleteResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> number_;
    RequestConfig request_config_;
};

class PartsClient::UpdateBuilder {
public:
    explicit UpdateBuilder(TofuPilot& client) noexcept : client_(client) {}

    UpdateBuilder& number(std::string value) {
        number_ = std::move(value);
        return *this;
    }
    UpdateBuilder& new_number(std::string value) {
        new_number_ = std::move(value);
        return *this;
    }
    UpdateBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }
    UpdateBuilder& body(PartUpdateRequestBody b) {
        if (b.new_number.has_value()) new_number_ = std::move(b.new_number);
        if (b.name.has_value()) name_ = std::move(b.name);
        return *this;
    }

    UpdateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    UpdateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    PartUpdateResponse send() {
        if (!number_.has_value()) throw ValidationError("missing required path parameter: number");

        std::string path = "/v2/parts/" + detail::url_encode(number_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            PartUpdateRequestBody req_body;
            req_body.new_number = new_number_;
            req_body.name = name_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("PATCH", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return PartUpdateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<PartUpdateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> number_;
    std::optional<std::string> new_number_;
    std::optional<std::string> name_;
    RequestConfig request_config_;
};

inline PartsClient::ListBuilder PartsClient::list() {
    return ListBuilder(client_);
}
inline PartsClient::CreateBuilder PartsClient::create() {
    return CreateBuilder(client_);
}
inline PartsClient::GetBuilder PartsClient::get() {
    return GetBuilder(client_);
}
inline PartsClient::DeleteBuilder PartsClient::delete_() {
    return DeleteBuilder(client_);
}
inline PartsClient::UpdateBuilder PartsClient::update() {
    return UpdateBuilder(client_);
}

} // namespace tofupilot
