// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class RunsClient {
public:
    explicit RunsClient(TofuPilot& client) noexcept : client_(client) {}

    class ListBuilder;
    ListBuilder list();
    class CreateBuilder;
    CreateBuilder create();
    class DeleteBuilder;
    DeleteBuilder delete_();
    class GetBuilder;
    GetBuilder get();
    class UpdateBuilder;
    UpdateBuilder update();

private:
    TofuPilot& client_;
};

class RunsClient::ListBuilder {
public:
    explicit ListBuilder(TofuPilot& client) noexcept : client_(client) {}

    ListBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }
    ListBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }
    ListBuilder& outcomes(std::vector<Outcome> value) {
        outcomes_ = std::move(value);
        return *this;
    }
    ListBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& procedure_versions(std::vector<std::string> value) {
        procedure_versions_ = std::move(value);
        return *this;
    }
    ListBuilder& serial_numbers(std::vector<std::string> value) {
        serial_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& part_numbers(std::vector<std::string> value) {
        part_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& revision_numbers(std::vector<std::string> value) {
        revision_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& batch_numbers(std::vector<std::string> value) {
        batch_numbers_ = std::move(value);
        return *this;
    }
    ListBuilder& duration_min(std::string value) {
        duration_min_ = std::move(value);
        return *this;
    }
    ListBuilder& duration_max(std::string value) {
        duration_max_ = std::move(value);
        return *this;
    }
    ListBuilder& started_after(std::string value) {
        started_after_ = std::move(value);
        return *this;
    }
    ListBuilder& started_before(std::string value) {
        started_before_ = std::move(value);
        return *this;
    }
    ListBuilder& ended_after(std::string value) {
        ended_after_ = std::move(value);
        return *this;
    }
    ListBuilder& ended_before(std::string value) {
        ended_before_ = std::move(value);
        return *this;
    }
    ListBuilder& created_after(std::string value) {
        created_after_ = std::move(value);
        return *this;
    }
    ListBuilder& created_before(std::string value) {
        created_before_ = std::move(value);
        return *this;
    }
    ListBuilder& created_by_user_ids(std::vector<std::string> value) {
        created_by_user_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& created_by_station_ids(std::vector<std::string> value) {
        created_by_station_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& operated_by_ids(std::vector<std::string> value) {
        operated_by_ids_ = std::move(value);
        return *this;
    }
    ListBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }
    ListBuilder& cursor(double value) {
        cursor_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_by(RunListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }
    ListBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }

    ListBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    ListBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    RunListResponse send() {

        std::string path = "/v2/runs";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (search_query_.has_value()) {
                if (!first) qs << "&";
                qs << "search_query=" << detail::url_encode(detail::to_query_string(search_query_.value()));
                first = false;
            }
            if (ids_.has_value()) {
                for (const auto& item : ids_.value()) {
                    if (!first) qs << "&";
                    qs << "ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (outcomes_.has_value()) {
                for (const auto& item : outcomes_.value()) {
                    if (!first) qs << "&";
                    qs << "outcomes=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (procedure_ids_.has_value()) {
                for (const auto& item : procedure_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (procedure_versions_.has_value()) {
                for (const auto& item : procedure_versions_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_versions=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (serial_numbers_.has_value()) {
                for (const auto& item : serial_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "serial_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (part_numbers_.has_value()) {
                for (const auto& item : part_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "part_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (revision_numbers_.has_value()) {
                for (const auto& item : revision_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "revision_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (batch_numbers_.has_value()) {
                for (const auto& item : batch_numbers_.value()) {
                    if (!first) qs << "&";
                    qs << "batch_numbers=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (duration_min_.has_value()) {
                if (!first) qs << "&";
                qs << "duration_min=" << detail::url_encode(detail::to_query_string(duration_min_.value()));
                first = false;
            }
            if (duration_max_.has_value()) {
                if (!first) qs << "&";
                qs << "duration_max=" << detail::url_encode(detail::to_query_string(duration_max_.value()));
                first = false;
            }
            if (started_after_.has_value()) {
                if (!first) qs << "&";
                qs << "started_after=" << detail::url_encode(detail::to_query_string(started_after_.value()));
                first = false;
            }
            if (started_before_.has_value()) {
                if (!first) qs << "&";
                qs << "started_before=" << detail::url_encode(detail::to_query_string(started_before_.value()));
                first = false;
            }
            if (ended_after_.has_value()) {
                if (!first) qs << "&";
                qs << "ended_after=" << detail::url_encode(detail::to_query_string(ended_after_.value()));
                first = false;
            }
            if (ended_before_.has_value()) {
                if (!first) qs << "&";
                qs << "ended_before=" << detail::url_encode(detail::to_query_string(ended_before_.value()));
                first = false;
            }
            if (created_after_.has_value()) {
                if (!first) qs << "&";
                qs << "created_after=" << detail::url_encode(detail::to_query_string(created_after_.value()));
                first = false;
            }
            if (created_before_.has_value()) {
                if (!first) qs << "&";
                qs << "created_before=" << detail::url_encode(detail::to_query_string(created_before_.value()));
                first = false;
            }
            if (created_by_user_ids_.has_value()) {
                for (const auto& item : created_by_user_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "created_by_user_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (created_by_station_ids_.has_value()) {
                for (const auto& item : created_by_station_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "created_by_station_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (operated_by_ids_.has_value()) {
                for (const auto& item : operated_by_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "operated_by_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            if (limit_.has_value()) {
                if (!first) qs << "&";
                qs << "limit=" << detail::url_encode(detail::to_query_string(limit_.value()));
                first = false;
            }
            if (cursor_.has_value()) {
                if (!first) qs << "&";
                qs << "cursor=" << detail::url_encode(detail::to_query_string(cursor_.value()));
                first = false;
            }
            if (sort_by_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_by=" << detail::url_encode(detail::to_query_string(sort_by_.value()));
                first = false;
            }
            if (sort_order_.has_value()) {
                if (!first) qs << "&";
                qs << "sort_order=" << detail::url_encode(detail::to_query_string(sort_order_.value()));
                first = false;
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return RunListResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<RunListResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> ids_;
    std::optional<std::vector<Outcome>> outcomes_;
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<std::vector<std::string>> procedure_versions_;
    std::optional<std::vector<std::string>> serial_numbers_;
    std::optional<std::vector<std::string>> part_numbers_;
    std::optional<std::vector<std::string>> revision_numbers_;
    std::optional<std::vector<std::string>> batch_numbers_;
    std::optional<std::string> duration_min_;
    std::optional<std::string> duration_max_;
    std::optional<std::string> started_after_;
    std::optional<std::string> started_before_;
    std::optional<std::string> ended_after_;
    std::optional<std::string> ended_before_;
    std::optional<std::string> created_after_;
    std::optional<std::string> created_before_;
    std::optional<std::vector<std::string>> created_by_user_ids_;
    std::optional<std::vector<std::string>> created_by_station_ids_;
    std::optional<std::vector<std::string>> operated_by_ids_;
    std::optional<int64_t> limit_;
    std::optional<double> cursor_;
    std::optional<RunListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
    RequestConfig request_config_;
};

class RunsClient::CreateBuilder {
public:
    explicit CreateBuilder(TofuPilot& client) noexcept : client_(client) {}

    CreateBuilder& outcome(Outcome value) {
        outcome_ = std::move(value);
        return *this;
    }
    CreateBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }
    CreateBuilder& procedure_version(std::string value) {
        procedure_version_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }
    CreateBuilder& procedure_version_null() {
        procedure_version_ = NullableField<std::string>::make_null();
        return *this;
    }
    CreateBuilder& operated_by(std::string value) {
        operated_by_ = std::move(value);
        return *this;
    }
    CreateBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }
    CreateBuilder& ended_at(std::string value) {
        ended_at_ = std::move(value);
        return *this;
    }
    CreateBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }
    CreateBuilder& part_number(std::string value) {
        part_number_ = std::move(value);
        return *this;
    }
    CreateBuilder& revision_number(std::string value) {
        revision_number_ = std::move(value);
        return *this;
    }
    CreateBuilder& batch_number(std::string value) {
        batch_number_ = std::move(value);
        return *this;
    }
    CreateBuilder& sub_units(std::vector<std::string> value) {
        sub_units_ = std::move(value);
        return *this;
    }
    CreateBuilder& docstring(std::string value) {
        docstring_ = std::move(value);
        return *this;
    }
    CreateBuilder& phases(std::vector<RunCreatePhases> value) {
        phases_ = std::move(value);
        return *this;
    }
    CreateBuilder& logs(std::vector<RunCreateLogs> value) {
        logs_ = std::move(value);
        return *this;
    }
    CreateBuilder& body(RunCreateRequest b) {
        outcome_ = std::move(b.outcome);
        procedure_id_ = std::move(b.procedure_id);
        procedure_version_ = std::move(b.procedure_version);
        if (b.operated_by.has_value()) operated_by_ = std::move(b.operated_by);
        started_at_ = std::move(b.started_at);
        ended_at_ = std::move(b.ended_at);
        serial_number_ = std::move(b.serial_number);
        if (b.part_number.has_value()) part_number_ = std::move(b.part_number);
        if (b.revision_number.has_value()) revision_number_ = std::move(b.revision_number);
        if (b.batch_number.has_value()) batch_number_ = std::move(b.batch_number);
        if (b.sub_units.has_value()) sub_units_ = std::move(b.sub_units);
        if (b.docstring.has_value()) docstring_ = std::move(b.docstring);
        if (b.phases.has_value()) phases_ = std::move(b.phases);
        if (b.logs.has_value()) logs_ = std::move(b.logs);
        return *this;
    }

    CreateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    CreateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    RunCreateResponse send() {

        std::string path = "/v2/runs";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            RunCreateRequest req_body;
            if (!outcome_.has_value()) throw ValidationError("missing required field: outcome");
            req_body.outcome = outcome_.value();
            if (!procedure_id_.has_value()) throw ValidationError("missing required field: procedure_id");
            req_body.procedure_id = procedure_id_.value();
            if (!procedure_version_.is_absent()) req_body.procedure_version = procedure_version_;
            req_body.operated_by = operated_by_;
            if (!started_at_.has_value()) throw ValidationError("missing required field: started_at");
            req_body.started_at = started_at_.value();
            if (!ended_at_.has_value()) throw ValidationError("missing required field: ended_at");
            req_body.ended_at = ended_at_.value();
            if (!serial_number_.has_value()) throw ValidationError("missing required field: serial_number");
            req_body.serial_number = serial_number_.value();
            req_body.part_number = part_number_;
            req_body.revision_number = revision_number_;
            req_body.batch_number = batch_number_;
            req_body.sub_units = sub_units_;
            req_body.docstring = docstring_;
            req_body.phases = phases_;
            req_body.logs = logs_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("POST", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return RunCreateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<RunCreateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<Outcome> outcome_;
    std::optional<std::string> procedure_id_;
    NullableField<std::string> procedure_version_;
    std::optional<std::string> operated_by_;
    std::optional<std::string> started_at_;
    std::optional<std::string> ended_at_;
    std::optional<std::string> serial_number_;
    std::optional<std::string> part_number_;
    std::optional<std::string> revision_number_;
    std::optional<std::string> batch_number_;
    std::optional<std::vector<std::string>> sub_units_;
    std::optional<std::string> docstring_;
    std::optional<std::vector<RunCreatePhases>> phases_;
    std::optional<std::vector<RunCreateLogs>> logs_;
    RequestConfig request_config_;
};

class RunsClient::DeleteBuilder {
public:
    explicit DeleteBuilder(TofuPilot& client) noexcept : client_(client) {}

    DeleteBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    DeleteBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    DeleteBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    RunDeleteResponse send() {

        std::string path = "/v2/runs";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (ids_.has_value()) {
                for (const auto& item : ids_.value()) {
                    if (!first) qs << "&";
                    qs << "ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("DELETE", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return RunDeleteResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<RunDeleteResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::vector<std::string>> ids_;
    RequestConfig request_config_;
};

class RunsClient::GetBuilder {
public:
    explicit GetBuilder(TofuPilot& client) noexcept : client_(client) {}

    GetBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    GetBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    RunGetResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/runs/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return RunGetResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<RunGetResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

class RunsClient::UpdateBuilder {
public:
    explicit UpdateBuilder(TofuPilot& client) noexcept : client_(client) {}

    UpdateBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }
    UpdateBuilder& attachments(std::vector<std::string> value) {
        attachments_ = std::move(value);
        return *this;
    }
    UpdateBuilder& body(RunUpdateRequestBody b) {
        if (b.attachments.has_value()) attachments_ = std::move(b.attachments);
        return *this;
    }

    UpdateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    UpdateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    RunUpdateResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/runs/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            RunUpdateRequestBody req_body;
            req_body.attachments = attachments_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("PATCH", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return RunUpdateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<RunUpdateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    std::optional<std::vector<std::string>> attachments_;
    RequestConfig request_config_;
};

inline RunsClient::ListBuilder RunsClient::list() {
    return ListBuilder(client_);
}
inline RunsClient::CreateBuilder RunsClient::create() {
    return CreateBuilder(client_);
}
inline RunsClient::DeleteBuilder RunsClient::delete_() {
    return DeleteBuilder(client_);
}
inline RunsClient::GetBuilder RunsClient::get() {
    return GetBuilder(client_);
}
inline RunsClient::UpdateBuilder RunsClient::update() {
    return UpdateBuilder(client_);
}

} // namespace tofupilot
