// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <chrono>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"

namespace tofupilot {

class TofuPilot;

class StationsClient {
public:
    explicit StationsClient(TofuPilot& client) noexcept : client_(client) {}

    class ListBuilder;
    ListBuilder list();
    class CreateBuilder;
    CreateBuilder create();
    class GetCurrentBuilder;
    GetCurrentBuilder get_current();
    class GetBuilder;
    GetBuilder get();
    class RemoveBuilder;
    RemoveBuilder remove();
    class UpdateBuilder;
    UpdateBuilder update();

private:
    TofuPilot& client_;
};

class StationsClient::ListBuilder {
public:
    explicit ListBuilder(TofuPilot& client) noexcept : client_(client) {}

    ListBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }
    ListBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }
    ListBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }
    ListBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }

    ListBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    ListBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationListResponse send() {

        std::string path = "/v2/stations";

        std::string query_string;
        {
            std::ostringstream qs;
            bool first = true;
            if (limit_.has_value()) {
                if (!first) qs << "&";
                qs << "limit=" << detail::url_encode(detail::to_query_string(limit_.value()));
                first = false;
            }
            if (cursor_.has_value()) {
                if (!first) qs << "&";
                qs << "cursor=" << detail::url_encode(detail::to_query_string(cursor_.value()));
                first = false;
            }
            if (search_query_.has_value()) {
                if (!first) qs << "&";
                qs << "search_query=" << detail::url_encode(detail::to_query_string(search_query_.value()));
                first = false;
            }
            if (procedure_ids_.has_value()) {
                for (const auto& item : procedure_ids_.value()) {
                    if (!first) qs << "&";
                    qs << "procedure_ids=" << detail::url_encode(detail::to_query_string(item));
                    first = false;
                }
            }
            query_string = qs.str();
        }

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationListResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationListResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> procedure_ids_;
    RequestConfig request_config_;
};

class StationsClient::CreateBuilder {
public:
    explicit CreateBuilder(TofuPilot& client) noexcept : client_(client) {}

    CreateBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }
    CreateBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }
    CreateBuilder& body(StationCreateRequest b) {
        name_ = std::move(b.name);
        if (b.procedure_id.has_value()) procedure_id_ = std::move(b.procedure_id);
        return *this;
    }

    CreateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    CreateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationCreateResponse send() {

        std::string path = "/v2/stations";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            StationCreateRequest req_body;
            if (!name_.has_value()) throw ValidationError("missing required field: name");
            req_body.name = name_.value();
            req_body.procedure_id = procedure_id_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("POST", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationCreateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationCreateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> name_;
    std::optional<std::string> procedure_id_;
    RequestConfig request_config_;
};

class StationsClient::GetCurrentBuilder {
public:
    explicit GetCurrentBuilder(TofuPilot& client) noexcept : client_(client) {}


    GetCurrentBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetCurrentBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationGetCurrentResponse send() {

        std::string path = "/v2/stations/current";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationGetCurrentResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationGetCurrentResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    RequestConfig request_config_;
};

class StationsClient::GetBuilder {
public:
    explicit GetBuilder(TofuPilot& client) noexcept : client_(client) {}

    GetBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    GetBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    GetBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationGetResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/stations/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("GET", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationGetResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationGetResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

class StationsClient::RemoveBuilder {
public:
    explicit RemoveBuilder(TofuPilot& client) noexcept : client_(client) {}

    RemoveBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    RemoveBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    RemoveBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationRemoveResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/stations/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;

        auto result = client_.execute("DELETE", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationRemoveResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationRemoveResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    RequestConfig request_config_;
};

class StationsClient::UpdateBuilder {
public:
    explicit UpdateBuilder(TofuPilot& client) noexcept : client_(client) {}

    UpdateBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }
    UpdateBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }
    UpdateBuilder& image_id(std::string value) {
        image_id_ = std::move(value);
        return *this;
    }
    UpdateBuilder& team_id(std::string value) {
        team_id_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }
    UpdateBuilder& team_id_null() {
        team_id_ = NullableField<std::string>::make_null();
        return *this;
    }
    UpdateBuilder& body(StationUpdateRequestBody b) {
        if (b.name.has_value()) name_ = std::move(b.name);
        if (b.image_id.has_value()) image_id_ = std::move(b.image_id);
        team_id_ = std::move(b.team_id);
        return *this;
    }

    UpdateBuilder& server_url(std::string url) {
        request_config_.server_url = std::move(url);
        return *this;
    }
    UpdateBuilder& timeout(std::chrono::seconds t) {
        request_config_.timeout = t;
        return *this;
    }

    StationUpdateResponse send() {
        if (!id_.has_value()) throw ValidationError("missing required path parameter: id");

        std::string path = "/v2/stations/" + detail::url_encode(id_.value()) + "";

        std::string query_string;

        std::string body_str;
        std::string content_type;
        {
            StationUpdateRequestBody req_body;
            req_body.name = name_;
            req_body.image_id = image_id_;
            if (!team_id_.is_absent()) req_body.team_id = team_id_;
            body_str = nlohmann::json(req_body).dump();
            content_type = "application/json";
        }

        auto result = client_.execute("PATCH", path, body_str, content_type, query_string,
            request_config_.is_default() ? nullptr : &request_config_);

        const auto& resp_body = result->body;
        if (resp_body.empty()) {
            return StationUpdateResponse{};
        }
        try {
            return nlohmann::json::parse(resp_body).get<StationUpdateResponse>();
        } catch (const nlohmann::json::parse_error& e) {
            throw HttpError(std::string("Invalid JSON in response: ") + e.what());
        }
    }

private:
    TofuPilot& client_;
    std::optional<std::string> id_;
    std::optional<std::string> name_;
    std::optional<std::string> image_id_;
    NullableField<std::string> team_id_;
    RequestConfig request_config_;
};

inline StationsClient::ListBuilder StationsClient::list() {
    return ListBuilder(client_);
}
inline StationsClient::CreateBuilder StationsClient::create() {
    return CreateBuilder(client_);
}
inline StationsClient::GetCurrentBuilder StationsClient::get_current() {
    return GetCurrentBuilder(client_);
}
inline StationsClient::GetBuilder StationsClient::get() {
    return GetBuilder(client_);
}
inline StationsClient::RemoveBuilder StationsClient::remove() {
    return RemoveBuilder(client_);
}
inline StationsClient::UpdateBuilder StationsClient::update() {
    return UpdateBuilder(client_);
}

} // namespace tofupilot
