// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include "config.hpp"
#include "detail.hpp"
#include "error.hpp"
#include "types.hpp"
#include "client.hpp"
#include "procedures.hpp"
#include "versions.hpp"
#include "runs.hpp"
#include "attachments.hpp"
#include "units.hpp"
#include "parts.hpp"
#include "revisions.hpp"
#include "batches.hpp"
#include "stations.hpp"
#include "user.hpp"
#include "upload.hpp"

namespace tofupilot {
inline ProceduresClient TofuPilot::procedures() {
    return ProceduresClient(*this);
}
inline VersionsClient TofuPilot::versions() {
    return VersionsClient(*this);
}
inline RunsClient TofuPilot::runs() {
    return RunsClient(*this);
}
inline AttachmentsClient TofuPilot::attachments() {
    return AttachmentsClient(*this);
}
inline UnitsClient TofuPilot::units() {
    return UnitsClient(*this);
}
inline PartsClient TofuPilot::parts() {
    return PartsClient(*this);
}
inline RevisionsClient TofuPilot::revisions() {
    return RevisionsClient(*this);
}
inline BatchesClient TofuPilot::batches() {
    return BatchesClient(*this);
}
inline StationsClient TofuPilot::stations() {
    return StationsClient(*this);
}
inline UserClient TofuPilot::user() {
    return UserClient(*this);
}
} // namespace tofupilot
