// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct AttachmentDeleteRequest {
    /// Upload IDs to delete
    std::vector<std::string> ids;
};

inline void to_json(nlohmann::json& j, const AttachmentDeleteRequest& v) {
    j = nlohmann::json::object();
    j["ids"] = v.ids;
}

inline void from_json(const nlohmann::json& j, AttachmentDeleteRequest& v) {
    if (j.contains("ids") && j["ids"].is_array()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
}

/// Builder for AttachmentDeleteRequest.
class AttachmentDeleteRequestBuilder {
public:
    /// Set the `ids` field.
    /// Upload IDs to delete
    AttachmentDeleteRequestBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    AttachmentDeleteRequest build() const& {
        AttachmentDeleteRequest result;
        if (ids_.has_value()) {
            result.ids = ids_.value();
        }
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    AttachmentDeleteRequest build() && {
        AttachmentDeleteRequest result;
        if (ids_.has_value()) {
            result.ids = std::move(ids_.value());
        }
        return result;
    }

private:
    std::optional<std::vector<std::string>> ids_;
};

} // namespace tofupilot
