// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/batch_list_sort_by.hpp"
#include "tofupilot/models/list_sort_order.hpp"

namespace tofupilot {

struct BatchListRequest {
    std::optional<std::vector<std::string>> ids;
    std::optional<std::vector<std::string>> numbers;
    std::optional<std::string> created_after;
    std::optional<std::string> created_before;
    /// Maximum number of batches to return. Use `cursor` to fetch additional results.
    std::optional<int64_t> limit;
    std::optional<int64_t> cursor;
    std::optional<std::string> search_query;
    std::optional<std::vector<std::string>> part_numbers;
    std::optional<std::vector<std::string>> revision_numbers;
    /// Field to sort results by.
    std::optional<BatchListSortBy> sort_by;
    /// Sort order direction.
    std::optional<ListSortOrder> sort_order;
};

inline void to_json(nlohmann::json& j, const BatchListRequest& v) {
    j = nlohmann::json::object();
    if (v.ids.has_value()) {
        j["ids"] = v.ids.value();
    }
    if (v.numbers.has_value()) {
        j["numbers"] = v.numbers.value();
    }
    if (v.created_after.has_value()) {
        j["created_after"] = v.created_after.value();
    }
    if (v.created_before.has_value()) {
        j["created_before"] = v.created_before.value();
    }
    if (v.limit.has_value()) {
        j["limit"] = v.limit.value();
    }
    if (v.cursor.has_value()) {
        j["cursor"] = v.cursor.value();
    }
    if (v.search_query.has_value()) {
        j["search_query"] = v.search_query.value();
    }
    if (v.part_numbers.has_value()) {
        j["part_numbers"] = v.part_numbers.value();
    }
    if (v.revision_numbers.has_value()) {
        j["revision_numbers"] = v.revision_numbers.value();
    }
    if (v.sort_by.has_value()) {
        j["sort_by"] = v.sort_by.value();
    }
    if (v.sort_order.has_value()) {
        j["sort_order"] = v.sort_order.value();
    }
}

inline void from_json(const nlohmann::json& j, BatchListRequest& v) {
    if (j.contains("ids") && !j["ids"].is_null()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
    if (j.contains("numbers") && !j["numbers"].is_null()) {
        v.numbers = j["numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("created_after") && !j["created_after"].is_null()) {
        v.created_after = j["created_after"].get<std::string>();
    }
    if (j.contains("created_before") && !j["created_before"].is_null()) {
        v.created_before = j["created_before"].get<std::string>();
    }
    if (j.contains("limit") && !j["limit"].is_null()) {
        v.limit = j["limit"].get<int64_t>();
    }
    if (j.contains("cursor") && !j["cursor"].is_null()) {
        v.cursor = j["cursor"].get<int64_t>();
    }
    if (j.contains("search_query") && !j["search_query"].is_null()) {
        v.search_query = j["search_query"].get<std::string>();
    }
    if (j.contains("part_numbers") && !j["part_numbers"].is_null()) {
        v.part_numbers = j["part_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("revision_numbers") && !j["revision_numbers"].is_null()) {
        v.revision_numbers = j["revision_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("sort_by") && !j["sort_by"].is_null()) {
        v.sort_by = j["sort_by"].get<BatchListSortBy>();
    }
    if (j.contains("sort_order") && !j["sort_order"].is_null()) {
        v.sort_order = j["sort_order"].get<ListSortOrder>();
    }
}

/// Builder for BatchListRequest.
class BatchListRequestBuilder {
public:
    /// Set the `ids` field.
    BatchListRequestBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    /// Set the `numbers` field.
    BatchListRequestBuilder& numbers(std::vector<std::string> value) {
        numbers_ = std::move(value);
        return *this;
    }

    /// Set the `created_after` field.
    BatchListRequestBuilder& created_after(std::string value) {
        created_after_ = std::move(value);
        return *this;
    }

    /// Set the `created_before` field.
    BatchListRequestBuilder& created_before(std::string value) {
        created_before_ = std::move(value);
        return *this;
    }

    /// Set the `limit` field.
    /// Maximum number of batches to return. Use `cursor` to fetch additional results.
    BatchListRequestBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }

    /// Set the `cursor` field.
    BatchListRequestBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    /// Set the `search_query` field.
    BatchListRequestBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }

    /// Set the `part_numbers` field.
    BatchListRequestBuilder& part_numbers(std::vector<std::string> value) {
        part_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `revision_numbers` field.
    BatchListRequestBuilder& revision_numbers(std::vector<std::string> value) {
        revision_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `sort_by` field.
    /// Field to sort results by.
    BatchListRequestBuilder& sort_by(BatchListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }

    /// Set the `sort_order` field.
    /// Sort order direction.
    BatchListRequestBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    BatchListRequest build() const& {
        BatchListRequest result;
        result.ids = ids_;
        result.numbers = numbers_;
        result.created_after = created_after_;
        result.created_before = created_before_;
        result.limit = limit_;
        result.cursor = cursor_;
        result.search_query = search_query_;
        result.part_numbers = part_numbers_;
        result.revision_numbers = revision_numbers_;
        result.sort_by = sort_by_;
        result.sort_order = sort_order_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    BatchListRequest build() && {
        BatchListRequest result;
        result.ids = std::move(ids_);
        result.numbers = std::move(numbers_);
        result.created_after = std::move(created_after_);
        result.created_before = std::move(created_before_);
        result.limit = std::move(limit_);
        result.cursor = std::move(cursor_);
        result.search_query = std::move(search_query_);
        result.part_numbers = std::move(part_numbers_);
        result.revision_numbers = std::move(revision_numbers_);
        result.sort_by = std::move(sort_by_);
        result.sort_order = std::move(sort_order_);
        return result;
    }

private:
    std::optional<std::vector<std::string>> ids_;
    std::optional<std::vector<std::string>> numbers_;
    std::optional<std::string> created_after_;
    std::optional<std::string> created_before_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> part_numbers_;
    std::optional<std::vector<std::string>> revision_numbers_;
    std::optional<BatchListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
};

} // namespace tofupilot
