// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/batch_get_part.hpp"

namespace tofupilot {

struct BatchGetUnits {
    /// Unit ID.
    std::string id;
    /// Unit serial number.
    std::string serial_number;
    /// ISO 8601 timestamp when the unit was created.
    std::string created_at;
    /// Part information with revision details for this unit.
    BatchGetPart part;
};

inline void to_json(nlohmann::json& j, const BatchGetUnits& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["serial_number"] = v.serial_number;
    j["created_at"] = v.created_at;
    j["part"] = v.part;
}

inline void from_json(const nlohmann::json& j, BatchGetUnits& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
    if (!j.contains("created_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: created_at", &j);
    }
    v.created_at = j["created_at"].get<std::string>();
    if (!j.contains("part")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: part", &j);
    }
    v.part = j["part"].get<BatchGetPart>();
}

} // namespace tofupilot
