// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct BatchUpdateRequestBody {
    /// New batch number.
    std::string new_number;
};

inline void to_json(nlohmann::json& j, const BatchUpdateRequestBody& v) {
    j = nlohmann::json::object();
    j["new_number"] = v.new_number;
}

inline void from_json(const nlohmann::json& j, BatchUpdateRequestBody& v) {
    if (!j.contains("new_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: new_number", &j);
    }
    v.new_number = j["new_number"].get<std::string>();
}

} // namespace tofupilot
