// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Field to sort results by.
enum class BatchListSortBy {
    Number,
    CreatedAt,
};

NLOHMANN_JSON_SERIALIZE_ENUM(BatchListSortBy, {
    { BatchListSortBy::Number, "number" },
    { BatchListSortBy::CreatedAt, "created_at" },
})

inline std::string to_string(BatchListSortBy e) {
    switch (e) {
        case BatchListSortBy::Number: return "number";
        case BatchListSortBy::CreatedAt: return "created_at";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
