// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/batch_list_created_by_station.hpp"
#include "tofupilot/models/batch_list_created_by_user.hpp"

namespace tofupilot {

struct BatchListData {
    /// Unique identifier for the batch.
    std::string id;
    /// Batch number.
    std::string number;
    /// ISO timestamp when the batch was created.
    std::string created_at;
    /// User who created this batch.
    NullableField<BatchListCreatedByUser> created_by_user;
    /// Station that created this batch.
    NullableField<BatchListCreatedByStation> created_by_station;
    /// Total number of units in this batch.
    int64_t unit_count;
};

inline void to_json(nlohmann::json& j, const BatchListData& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["number"] = v.number;
    j["created_at"] = v.created_at;
    if (!v.created_by_user.is_absent()) {
        if (v.created_by_user.is_null()) {
            j["created_by_user"] = nullptr;
        } else {
            j["created_by_user"] = v.created_by_user.get();
        }
    }
    if (!v.created_by_station.is_absent()) {
        if (v.created_by_station.is_null()) {
            j["created_by_station"] = nullptr;
        } else {
            j["created_by_station"] = v.created_by_station.get();
        }
    }
    j["unit_count"] = v.unit_count;
}

inline void from_json(const nlohmann::json& j, BatchListData& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: number", &j);
    }
    v.number = j["number"].get<std::string>();
    if (!j.contains("created_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: created_at", &j);
    }
    v.created_at = j["created_at"].get<std::string>();
    if (j.contains("created_by_user")) {
        if (j["created_by_user"].is_null()) {
            v.created_by_user = NullableField<BatchListCreatedByUser>::make_null();
        } else {
            v.created_by_user = NullableField<BatchListCreatedByUser>::value(j["created_by_user"].get<BatchListCreatedByUser>());
        }
    }
    if (j.contains("created_by_station")) {
        if (j["created_by_station"].is_null()) {
            v.created_by_station = NullableField<BatchListCreatedByStation>::make_null();
        } else {
            v.created_by_station = NullableField<BatchListCreatedByStation>::value(j["created_by_station"].get<BatchListCreatedByStation>());
        }
    }
    if (!j.contains("unit_count")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: unit_count", &j);
    }
    v.unit_count = j["unit_count"].get<int64_t>();
}

/// Builder for BatchListData.
class BatchListDataBuilder {
public:
    /// Set the `id` field.
    /// Unique identifier for the batch.
    BatchListDataBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `number` field.
    /// Batch number.
    BatchListDataBuilder& number(std::string value) {
        number_ = std::move(value);
        return *this;
    }

    /// Set the `created_at` field.
    /// ISO timestamp when the batch was created.
    BatchListDataBuilder& created_at(std::string value) {
        created_at_ = std::move(value);
        return *this;
    }

    /// Set the `created_by_user` field.
    /// User who created this batch.
    BatchListDataBuilder& created_by_user(BatchListCreatedByUser value) {
        created_by_user_ = NullableField<BatchListCreatedByUser>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `created_by_user` to null.
    BatchListDataBuilder& created_by_user_null() {
        created_by_user_ = NullableField<BatchListCreatedByUser>::make_null();
        return *this;
    }

    /// Set the `created_by_station` field.
    /// Station that created this batch.
    BatchListDataBuilder& created_by_station(BatchListCreatedByStation value) {
        created_by_station_ = NullableField<BatchListCreatedByStation>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `created_by_station` to null.
    BatchListDataBuilder& created_by_station_null() {
        created_by_station_ = NullableField<BatchListCreatedByStation>::make_null();
        return *this;
    }

    /// Set the `unit_count` field.
    /// Total number of units in this batch.
    BatchListDataBuilder& unit_count(int64_t value) {
        unit_count_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    BatchListData build() const& {
        BatchListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!number_.has_value()) {
            throw std::runtime_error("missing required field: number");
        }
        result.number = number_.value();
        if (!created_at_.has_value()) {
            throw std::runtime_error("missing required field: created_at");
        }
        result.created_at = created_at_.value();
        result.created_by_user = created_by_user_;
        result.created_by_station = created_by_station_;
        if (!unit_count_.has_value()) {
            throw std::runtime_error("missing required field: unit_count");
        }
        result.unit_count = unit_count_.value();
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    BatchListData build() && {
        BatchListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!number_.has_value()) {
            throw std::runtime_error("missing required field: number");
        }
        result.number = std::move(number_.value());
        if (!created_at_.has_value()) {
            throw std::runtime_error("missing required field: created_at");
        }
        result.created_at = std::move(created_at_.value());
        result.created_by_user = std::move(created_by_user_);
        result.created_by_station = std::move(created_by_station_);
        if (!unit_count_.has_value()) {
            throw std::runtime_error("missing required field: unit_count");
        }
        result.unit_count = std::move(unit_count_.value());
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> number_;
    std::optional<std::string> created_at_;
    NullableField<BatchListCreatedByUser> created_by_user_;
    NullableField<BatchListCreatedByStation> created_by_station_;
    std::optional<int64_t> unit_count_;
};

} // namespace tofupilot
