// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/provider.hpp"

namespace tofupilot {

struct DeploymentGetRepository {
    std::string full_name;
    Provider provider;
};

inline void to_json(nlohmann::json& j, const DeploymentGetRepository& v) {
    j = nlohmann::json::object();
    j["full_name"] = v.full_name;
    j["provider"] = v.provider;
}

inline void from_json(const nlohmann::json& j, DeploymentGetRepository& v) {
    if (!j.contains("full_name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: full_name", &j);
    }
    v.full_name = j["full_name"].get<std::string>();
    if (!j.contains("provider")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: provider", &j);
    }
    v.provider = j["provider"].get<Provider>();
}

} // namespace tofupilot
