// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Build status of the deployment.
enum class DeploymentGetStatus {
    Pending,
    Building,
    Ready,
    Failed,
};

NLOHMANN_JSON_SERIALIZE_ENUM(DeploymentGetStatus, {
    { DeploymentGetStatus::Pending, "pending" },
    { DeploymentGetStatus::Building, "building" },
    { DeploymentGetStatus::Ready, "ready" },
    { DeploymentGetStatus::Failed, "failed" },
})

inline std::string to_string(DeploymentGetStatus e) {
    switch (e) {
        case DeploymentGetStatus::Pending: return "pending";
        case DeploymentGetStatus::Building: return "building";
        case DeploymentGetStatus::Ready: return "ready";
        case DeploymentGetStatus::Failed: return "failed";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
