// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Deployment mode.
enum class DeploymentGetDeploymentMode {
    Sync,
    Standalone,
};

NLOHMANN_JSON_SERIALIZE_ENUM(DeploymentGetDeploymentMode, {
    { DeploymentGetDeploymentMode::Sync, "sync" },
    { DeploymentGetDeploymentMode::Standalone, "standalone" },
})

inline std::string to_string(DeploymentGetDeploymentMode e) {
    switch (e) {
        case DeploymentGetDeploymentMode::Sync: return "sync";
        case DeploymentGetDeploymentMode::Standalone: return "standalone";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
