// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/level.hpp"

namespace tofupilot {

struct DeploymentGetBuildLogs {
    /// Sequence number ordering the log line within the build.
    int64_t seq;
    /// Severity of the build log line.
    Level level;
    /// Build log line content.
    std::string message;
    /// ISO 8601 timestamp when the log line was emitted.
    std::string created_at;
};

inline void to_json(nlohmann::json& j, const DeploymentGetBuildLogs& v) {
    j = nlohmann::json::object();
    j["seq"] = v.seq;
    j["level"] = v.level;
    j["message"] = v.message;
    j["created_at"] = v.created_at;
}

inline void from_json(const nlohmann::json& j, DeploymentGetBuildLogs& v) {
    if (!j.contains("seq")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: seq", &j);
    }
    v.seq = j["seq"].get<int64_t>();
    if (!j.contains("level")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: level", &j);
    }
    v.level = j["level"].get<Level>();
    if (!j.contains("message")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: message", &j);
    }
    v.message = j["message"].get<std::string>();
    if (!j.contains("created_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: created_at", &j);
    }
    v.created_at = j["created_at"].get<std::string>();
}

} // namespace tofupilot
