// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/deployment_get_status.hpp"
#include "tofupilot/models/deployment_list_commit.hpp"
#include "tofupilot/models/deployment_list_procedure.hpp"
#include "tofupilot/models/deployment_list_repository.hpp"
#include "tofupilot/models/deployment_list_stations.hpp"
#include "tofupilot/models/environment.hpp"
#include "tofupilot/models/trigger.hpp"

namespace tofupilot {

struct DeploymentListData {
    /// Unique identifier for the deployment.
    std::string id;
    /// Deployment environment.
    Environment environment;
    /// How the deployment was triggered.
    Trigger trigger;
    /// Build status of the deployment.
    DeploymentGetStatus status;
    /// True when an auto-push deployment was recorded for audit but never enqueued to build.
    bool skipped;
    /// ISO 8601 timestamp when the build started. Null if not started.
    std::optional<std::string> started_at;
    /// ISO 8601 timestamp when the build ended. Null if not ended.
    std::optional<std::string> ended_at;
    /// ISO 8601 timestamp when the deployment was created.
    std::string deployed_at;
    /// Procedure this deployment targets.
    std::optional<DeploymentListProcedure> procedure;
    /// Git commit the deployment was built from. Null for non-git deployments.
    std::optional<DeploymentListCommit> commit;
    /// Source repository provider. Null for non-git deployments.
    std::optional<DeploymentListRepository> repository;
    /// Stations this deployment has been pushed to.
    std::vector<DeploymentListStations> stations;
};

inline void to_json(nlohmann::json& j, const DeploymentListData& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["environment"] = v.environment;
    j["trigger"] = v.trigger;
    j["status"] = v.status;
    j["skipped"] = v.skipped;
    if (v.started_at.has_value()) {
        j["started_at"] = v.started_at.value();
    }
    if (v.ended_at.has_value()) {
        j["ended_at"] = v.ended_at.value();
    }
    j["deployed_at"] = v.deployed_at;
    if (v.procedure.has_value()) {
        j["procedure"] = v.procedure.value();
    }
    if (v.commit.has_value()) {
        j["commit"] = v.commit.value();
    }
    if (v.repository.has_value()) {
        j["repository"] = v.repository.value();
    }
    j["stations"] = v.stations;
}

inline void from_json(const nlohmann::json& j, DeploymentListData& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("environment")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: environment", &j);
    }
    v.environment = j["environment"].get<Environment>();
    if (!j.contains("trigger")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: trigger", &j);
    }
    v.trigger = j["trigger"].get<Trigger>();
    if (!j.contains("status")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: status", &j);
    }
    v.status = j["status"].get<DeploymentGetStatus>();
    if (!j.contains("skipped")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: skipped", &j);
    }
    v.skipped = j["skipped"].get<bool>();
    if (j.contains("started_at") && !j["started_at"].is_null()) {
        v.started_at = j["started_at"].get<std::string>();
    }
    if (j.contains("ended_at") && !j["ended_at"].is_null()) {
        v.ended_at = j["ended_at"].get<std::string>();
    }
    if (!j.contains("deployed_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: deployed_at", &j);
    }
    v.deployed_at = j["deployed_at"].get<std::string>();
    if (j.contains("procedure") && !j["procedure"].is_null()) {
        v.procedure = j["procedure"].get<DeploymentListProcedure>();
    }
    if (j.contains("commit") && !j["commit"].is_null()) {
        v.commit = j["commit"].get<DeploymentListCommit>();
    }
    if (j.contains("repository") && !j["repository"].is_null()) {
        v.repository = j["repository"].get<DeploymentListRepository>();
    }
    if (j.contains("stations") && j["stations"].is_array()) {
        v.stations = j["stations"].get<std::vector<DeploymentListStations>>();
    }
}

/// Builder for DeploymentListData.
class DeploymentListDataBuilder {
public:
    /// Set the `id` field.
    /// Unique identifier for the deployment.
    DeploymentListDataBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `environment` field.
    /// Deployment environment.
    DeploymentListDataBuilder& environment(Environment value) {
        environment_ = std::move(value);
        return *this;
    }

    /// Set the `trigger` field.
    /// How the deployment was triggered.
    DeploymentListDataBuilder& trigger(Trigger value) {
        trigger_ = std::move(value);
        return *this;
    }

    /// Set the `status` field.
    /// Build status of the deployment.
    DeploymentListDataBuilder& status(DeploymentGetStatus value) {
        status_ = std::move(value);
        return *this;
    }

    /// Set the `skipped` field.
    /// True when an auto-push deployment was recorded for audit but never enqueued to build.
    DeploymentListDataBuilder& skipped(bool value) {
        skipped_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the build started. Null if not started.
    DeploymentListDataBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `ended_at` field.
    /// ISO 8601 timestamp when the build ended. Null if not ended.
    DeploymentListDataBuilder& ended_at(std::string value) {
        ended_at_ = std::move(value);
        return *this;
    }

    /// Set the `deployed_at` field.
    /// ISO 8601 timestamp when the deployment was created.
    DeploymentListDataBuilder& deployed_at(std::string value) {
        deployed_at_ = std::move(value);
        return *this;
    }

    /// Set the `procedure` field.
    /// Procedure this deployment targets.
    DeploymentListDataBuilder& procedure(DeploymentListProcedure value) {
        procedure_ = std::move(value);
        return *this;
    }

    /// Set the `commit` field.
    /// Git commit the deployment was built from. Null for non-git deployments.
    DeploymentListDataBuilder& commit(DeploymentListCommit value) {
        commit_ = std::move(value);
        return *this;
    }

    /// Set the `repository` field.
    /// Source repository provider. Null for non-git deployments.
    DeploymentListDataBuilder& repository(DeploymentListRepository value) {
        repository_ = std::move(value);
        return *this;
    }

    /// Set the `stations` field.
    /// Stations this deployment has been pushed to.
    DeploymentListDataBuilder& stations(std::vector<DeploymentListStations> value) {
        stations_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    DeploymentListData build() const& {
        DeploymentListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!environment_.has_value()) {
            throw std::runtime_error("missing required field: environment");
        }
        result.environment = environment_.value();
        if (!trigger_.has_value()) {
            throw std::runtime_error("missing required field: trigger");
        }
        result.trigger = trigger_.value();
        if (!status_.has_value()) {
            throw std::runtime_error("missing required field: status");
        }
        result.status = status_.value();
        if (!skipped_.has_value()) {
            throw std::runtime_error("missing required field: skipped");
        }
        result.skipped = skipped_.value();
        result.started_at = started_at_;
        result.ended_at = ended_at_;
        if (!deployed_at_.has_value()) {
            throw std::runtime_error("missing required field: deployed_at");
        }
        result.deployed_at = deployed_at_.value();
        result.procedure = procedure_;
        result.commit = commit_;
        result.repository = repository_;
        if (stations_.has_value()) {
            result.stations = stations_.value();
        }
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    DeploymentListData build() && {
        DeploymentListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!environment_.has_value()) {
            throw std::runtime_error("missing required field: environment");
        }
        result.environment = std::move(environment_.value());
        if (!trigger_.has_value()) {
            throw std::runtime_error("missing required field: trigger");
        }
        result.trigger = std::move(trigger_.value());
        if (!status_.has_value()) {
            throw std::runtime_error("missing required field: status");
        }
        result.status = std::move(status_.value());
        if (!skipped_.has_value()) {
            throw std::runtime_error("missing required field: skipped");
        }
        result.skipped = std::move(skipped_.value());
        result.started_at = std::move(started_at_);
        result.ended_at = std::move(ended_at_);
        if (!deployed_at_.has_value()) {
            throw std::runtime_error("missing required field: deployed_at");
        }
        result.deployed_at = std::move(deployed_at_.value());
        result.procedure = std::move(procedure_);
        result.commit = std::move(commit_);
        result.repository = std::move(repository_);
        if (stations_.has_value()) {
            result.stations = std::move(stations_.value());
        }
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<Environment> environment_;
    std::optional<Trigger> trigger_;
    std::optional<DeploymentGetStatus> status_;
    std::optional<bool> skipped_;
    std::optional<std::string> started_at_;
    std::optional<std::string> ended_at_;
    std::optional<std::string> deployed_at_;
    std::optional<DeploymentListProcedure> procedure_;
    std::optional<DeploymentListCommit> commit_;
    std::optional<DeploymentListRepository> repository_;
    std::optional<std::vector<DeploymentListStations>> stations_;
};

} // namespace tofupilot
