// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/deployment_get_status.hpp"
#include "tofupilot/models/environment.hpp"

namespace tofupilot {

struct DeploymentListRequest {
    std::optional<std::vector<std::string>> procedure_ids;
    std::optional<std::vector<Environment>> environments;
    std::optional<std::vector<DeploymentGetStatus>> build_statuses;
    std::optional<bool> pushed;
    std::optional<std::vector<std::string>> branch_names;
    std::optional<std::vector<std::string>> author_usernames;
    std::optional<std::string> deployed_after;
    std::optional<std::string> deployed_before;
    std::optional<std::string> search_query;
    /// Maximum number of deployments to return.
    std::optional<int64_t> limit;
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    std::optional<int64_t> cursor;
};

inline void to_json(nlohmann::json& j, const DeploymentListRequest& v) {
    j = nlohmann::json::object();
    if (v.procedure_ids.has_value()) {
        j["procedure_ids"] = v.procedure_ids.value();
    }
    if (v.environments.has_value()) {
        j["environments"] = v.environments.value();
    }
    if (v.build_statuses.has_value()) {
        j["build_statuses"] = v.build_statuses.value();
    }
    if (v.pushed.has_value()) {
        j["pushed"] = v.pushed.value();
    }
    if (v.branch_names.has_value()) {
        j["branch_names"] = v.branch_names.value();
    }
    if (v.author_usernames.has_value()) {
        j["author_usernames"] = v.author_usernames.value();
    }
    if (v.deployed_after.has_value()) {
        j["deployed_after"] = v.deployed_after.value();
    }
    if (v.deployed_before.has_value()) {
        j["deployed_before"] = v.deployed_before.value();
    }
    if (v.search_query.has_value()) {
        j["search_query"] = v.search_query.value();
    }
    if (v.limit.has_value()) {
        j["limit"] = v.limit.value();
    }
    if (v.cursor.has_value()) {
        j["cursor"] = v.cursor.value();
    }
}

inline void from_json(const nlohmann::json& j, DeploymentListRequest& v) {
    if (j.contains("procedure_ids") && !j["procedure_ids"].is_null()) {
        v.procedure_ids = j["procedure_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("environments") && !j["environments"].is_null()) {
        v.environments = j["environments"].get<std::vector<Environment>>();
    }
    if (j.contains("build_statuses") && !j["build_statuses"].is_null()) {
        v.build_statuses = j["build_statuses"].get<std::vector<DeploymentGetStatus>>();
    }
    if (j.contains("pushed") && !j["pushed"].is_null()) {
        v.pushed = j["pushed"].get<bool>();
    }
    if (j.contains("branch_names") && !j["branch_names"].is_null()) {
        v.branch_names = j["branch_names"].get<std::vector<std::string>>();
    }
    if (j.contains("author_usernames") && !j["author_usernames"].is_null()) {
        v.author_usernames = j["author_usernames"].get<std::vector<std::string>>();
    }
    if (j.contains("deployed_after") && !j["deployed_after"].is_null()) {
        v.deployed_after = j["deployed_after"].get<std::string>();
    }
    if (j.contains("deployed_before") && !j["deployed_before"].is_null()) {
        v.deployed_before = j["deployed_before"].get<std::string>();
    }
    if (j.contains("search_query") && !j["search_query"].is_null()) {
        v.search_query = j["search_query"].get<std::string>();
    }
    if (j.contains("limit") && !j["limit"].is_null()) {
        v.limit = j["limit"].get<int64_t>();
    }
    if (j.contains("cursor") && !j["cursor"].is_null()) {
        v.cursor = j["cursor"].get<int64_t>();
    }
}

/// Builder for DeploymentListRequest.
class DeploymentListRequestBuilder {
public:
    /// Set the `procedure_ids` field.
    DeploymentListRequestBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }

    /// Set the `environments` field.
    DeploymentListRequestBuilder& environments(std::vector<Environment> value) {
        environments_ = std::move(value);
        return *this;
    }

    /// Set the `build_statuses` field.
    DeploymentListRequestBuilder& build_statuses(std::vector<DeploymentGetStatus> value) {
        build_statuses_ = std::move(value);
        return *this;
    }

    /// Set the `pushed` field.
    DeploymentListRequestBuilder& pushed(bool value) {
        pushed_ = std::move(value);
        return *this;
    }

    /// Set the `branch_names` field.
    DeploymentListRequestBuilder& branch_names(std::vector<std::string> value) {
        branch_names_ = std::move(value);
        return *this;
    }

    /// Set the `author_usernames` field.
    DeploymentListRequestBuilder& author_usernames(std::vector<std::string> value) {
        author_usernames_ = std::move(value);
        return *this;
    }

    /// Set the `deployed_after` field.
    DeploymentListRequestBuilder& deployed_after(std::string value) {
        deployed_after_ = std::move(value);
        return *this;
    }

    /// Set the `deployed_before` field.
    DeploymentListRequestBuilder& deployed_before(std::string value) {
        deployed_before_ = std::move(value);
        return *this;
    }

    /// Set the `search_query` field.
    DeploymentListRequestBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }

    /// Set the `limit` field.
    /// Maximum number of deployments to return.
    DeploymentListRequestBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }

    /// Set the `cursor` field.
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    DeploymentListRequestBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    DeploymentListRequest build() const& {
        DeploymentListRequest result;
        result.procedure_ids = procedure_ids_;
        result.environments = environments_;
        result.build_statuses = build_statuses_;
        result.pushed = pushed_;
        result.branch_names = branch_names_;
        result.author_usernames = author_usernames_;
        result.deployed_after = deployed_after_;
        result.deployed_before = deployed_before_;
        result.search_query = search_query_;
        result.limit = limit_;
        result.cursor = cursor_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    DeploymentListRequest build() && {
        DeploymentListRequest result;
        result.procedure_ids = std::move(procedure_ids_);
        result.environments = std::move(environments_);
        result.build_statuses = std::move(build_statuses_);
        result.pushed = std::move(pushed_);
        result.branch_names = std::move(branch_names_);
        result.author_usernames = std::move(author_usernames_);
        result.deployed_after = std::move(deployed_after_);
        result.deployed_before = std::move(deployed_before_);
        result.search_query = std::move(search_query_);
        result.limit = std::move(limit_);
        result.cursor = std::move(cursor_);
        return result;
    }

private:
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<std::vector<Environment>> environments_;
    std::optional<std::vector<DeploymentGetStatus>> build_statuses_;
    std::optional<bool> pushed_;
    std::optional<std::vector<std::string>> branch_names_;
    std::optional<std::vector<std::string>> author_usernames_;
    std::optional<std::string> deployed_after_;
    std::optional<std::string> deployed_before_;
    std::optional<std::string> search_query_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
};

} // namespace tofupilot
