// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/import_tabular_mapping.hpp"

namespace tofupilot {

struct ImportTabularRequest {
    /// ID of a previously uploaded tabular file.
    std::string upload_id;
    /// Procedure to attach the imported run to. Always overrides any procedure referenced in the file. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    std::string procedure_id;
    /// Inline column mapping describing how source columns feed TofuPilot fields. Provide this OR template_id, not both.
    std::optional<ImportTabularMapping> mapping;
    /// ID of a saved mapping template to apply. Provide this OR mapping, not both.
    std::optional<std::string> template_id;
};

inline void to_json(nlohmann::json& j, const ImportTabularRequest& v) {
    j = nlohmann::json::object();
    j["upload_id"] = v.upload_id;
    j["procedure_id"] = v.procedure_id;
    if (v.mapping.has_value()) {
        j["mapping"] = v.mapping.value();
    }
    if (v.template_id.has_value()) {
        j["template_id"] = v.template_id.value();
    }
}

inline void from_json(const nlohmann::json& j, ImportTabularRequest& v) {
    if (!j.contains("upload_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: upload_id", &j);
    }
    v.upload_id = j["upload_id"].get<std::string>();
    if (!j.contains("procedure_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure_id", &j);
    }
    v.procedure_id = j["procedure_id"].get<std::string>();
    if (j.contains("mapping") && !j["mapping"].is_null()) {
        v.mapping = j["mapping"].get<ImportTabularMapping>();
    }
    if (j.contains("template_id") && !j["template_id"].is_null()) {
        v.template_id = j["template_id"].get<std::string>();
    }
}

/// Builder for ImportTabularRequest.
class ImportTabularRequestBuilder {
public:
    /// Set the `upload_id` field.
    /// ID of a previously uploaded tabular file.
    ImportTabularRequestBuilder& upload_id(std::string value) {
        upload_id_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_id` field.
    /// Procedure to attach the imported run to. Always overrides any procedure referenced in the file. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    ImportTabularRequestBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }

    /// Set the `mapping` field.
    /// Inline column mapping describing how source columns feed TofuPilot fields. Provide this OR template_id, not both.
    ImportTabularRequestBuilder& mapping(ImportTabularMapping value) {
        mapping_ = std::move(value);
        return *this;
    }

    /// Set the `template_id` field.
    /// ID of a saved mapping template to apply. Provide this OR mapping, not both.
    ImportTabularRequestBuilder& template_id(std::string value) {
        template_id_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    ImportTabularRequest build() const& {
        ImportTabularRequest result;
        if (!upload_id_.has_value()) {
            throw std::runtime_error("missing required field: upload_id");
        }
        result.upload_id = upload_id_.value();
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = procedure_id_.value();
        result.mapping = mapping_;
        result.template_id = template_id_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    ImportTabularRequest build() && {
        ImportTabularRequest result;
        if (!upload_id_.has_value()) {
            throw std::runtime_error("missing required field: upload_id");
        }
        result.upload_id = std::move(upload_id_.value());
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = std::move(procedure_id_.value());
        result.mapping = std::move(mapping_);
        result.template_id = std::move(template_id_);
        return result;
    }

private:
    std::optional<std::string> upload_id_;
    std::optional<std::string> procedure_id_;
    std::optional<ImportTabularMapping> mapping_;
    std::optional<std::string> template_id_;
};

} // namespace tofupilot
