// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/import_structured_results.hpp"

namespace tofupilot {

/// Run imported successfully
struct ImportStructuredResponse {
    std::vector<ImportStructuredResults> results;
};

inline void to_json(nlohmann::json& j, const ImportStructuredResponse& v) {
    j = nlohmann::json::object();
    j["results"] = v.results;
}

inline void from_json(const nlohmann::json& j, ImportStructuredResponse& v) {
    if (j.contains("results") && j["results"].is_array()) {
        v.results = j["results"].get<std::vector<ImportStructuredResults>>();
    }
}

} // namespace tofupilot
