// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct ImportTabularRevisionNumber2 {
    std::string value;
};

inline void to_json(nlohmann::json& j, const ImportTabularRevisionNumber2& v) {
    j = nlohmann::json::object();
    j["value"] = v.value;
}

inline void from_json(const nlohmann::json& j, ImportTabularRevisionNumber2& v) {
    if (!j.contains("value")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: value", &j);
    }
    v.value = j["value"].get<std::string>();
}

} // namespace tofupilot
