// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/import_tabular_columns.hpp"

namespace tofupilot {

struct ImportTabularMeasurements2 {
    std::string layout;
    std::vector<ImportTabularColumns> columns;
};

inline void to_json(nlohmann::json& j, const ImportTabularMeasurements2& v) {
    j = nlohmann::json::object();
    j["layout"] = v.layout;
    j["columns"] = v.columns;
}

inline void from_json(const nlohmann::json& j, ImportTabularMeasurements2& v) {
    if (!j.contains("layout")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: layout", &j);
    }
    v.layout = j["layout"].get<std::string>();
    if (j.contains("columns") && j["columns"].is_array()) {
        v.columns = j["columns"].get<std::vector<ImportTabularColumns>>();
    }
}

/// Builder for ImportTabularMeasurements2.
class ImportTabularMeasurements2Builder {
public:
    /// Set the `layout` field.
    ImportTabularMeasurements2Builder& layout(std::string value) {
        layout_ = std::move(value);
        return *this;
    }

    /// Set the `columns` field.
    ImportTabularMeasurements2Builder& columns(std::vector<ImportTabularColumns> value) {
        columns_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    ImportTabularMeasurements2 build() const& {
        ImportTabularMeasurements2 result;
        if (!layout_.has_value()) {
            throw std::runtime_error("missing required field: layout");
        }
        result.layout = layout_.value();
        if (columns_.has_value()) {
            result.columns = columns_.value();
        }
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    ImportTabularMeasurements2 build() && {
        ImportTabularMeasurements2 result;
        if (!layout_.has_value()) {
            throw std::runtime_error("missing required field: layout");
        }
        result.layout = std::move(layout_.value());
        if (columns_.has_value()) {
            result.columns = std::move(columns_.value());
        }
        return result;
    }

private:
    std::optional<std::string> layout_;
    std::optional<std::vector<ImportTabularColumns>> columns_;
};

} // namespace tofupilot
