// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/import_tabular_fields.hpp"
#include "tofupilot/models/import_tabular_metadata.hpp"
#include "tofupilot/models/import_tabular_phases.hpp"
#include "tofupilot/models/import_tabular_unit_metadata.hpp"

namespace tofupilot {

/// Inline column mapping describing how source columns feed TofuPilot fields. Provide this OR template_id, not both.
struct ImportTabularMapping {
    ImportTabularFields fields;
    nlohmann::json measurements;
    std::optional<ImportTabularPhases> phases;
    std::optional<std::vector<ImportTabularMetadata>> metadata;
    std::optional<std::vector<ImportTabularUnitMetadata>> unit_metadata;
};

inline void to_json(nlohmann::json& j, const ImportTabularMapping& v) {
    j = nlohmann::json::object();
    j["fields"] = v.fields;
    j["measurements"] = v.measurements;
    if (v.phases.has_value()) {
        j["phases"] = v.phases.value();
    }
    if (v.metadata.has_value()) {
        j["metadata"] = v.metadata.value();
    }
    if (v.unit_metadata.has_value()) {
        j["unitMetadata"] = v.unit_metadata.value();
    }
}

inline void from_json(const nlohmann::json& j, ImportTabularMapping& v) {
    if (!j.contains("fields")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: fields", &j);
    }
    v.fields = j["fields"].get<ImportTabularFields>();
    if (!j.contains("measurements")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: measurements", &j);
    }
    v.measurements = j["measurements"].get<nlohmann::json>();
    if (j.contains("phases") && !j["phases"].is_null()) {
        v.phases = j["phases"].get<ImportTabularPhases>();
    }
    if (j.contains("metadata") && !j["metadata"].is_null()) {
        v.metadata = j["metadata"].get<std::vector<ImportTabularMetadata>>();
    }
    if (j.contains("unitMetadata") && !j["unitMetadata"].is_null()) {
        v.unit_metadata = j["unitMetadata"].get<std::vector<ImportTabularUnitMetadata>>();
    }
}

/// Builder for ImportTabularMapping.
class ImportTabularMappingBuilder {
public:
    /// Set the `fields` field.
    ImportTabularMappingBuilder& fields(ImportTabularFields value) {
        fields_ = std::move(value);
        return *this;
    }

    /// Set the `measurements` field.
    ImportTabularMappingBuilder& measurements(nlohmann::json value) {
        measurements_ = std::move(value);
        return *this;
    }

    /// Set the `phases` field.
    ImportTabularMappingBuilder& phases(ImportTabularPhases value) {
        phases_ = std::move(value);
        return *this;
    }

    /// Set the `metadata` field.
    ImportTabularMappingBuilder& metadata(std::vector<ImportTabularMetadata> value) {
        metadata_ = std::move(value);
        return *this;
    }

    /// Set the `unitMetadata` field.
    ImportTabularMappingBuilder& unit_metadata(std::vector<ImportTabularUnitMetadata> value) {
        unit_metadata_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    ImportTabularMapping build() const& {
        ImportTabularMapping result;
        if (!fields_.has_value()) {
            throw std::runtime_error("missing required field: fields");
        }
        result.fields = fields_.value();
        if (!measurements_.has_value()) {
            throw std::runtime_error("missing required field: measurements");
        }
        result.measurements = measurements_.value();
        result.phases = phases_;
        result.metadata = metadata_;
        result.unit_metadata = unit_metadata_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    ImportTabularMapping build() && {
        ImportTabularMapping result;
        if (!fields_.has_value()) {
            throw std::runtime_error("missing required field: fields");
        }
        result.fields = std::move(fields_.value());
        if (!measurements_.has_value()) {
            throw std::runtime_error("missing required field: measurements");
        }
        result.measurements = std::move(measurements_.value());
        result.phases = std::move(phases_);
        result.metadata = std::move(metadata_);
        result.unit_metadata = std::move(unit_metadata_);
        return result;
    }

private:
    std::optional<ImportTabularFields> fields_;
    std::optional<nlohmann::json> measurements_;
    std::optional<ImportTabularPhases> phases_;
    std::optional<std::vector<ImportTabularMetadata>> metadata_;
    std::optional<std::vector<ImportTabularUnitMetadata>> unit_metadata_;
};

} // namespace tofupilot
