// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/run_get_outcome.hpp"

namespace tofupilot {

struct ImportTabularOutcome2 {
    RunGetOutcome value;
};

inline void to_json(nlohmann::json& j, const ImportTabularOutcome2& v) {
    j = nlohmann::json::object();
    j["value"] = v.value;
}

inline void from_json(const nlohmann::json& j, ImportTabularOutcome2& v) {
    if (!j.contains("value")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: value", &j);
    }
    v.value = j["value"].get<RunGetOutcome>();
}

} // namespace tofupilot
