// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Severity level of the log message following standard system logging levels. Use DEBUG for detailed diagnostic information, INFO for general execution information, WARNING for unexpected events or potential issues, ERROR for serious problems that prevented function execution, CRITICAL for severe errors that may cause program termination.
enum class Level {
    Debug,
    Info,
    Warning,
    Error,
    Critical,
};

NLOHMANN_JSON_SERIALIZE_ENUM(Level, {
    { Level::Debug, "DEBUG" },
    { Level::Info, "INFO" },
    { Level::Warning, "WARNING" },
    { Level::Error, "ERROR" },
    { Level::Critical, "CRITICAL" },
})

inline std::string to_string(Level e) {
    switch (e) {
        case Level::Debug: return "DEBUG";
        case Level::Info: return "INFO";
        case Level::Warning: return "WARNING";
        case Level::Error: return "ERROR";
        case Level::Critical: return "CRITICAL";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
