// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

enum class ListSample {
    Golden,
    Failing,
};

NLOHMANN_JSON_SERIALIZE_ENUM(ListSample, {
    { ListSample::Golden, "golden" },
    { ListSample::Failing, "failing" },
})

inline std::string to_string(ListSample e) {
    switch (e) {
        case ListSample::Golden: return "golden";
        case ListSample::Failing: return "failing";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
