// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/log_get_outcome.hpp"

namespace tofupilot {

/// Run information for this log entry.
struct LogListRun {
    /// ID of the run this log belongs to.
    std::string id;
    /// Outcome of the run.
    LogGetOutcome outcome;
    /// When the run started.
    std::string started_at;
};

inline void to_json(nlohmann::json& j, const LogListRun& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["outcome"] = v.outcome;
    j["started_at"] = v.started_at;
}

inline void from_json(const nlohmann::json& j, LogListRun& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<LogGetOutcome>();
    if (!j.contains("started_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: started_at", &j);
    }
    v.started_at = j["started_at"].get<std::string>();
}

} // namespace tofupilot
