// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/measurement_get_aggregations.hpp"
#include "tofupilot/models/measurement_get_data_series.hpp"
#include "tofupilot/models/measurement_get_phase.hpp"
#include "tofupilot/models/measurement_get_procedure.hpp"
#include "tofupilot/models/measurement_get_run.hpp"
#include "tofupilot/models/measurement_get_validators.hpp"
#include "tofupilot/models/outcome.hpp"

namespace tofupilot {

/// Measurement retrieved successfully
struct MeasurementGetResponse {
    std::string id;
    std::string name;
    Outcome outcome;
    NullableField<std::string> units;
    std::optional<std::vector<MeasurementGetValidators>> validators;
    NullableField<std::vector<MeasurementGetAggregations>> aggregations;
    std::optional<nlohmann::json> measured_value;
    std::optional<std::vector<MeasurementGetDataSeries>> data_series;
    NullableField<std::string> docstring;
    MeasurementGetPhase phase;
    MeasurementGetRun run;
    MeasurementGetProcedure procedure;
};

inline void to_json(nlohmann::json& j, const MeasurementGetResponse& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["outcome"] = v.outcome;
    if (!v.units.is_absent()) {
        if (v.units.is_null()) {
            j["units"] = nullptr;
        } else {
            j["units"] = v.units.get();
        }
    }
    if (v.validators.has_value()) {
        j["validators"] = v.validators.value();
    }
    if (!v.aggregations.is_absent()) {
        if (v.aggregations.is_null()) {
            j["aggregations"] = nullptr;
        } else {
            j["aggregations"] = v.aggregations.get();
        }
    }
    if (v.measured_value.has_value()) {
        j["measured_value"] = v.measured_value.value();
    }
    if (v.data_series.has_value()) {
        j["data_series"] = v.data_series.value();
    }
    if (!v.docstring.is_absent()) {
        if (v.docstring.is_null()) {
            j["docstring"] = nullptr;
        } else {
            j["docstring"] = v.docstring.get();
        }
    }
    j["phase"] = v.phase;
    j["run"] = v.run;
    j["procedure"] = v.procedure;
}

inline void from_json(const nlohmann::json& j, MeasurementGetResponse& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<Outcome>();
    if (j.contains("units")) {
        if (j["units"].is_null()) {
            v.units = NullableField<std::string>::make_null();
        } else {
            v.units = NullableField<std::string>::value(j["units"].get<std::string>());
        }
    }
    if (j.contains("validators") && !j["validators"].is_null()) {
        v.validators = j["validators"].get<std::vector<MeasurementGetValidators>>();
    }
    if (j.contains("aggregations")) {
        if (j["aggregations"].is_null()) {
            v.aggregations = NullableField<std::vector<MeasurementGetAggregations>>::make_null();
        } else {
            v.aggregations = NullableField<std::vector<MeasurementGetAggregations>>::value(j["aggregations"].get<std::vector<MeasurementGetAggregations>>());
        }
    }
    if (j.contains("measured_value") && !j["measured_value"].is_null()) {
        v.measured_value = j["measured_value"].get<nlohmann::json>();
    }
    if (j.contains("data_series") && !j["data_series"].is_null()) {
        v.data_series = j["data_series"].get<std::vector<MeasurementGetDataSeries>>();
    }
    if (j.contains("docstring")) {
        if (j["docstring"].is_null()) {
            v.docstring = NullableField<std::string>::make_null();
        } else {
            v.docstring = NullableField<std::string>::value(j["docstring"].get<std::string>());
        }
    }
    if (!j.contains("phase")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: phase", &j);
    }
    v.phase = j["phase"].get<MeasurementGetPhase>();
    if (!j.contains("run")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: run", &j);
    }
    v.run = j["run"].get<MeasurementGetRun>();
    if (!j.contains("procedure")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure", &j);
    }
    v.procedure = j["procedure"].get<MeasurementGetProcedure>();
}

} // namespace tofupilot
