// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/measurement_list_validators.hpp"
#include "tofupilot/models/measurement_type.hpp"
#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/sample.hpp"

namespace tofupilot {

struct MeasurementListData {
    /// Unique identifier for the measurement.
    std::string id;
    /// Name of the phase this measurement belongs to.
    std::string phase_name;
    /// Name of the measurement.
    std::string measurement_name;
    /// ISO 8601 timestamp when the measurement's phase started.
    std::optional<std::string> started_at;
    /// Numeric value, when the measurement is numeric. Null otherwise.
    std::optional<double> value;
    /// Boolean value, when the measurement is boolean. Null otherwise.
    std::optional<bool> bool_value;
    /// String value, when the measurement is a string. Null otherwise.
    std::optional<std::string> string_value;
    /// Measurement units, when applicable.
    std::optional<std::string> units;
    /// Outcome of the measurement.
    Outcome measurement_outcome;
    /// ID of the run this measurement belongs to.
    std::string run_id;
    /// Serial number of the unit tested.
    std::optional<std::string> serial_number;
    /// Sample class of the unit (golden or failing). Null for regular units.
    std::optional<Sample> sample;
    /// Value type of the measurement.
    MeasurementType measurement_type;
    /// Retry attempt number of the phase this measurement belongs to (0 for the first attempt).
    int64_t retry_count;
    /// True when this measurement comes from the final attempt of its phase.
    bool is_final_attempt;
    /// Validators applied to this measurement. Null when none.
    std::optional<std::vector<MeasurementListValidators>> validators;
};

inline void to_json(nlohmann::json& j, const MeasurementListData& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["phase_name"] = v.phase_name;
    j["measurement_name"] = v.measurement_name;
    if (v.started_at.has_value()) {
        j["started_at"] = v.started_at.value();
    }
    if (v.value.has_value()) {
        j["value"] = v.value.value();
    }
    if (v.bool_value.has_value()) {
        j["bool_value"] = v.bool_value.value();
    }
    if (v.string_value.has_value()) {
        j["string_value"] = v.string_value.value();
    }
    if (v.units.has_value()) {
        j["units"] = v.units.value();
    }
    j["measurement_outcome"] = v.measurement_outcome;
    j["run_id"] = v.run_id;
    if (v.serial_number.has_value()) {
        j["serial_number"] = v.serial_number.value();
    }
    if (v.sample.has_value()) {
        j["sample"] = v.sample.value();
    }
    j["measurement_type"] = v.measurement_type;
    j["retry_count"] = v.retry_count;
    j["is_final_attempt"] = v.is_final_attempt;
    if (v.validators.has_value()) {
        j["validators"] = v.validators.value();
    }
}

inline void from_json(const nlohmann::json& j, MeasurementListData& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("phase_name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: phase_name", &j);
    }
    v.phase_name = j["phase_name"].get<std::string>();
    if (!j.contains("measurement_name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: measurement_name", &j);
    }
    v.measurement_name = j["measurement_name"].get<std::string>();
    if (j.contains("started_at") && !j["started_at"].is_null()) {
        v.started_at = j["started_at"].get<std::string>();
    }
    if (j.contains("value") && !j["value"].is_null()) {
        v.value = j["value"].get<double>();
    }
    if (j.contains("bool_value") && !j["bool_value"].is_null()) {
        v.bool_value = j["bool_value"].get<bool>();
    }
    if (j.contains("string_value") && !j["string_value"].is_null()) {
        v.string_value = j["string_value"].get<std::string>();
    }
    if (j.contains("units") && !j["units"].is_null()) {
        v.units = j["units"].get<std::string>();
    }
    if (!j.contains("measurement_outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: measurement_outcome", &j);
    }
    v.measurement_outcome = j["measurement_outcome"].get<Outcome>();
    if (!j.contains("run_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: run_id", &j);
    }
    v.run_id = j["run_id"].get<std::string>();
    if (j.contains("serial_number") && !j["serial_number"].is_null()) {
        v.serial_number = j["serial_number"].get<std::string>();
    }
    if (j.contains("sample") && !j["sample"].is_null()) {
        v.sample = j["sample"].get<Sample>();
    }
    if (!j.contains("measurement_type")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: measurement_type", &j);
    }
    v.measurement_type = j["measurement_type"].get<MeasurementType>();
    if (!j.contains("retry_count")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: retry_count", &j);
    }
    v.retry_count = j["retry_count"].get<int64_t>();
    if (!j.contains("is_final_attempt")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: is_final_attempt", &j);
    }
    v.is_final_attempt = j["is_final_attempt"].get<bool>();
    if (j.contains("validators") && !j["validators"].is_null()) {
        v.validators = j["validators"].get<std::vector<MeasurementListValidators>>();
    }
}

/// Builder for MeasurementListData.
class MeasurementListDataBuilder {
public:
    /// Set the `id` field.
    /// Unique identifier for the measurement.
    MeasurementListDataBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `phase_name` field.
    /// Name of the phase this measurement belongs to.
    MeasurementListDataBuilder& phase_name(std::string value) {
        phase_name_ = std::move(value);
        return *this;
    }

    /// Set the `measurement_name` field.
    /// Name of the measurement.
    MeasurementListDataBuilder& measurement_name(std::string value) {
        measurement_name_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the measurement's phase started.
    MeasurementListDataBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `value` field.
    /// Numeric value, when the measurement is numeric. Null otherwise.
    MeasurementListDataBuilder& value(double value) {
        value_ = std::move(value);
        return *this;
    }

    /// Set the `bool_value` field.
    /// Boolean value, when the measurement is boolean. Null otherwise.
    MeasurementListDataBuilder& bool_value(bool value) {
        bool_value_ = std::move(value);
        return *this;
    }

    /// Set the `string_value` field.
    /// String value, when the measurement is a string. Null otherwise.
    MeasurementListDataBuilder& string_value(std::string value) {
        string_value_ = std::move(value);
        return *this;
    }

    /// Set the `units` field.
    /// Measurement units, when applicable.
    MeasurementListDataBuilder& units(std::string value) {
        units_ = std::move(value);
        return *this;
    }

    /// Set the `measurement_outcome` field.
    /// Outcome of the measurement.
    MeasurementListDataBuilder& measurement_outcome(Outcome value) {
        measurement_outcome_ = std::move(value);
        return *this;
    }

    /// Set the `run_id` field.
    /// ID of the run this measurement belongs to.
    MeasurementListDataBuilder& run_id(std::string value) {
        run_id_ = std::move(value);
        return *this;
    }

    /// Set the `serial_number` field.
    /// Serial number of the unit tested.
    MeasurementListDataBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `sample` field.
    /// Sample class of the unit (golden or failing). Null for regular units.
    MeasurementListDataBuilder& sample(Sample value) {
        sample_ = std::move(value);
        return *this;
    }

    /// Set the `measurement_type` field.
    /// Value type of the measurement.
    MeasurementListDataBuilder& measurement_type(MeasurementType value) {
        measurement_type_ = std::move(value);
        return *this;
    }

    /// Set the `retry_count` field.
    /// Retry attempt number of the phase this measurement belongs to (0 for the first attempt).
    MeasurementListDataBuilder& retry_count(int64_t value) {
        retry_count_ = std::move(value);
        return *this;
    }

    /// Set the `is_final_attempt` field.
    /// True when this measurement comes from the final attempt of its phase.
    MeasurementListDataBuilder& is_final_attempt(bool value) {
        is_final_attempt_ = std::move(value);
        return *this;
    }

    /// Set the `validators` field.
    /// Validators applied to this measurement. Null when none.
    MeasurementListDataBuilder& validators(std::vector<MeasurementListValidators> value) {
        validators_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    MeasurementListData build() const& {
        MeasurementListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!phase_name_.has_value()) {
            throw std::runtime_error("missing required field: phase_name");
        }
        result.phase_name = phase_name_.value();
        if (!measurement_name_.has_value()) {
            throw std::runtime_error("missing required field: measurement_name");
        }
        result.measurement_name = measurement_name_.value();
        result.started_at = started_at_;
        result.value = value_;
        result.bool_value = bool_value_;
        result.string_value = string_value_;
        result.units = units_;
        if (!measurement_outcome_.has_value()) {
            throw std::runtime_error("missing required field: measurement_outcome");
        }
        result.measurement_outcome = measurement_outcome_.value();
        if (!run_id_.has_value()) {
            throw std::runtime_error("missing required field: run_id");
        }
        result.run_id = run_id_.value();
        result.serial_number = serial_number_;
        result.sample = sample_;
        if (!measurement_type_.has_value()) {
            throw std::runtime_error("missing required field: measurement_type");
        }
        result.measurement_type = measurement_type_.value();
        if (!retry_count_.has_value()) {
            throw std::runtime_error("missing required field: retry_count");
        }
        result.retry_count = retry_count_.value();
        if (!is_final_attempt_.has_value()) {
            throw std::runtime_error("missing required field: is_final_attempt");
        }
        result.is_final_attempt = is_final_attempt_.value();
        result.validators = validators_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    MeasurementListData build() && {
        MeasurementListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!phase_name_.has_value()) {
            throw std::runtime_error("missing required field: phase_name");
        }
        result.phase_name = std::move(phase_name_.value());
        if (!measurement_name_.has_value()) {
            throw std::runtime_error("missing required field: measurement_name");
        }
        result.measurement_name = std::move(measurement_name_.value());
        result.started_at = std::move(started_at_);
        result.value = std::move(value_);
        result.bool_value = std::move(bool_value_);
        result.string_value = std::move(string_value_);
        result.units = std::move(units_);
        if (!measurement_outcome_.has_value()) {
            throw std::runtime_error("missing required field: measurement_outcome");
        }
        result.measurement_outcome = std::move(measurement_outcome_.value());
        if (!run_id_.has_value()) {
            throw std::runtime_error("missing required field: run_id");
        }
        result.run_id = std::move(run_id_.value());
        result.serial_number = std::move(serial_number_);
        result.sample = std::move(sample_);
        if (!measurement_type_.has_value()) {
            throw std::runtime_error("missing required field: measurement_type");
        }
        result.measurement_type = std::move(measurement_type_.value());
        if (!retry_count_.has_value()) {
            throw std::runtime_error("missing required field: retry_count");
        }
        result.retry_count = std::move(retry_count_.value());
        if (!is_final_attempt_.has_value()) {
            throw std::runtime_error("missing required field: is_final_attempt");
        }
        result.is_final_attempt = std::move(is_final_attempt_.value());
        result.validators = std::move(validators_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> phase_name_;
    std::optional<std::string> measurement_name_;
    std::optional<std::string> started_at_;
    std::optional<double> value_;
    std::optional<bool> bool_value_;
    std::optional<std::string> string_value_;
    std::optional<std::string> units_;
    std::optional<Outcome> measurement_outcome_;
    std::optional<std::string> run_id_;
    std::optional<std::string> serial_number_;
    std::optional<Sample> sample_;
    std::optional<MeasurementType> measurement_type_;
    std::optional<int64_t> retry_count_;
    std::optional<bool> is_final_attempt_;
    std::optional<std::vector<MeasurementListValidators>> validators_;
};

} // namespace tofupilot
