// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"

namespace tofupilot {

struct MeasurementGetRun {
    std::string id;
    NullableField<std::string> outcome;
    NullableField<std::string> serial_number;
};

inline void to_json(nlohmann::json& j, const MeasurementGetRun& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    if (!v.outcome.is_absent()) {
        if (v.outcome.is_null()) {
            j["outcome"] = nullptr;
        } else {
            j["outcome"] = v.outcome.get();
        }
    }
    if (!v.serial_number.is_absent()) {
        if (v.serial_number.is_null()) {
            j["serial_number"] = nullptr;
        } else {
            j["serial_number"] = v.serial_number.get();
        }
    }
}

inline void from_json(const nlohmann::json& j, MeasurementGetRun& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (j.contains("outcome")) {
        if (j["outcome"].is_null()) {
            v.outcome = NullableField<std::string>::make_null();
        } else {
            v.outcome = NullableField<std::string>::value(j["outcome"].get<std::string>());
        }
    }
    if (j.contains("serial_number")) {
        if (j["serial_number"].is_null()) {
            v.serial_number = NullableField<std::string>::make_null();
        } else {
            v.serial_number = NullableField<std::string>::value(j["serial_number"].get<std::string>());
        }
    }
}

/// Builder for MeasurementGetRun.
class MeasurementGetRunBuilder {
public:
    /// Set the `id` field.
    MeasurementGetRunBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    MeasurementGetRunBuilder& outcome(std::string value) {
        outcome_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `outcome` to null.
    MeasurementGetRunBuilder& outcome_null() {
        outcome_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `serial_number` field.
    MeasurementGetRunBuilder& serial_number(std::string value) {
        serial_number_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `serial_number` to null.
    MeasurementGetRunBuilder& serial_number_null() {
        serial_number_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    MeasurementGetRun build() const& {
        MeasurementGetRun result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        result.outcome = outcome_;
        result.serial_number = serial_number_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    MeasurementGetRun build() && {
        MeasurementGetRun result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        result.outcome = std::move(outcome_);
        result.serial_number = std::move(serial_number_);
        return result;
    }

private:
    std::optional<std::string> id_;
    NullableField<std::string> outcome_;
    NullableField<std::string> serial_number_;
};

} // namespace tofupilot
