// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct PartListMetadataQueryParam2 {
    std::optional<double> gte;
    std::optional<double> lte;
    std::optional<double> gt;
    std::optional<double> lt;
    std::optional<double> eq;
};

inline void to_json(nlohmann::json& j, const PartListMetadataQueryParam2& v) {
    j = nlohmann::json::object();
    if (v.gte.has_value()) {
        j["gte"] = v.gte.value();
    }
    if (v.lte.has_value()) {
        j["lte"] = v.lte.value();
    }
    if (v.gt.has_value()) {
        j["gt"] = v.gt.value();
    }
    if (v.lt.has_value()) {
        j["lt"] = v.lt.value();
    }
    if (v.eq.has_value()) {
        j["eq"] = v.eq.value();
    }
}

inline void from_json(const nlohmann::json& j, PartListMetadataQueryParam2& v) {
    if (j.contains("gte") && !j["gte"].is_null()) {
        v.gte = j["gte"].get<double>();
    }
    if (j.contains("lte") && !j["lte"].is_null()) {
        v.lte = j["lte"].get<double>();
    }
    if (j.contains("gt") && !j["gt"].is_null()) {
        v.gt = j["gt"].get<double>();
    }
    if (j.contains("lt") && !j["lt"].is_null()) {
        v.lt = j["lt"].get<double>();
    }
    if (j.contains("eq") && !j["eq"].is_null()) {
        v.eq = j["eq"].get<double>();
    }
}

/// Builder for PartListMetadataQueryParam2.
class PartListMetadataQueryParam2Builder {
public:
    /// Set the `gte` field.
    PartListMetadataQueryParam2Builder& gte(double value) {
        gte_ = std::move(value);
        return *this;
    }

    /// Set the `lte` field.
    PartListMetadataQueryParam2Builder& lte(double value) {
        lte_ = std::move(value);
        return *this;
    }

    /// Set the `gt` field.
    PartListMetadataQueryParam2Builder& gt(double value) {
        gt_ = std::move(value);
        return *this;
    }

    /// Set the `lt` field.
    PartListMetadataQueryParam2Builder& lt(double value) {
        lt_ = std::move(value);
        return *this;
    }

    /// Set the `eq` field.
    PartListMetadataQueryParam2Builder& eq(double value) {
        eq_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    PartListMetadataQueryParam2 build() const& {
        PartListMetadataQueryParam2 result;
        result.gte = gte_;
        result.lte = lte_;
        result.gt = gt_;
        result.lt = lt_;
        result.eq = eq_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    PartListMetadataQueryParam2 build() && {
        PartListMetadataQueryParam2 result;
        result.gte = std::move(gte_);
        result.lte = std::move(lte_);
        result.gt = std::move(gt_);
        result.lt = std::move(lt_);
        result.eq = std::move(eq_);
        return result;
    }

private:
    std::optional<double> gte_;
    std::optional<double> lte_;
    std::optional<double> gt_;
    std::optional<double> lt_;
    std::optional<double> eq_;
};

} // namespace tofupilot
