// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Part associated with this revision.
struct PartGetRevisionPart {
    /// Unique identifier of the part.
    std::string id;
    /// Part number.
    std::string number;
    /// Name of the part.
    std::string name;
};

inline void to_json(nlohmann::json& j, const PartGetRevisionPart& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["number"] = v.number;
    j["name"] = v.name;
}

inline void from_json(const nlohmann::json& j, PartGetRevisionPart& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: number", &j);
    }
    v.number = j["number"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
}

} // namespace tofupilot
