// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct PartGetRequest {
    /// Part number of the part to retrieve.
    std::string number;
};

inline void to_json(nlohmann::json& j, const PartGetRequest& v) {
    j = nlohmann::json::object();
    j["number"] = v.number;
}

inline void from_json(const nlohmann::json& j, PartGetRequest& v) {
    if (!j.contains("number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: number", &j);
    }
    v.number = j["number"].get<std::string>();
}

} // namespace tofupilot
