// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/part_list_data.hpp"
#include "tofupilot/models/part_list_meta.hpp"

namespace tofupilot {

/// Parts retrieved successfully
struct PartListResponse {
    /// List of parts matching the search criteria.
    std::vector<PartListData> data;
    /// Pagination metadata.
    PartListMeta meta;
};

inline void to_json(nlohmann::json& j, const PartListResponse& v) {
    j = nlohmann::json::object();
    j["data"] = v.data;
    j["meta"] = v.meta;
}

inline void from_json(const nlohmann::json& j, PartListResponse& v) {
    if (j.contains("data") && j["data"].is_array()) {
        v.data = j["data"].get<std::vector<PartListData>>();
    }
    if (!j.contains("meta")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: meta", &j);
    }
    v.meta = j["meta"].get<PartListMeta>();
}

} // namespace tofupilot
