// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Field to sort results by.
enum class PartListSortBy {
    Name,
    Number,
    CreatedAt,
};

NLOHMANN_JSON_SERIALIZE_ENUM(PartListSortBy, {
    { PartListSortBy::Name, "name" },
    { PartListSortBy::Number, "number" },
    { PartListSortBy::CreatedAt, "created_at" },
})

inline std::string to_string(PartListSortBy e) {
    switch (e) {
        case PartListSortBy::Name: return "name";
        case PartListSortBy::Number: return "number";
        case PartListSortBy::CreatedAt: return "created_at";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
