// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/phase_list_data.hpp"
#include "tofupilot/models/phase_list_meta.hpp"

namespace tofupilot {

/// Phases retrieved successfully
struct PhaseListResponse {
    /// The list of phases matching the request.
    std::vector<PhaseListData> data;
    /// Pagination metadata.
    PhaseListMeta meta;
};

inline void to_json(nlohmann::json& j, const PhaseListResponse& v) {
    j = nlohmann::json::object();
    j["data"] = v.data;
    j["meta"] = v.meta;
}

inline void from_json(const nlohmann::json& j, PhaseListResponse& v) {
    if (j.contains("data") && j["data"].is_array()) {
        v.data = j["data"].get<std::vector<PhaseListData>>();
    }
    if (!j.contains("meta")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: meta", &j);
    }
    v.meta = j["meta"].get<PhaseListMeta>();
}

} // namespace tofupilot
