// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/phase_get_aggregations.hpp"
#include "tofupilot/models/phase_get_data_series.hpp"
#include "tofupilot/models/phase_get_validators.hpp"

namespace tofupilot {

struct PhaseGetMeasurements {
    std::string id;
    std::string name;
    Outcome outcome;
    NullableField<std::string> units;
    std::optional<std::vector<PhaseGetValidators>> validators;
    NullableField<std::vector<PhaseGetAggregations>> aggregations;
    std::optional<nlohmann::json> measured_value;
    std::optional<std::vector<PhaseGetDataSeries>> data_series;
    NullableField<std::string> docstring;
};

inline void to_json(nlohmann::json& j, const PhaseGetMeasurements& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["outcome"] = v.outcome;
    if (!v.units.is_absent()) {
        if (v.units.is_null()) {
            j["units"] = nullptr;
        } else {
            j["units"] = v.units.get();
        }
    }
    if (v.validators.has_value()) {
        j["validators"] = v.validators.value();
    }
    if (!v.aggregations.is_absent()) {
        if (v.aggregations.is_null()) {
            j["aggregations"] = nullptr;
        } else {
            j["aggregations"] = v.aggregations.get();
        }
    }
    if (v.measured_value.has_value()) {
        j["measured_value"] = v.measured_value.value();
    }
    if (v.data_series.has_value()) {
        j["data_series"] = v.data_series.value();
    }
    if (!v.docstring.is_absent()) {
        if (v.docstring.is_null()) {
            j["docstring"] = nullptr;
        } else {
            j["docstring"] = v.docstring.get();
        }
    }
}

inline void from_json(const nlohmann::json& j, PhaseGetMeasurements& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<Outcome>();
    if (j.contains("units")) {
        if (j["units"].is_null()) {
            v.units = NullableField<std::string>::make_null();
        } else {
            v.units = NullableField<std::string>::value(j["units"].get<std::string>());
        }
    }
    if (j.contains("validators") && !j["validators"].is_null()) {
        v.validators = j["validators"].get<std::vector<PhaseGetValidators>>();
    }
    if (j.contains("aggregations")) {
        if (j["aggregations"].is_null()) {
            v.aggregations = NullableField<std::vector<PhaseGetAggregations>>::make_null();
        } else {
            v.aggregations = NullableField<std::vector<PhaseGetAggregations>>::value(j["aggregations"].get<std::vector<PhaseGetAggregations>>());
        }
    }
    if (j.contains("measured_value") && !j["measured_value"].is_null()) {
        v.measured_value = j["measured_value"].get<nlohmann::json>();
    }
    if (j.contains("data_series") && !j["data_series"].is_null()) {
        v.data_series = j["data_series"].get<std::vector<PhaseGetDataSeries>>();
    }
    if (j.contains("docstring")) {
        if (j["docstring"].is_null()) {
            v.docstring = NullableField<std::string>::make_null();
        } else {
            v.docstring = NullableField<std::string>::value(j["docstring"].get<std::string>());
        }
    }
}

/// Builder for PhaseGetMeasurements.
class PhaseGetMeasurementsBuilder {
public:
    /// Set the `id` field.
    PhaseGetMeasurementsBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    PhaseGetMeasurementsBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    PhaseGetMeasurementsBuilder& outcome(Outcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `units` field.
    PhaseGetMeasurementsBuilder& units(std::string value) {
        units_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `units` to null.
    PhaseGetMeasurementsBuilder& units_null() {
        units_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `validators` field.
    PhaseGetMeasurementsBuilder& validators(std::vector<PhaseGetValidators> value) {
        validators_ = std::move(value);
        return *this;
    }

    /// Set the `aggregations` field.
    PhaseGetMeasurementsBuilder& aggregations(std::vector<PhaseGetAggregations> value) {
        aggregations_ = NullableField<std::vector<PhaseGetAggregations>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `aggregations` to null.
    PhaseGetMeasurementsBuilder& aggregations_null() {
        aggregations_ = NullableField<std::vector<PhaseGetAggregations>>::make_null();
        return *this;
    }

    /// Set the `measured_value` field.
    PhaseGetMeasurementsBuilder& measured_value(nlohmann::json value) {
        measured_value_ = std::move(value);
        return *this;
    }

    /// Set the `data_series` field.
    PhaseGetMeasurementsBuilder& data_series(std::vector<PhaseGetDataSeries> value) {
        data_series_ = std::move(value);
        return *this;
    }

    /// Set the `docstring` field.
    PhaseGetMeasurementsBuilder& docstring(std::string value) {
        docstring_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `docstring` to null.
    PhaseGetMeasurementsBuilder& docstring_null() {
        docstring_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    PhaseGetMeasurements build() const& {
        PhaseGetMeasurements result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        result.units = units_;
        result.validators = validators_;
        result.aggregations = aggregations_;
        result.measured_value = measured_value_;
        result.data_series = data_series_;
        result.docstring = docstring_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    PhaseGetMeasurements build() && {
        PhaseGetMeasurements result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        result.units = std::move(units_);
        result.validators = std::move(validators_);
        result.aggregations = std::move(aggregations_);
        result.measured_value = std::move(measured_value_);
        result.data_series = std::move(data_series_);
        result.docstring = std::move(docstring_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> name_;
    std::optional<Outcome> outcome_;
    NullableField<std::string> units_;
    std::optional<std::vector<PhaseGetValidators>> validators_;
    NullableField<std::vector<PhaseGetAggregations>> aggregations_;
    std::optional<nlohmann::json> measured_value_;
    std::optional<std::vector<PhaseGetDataSeries>> data_series_;
    NullableField<std::string> docstring_;
};

} // namespace tofupilot
