// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Field to sort results by.
enum class PhaseListSortBy {
    StartedAt,
    Duration,
    Outcome,
    SerialNumber,
    PhaseName,
};

NLOHMANN_JSON_SERIALIZE_ENUM(PhaseListSortBy, {
    { PhaseListSortBy::StartedAt, "started_at" },
    { PhaseListSortBy::Duration, "duration" },
    { PhaseListSortBy::Outcome, "outcome" },
    { PhaseListSortBy::SerialNumber, "serial_number" },
    { PhaseListSortBy::PhaseName, "phase_name" },
})

inline std::string to_string(PhaseListSortBy e) {
    switch (e) {
        case PhaseListSortBy::StartedAt: return "started_at";
        case PhaseListSortBy::Duration: return "duration";
        case PhaseListSortBy::Outcome: return "outcome";
        case PhaseListSortBy::SerialNumber: return "serial_number";
        case PhaseListSortBy::PhaseName: return "phase_name";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
