// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/phase_get_data_series_aggregations_validators.hpp"

namespace tofupilot {

/// Aggregation result with computed value and optional validators.
struct PhaseGetDataSeriesAggregations {
    /// Unique identifier for the aggregation.
    std::string id;
    /// Aggregation type (e.g., MIN, MAX, MEAN, RANGE, STD_DEV).
    std::string type;
    /// Aggregation validation result: PASS, FAIL, UNSET, or null if no validators.
    std::optional<Outcome> outcome;
    /// Computed aggregation value. Type depends on aggregation type.
    std::optional<nlohmann::json> value;
    /// Unit of measurement for the aggregated value.
    NullableField<std::string> unit;
    /// Validators applied to the aggregated value.
    NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>> validators;
};

inline void to_json(nlohmann::json& j, const PhaseGetDataSeriesAggregations& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["type"] = v.type;
    if (v.outcome.has_value()) {
        j["outcome"] = v.outcome.value();
    }
    if (v.value.has_value()) {
        j["value"] = v.value.value();
    }
    if (!v.unit.is_absent()) {
        if (v.unit.is_null()) {
            j["unit"] = nullptr;
        } else {
            j["unit"] = v.unit.get();
        }
    }
    if (!v.validators.is_absent()) {
        if (v.validators.is_null()) {
            j["validators"] = nullptr;
        } else {
            j["validators"] = v.validators.get();
        }
    }
}

inline void from_json(const nlohmann::json& j, PhaseGetDataSeriesAggregations& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("type")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: type", &j);
    }
    v.type = j["type"].get<std::string>();
    if (j.contains("outcome") && !j["outcome"].is_null()) {
        v.outcome = j["outcome"].get<Outcome>();
    }
    if (j.contains("value") && !j["value"].is_null()) {
        v.value = j["value"].get<nlohmann::json>();
    }
    if (j.contains("unit")) {
        if (j["unit"].is_null()) {
            v.unit = NullableField<std::string>::make_null();
        } else {
            v.unit = NullableField<std::string>::value(j["unit"].get<std::string>());
        }
    }
    if (j.contains("validators")) {
        if (j["validators"].is_null()) {
            v.validators = NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>>::make_null();
        } else {
            v.validators = NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>>::value(j["validators"].get<std::vector<PhaseGetDataSeriesAggregationsValidators>>());
        }
    }
}

/// Builder for PhaseGetDataSeriesAggregations.
class PhaseGetDataSeriesAggregationsBuilder {
public:
    /// Set the `id` field.
    /// Unique identifier for the aggregation.
    PhaseGetDataSeriesAggregationsBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `type` field.
    /// Aggregation type (e.g., MIN, MAX, MEAN, RANGE, STD_DEV).
    PhaseGetDataSeriesAggregationsBuilder& type(std::string value) {
        type_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    /// Aggregation validation result: PASS, FAIL, UNSET, or null if no validators.
    PhaseGetDataSeriesAggregationsBuilder& outcome(Outcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `value` field.
    /// Computed aggregation value. Type depends on aggregation type.
    PhaseGetDataSeriesAggregationsBuilder& value(nlohmann::json value) {
        value_ = std::move(value);
        return *this;
    }

    /// Set the `unit` field.
    /// Unit of measurement for the aggregated value.
    PhaseGetDataSeriesAggregationsBuilder& unit(std::string value) {
        unit_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `unit` to null.
    PhaseGetDataSeriesAggregationsBuilder& unit_null() {
        unit_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `validators` field.
    /// Validators applied to the aggregated value.
    PhaseGetDataSeriesAggregationsBuilder& validators(std::vector<PhaseGetDataSeriesAggregationsValidators> value) {
        validators_ = NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `validators` to null.
    PhaseGetDataSeriesAggregationsBuilder& validators_null() {
        validators_ = NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>>::make_null();
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    PhaseGetDataSeriesAggregations build() const& {
        PhaseGetDataSeriesAggregations result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!type_.has_value()) {
            throw std::runtime_error("missing required field: type");
        }
        result.type = type_.value();
        result.outcome = outcome_;
        result.value = value_;
        result.unit = unit_;
        result.validators = validators_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    PhaseGetDataSeriesAggregations build() && {
        PhaseGetDataSeriesAggregations result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!type_.has_value()) {
            throw std::runtime_error("missing required field: type");
        }
        result.type = std::move(type_.value());
        result.outcome = std::move(outcome_);
        result.value = std::move(value_);
        result.unit = std::move(unit_);
        result.validators = std::move(validators_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> type_;
    std::optional<Outcome> outcome_;
    std::optional<nlohmann::json> value_;
    NullableField<std::string> unit_;
    NullableField<std::vector<PhaseGetDataSeriesAggregationsValidators>> validators_;
};

} // namespace tofupilot
