// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Overall result of the phase execution. Use PASS when phase succeeds, FAIL when phase fails but execution completed successfully, ERROR when phase execution fails, SKIP when phase was not executed.
enum class PhaseGetOutcome {
    Pass,
    Fail,
    Skip,
    Error,
};

NLOHMANN_JSON_SERIALIZE_ENUM(PhaseGetOutcome, {
    { PhaseGetOutcome::Pass, "PASS" },
    { PhaseGetOutcome::Fail, "FAIL" },
    { PhaseGetOutcome::Skip, "SKIP" },
    { PhaseGetOutcome::Error, "ERROR" },
})

inline std::string to_string(PhaseGetOutcome e) {
    switch (e) {
        case PhaseGetOutcome::Pass: return "PASS";
        case PhaseGetOutcome::Fail: return "FAIL";
        case PhaseGetOutcome::Skip: return "SKIP";
        case PhaseGetOutcome::Error: return "ERROR";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
