// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/log_get_outcome.hpp"
#include "tofupilot/models/phase_get_outcome.hpp"
#include "tofupilot/models/sample.hpp"

namespace tofupilot {

struct PhaseListData {
    /// Unique identifier for the phase.
    std::string id;
    /// Name of the phase.
    std::string name;
    /// Outcome of the phase.
    PhaseGetOutcome outcome;
    /// ISO 8601 timestamp when the phase started.
    std::optional<std::string> started_at;
    /// ISO 8601 timestamp when the phase ended.
    std::optional<std::string> ended_at;
    /// Phase duration in milliseconds. Null when start or end is missing.
    std::optional<int64_t> duration_ms;
    /// Retry attempt number of the phase (0 for the first attempt).
    int64_t retry_count;
    /// True when this is the final attempt of the phase.
    bool is_final_attempt;
    /// ID of the run this phase belongs to.
    std::string run_id;
    /// Outcome of the run this phase belongs to.
    LogGetOutcome run_outcome;
    /// Serial number of the unit tested.
    std::optional<std::string> serial_number;
    /// Sample class of the unit (golden or failing). Null for regular units.
    std::optional<Sample> sample;
};

inline void to_json(nlohmann::json& j, const PhaseListData& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["outcome"] = v.outcome;
    if (v.started_at.has_value()) {
        j["started_at"] = v.started_at.value();
    }
    if (v.ended_at.has_value()) {
        j["ended_at"] = v.ended_at.value();
    }
    if (v.duration_ms.has_value()) {
        j["duration_ms"] = v.duration_ms.value();
    }
    j["retry_count"] = v.retry_count;
    j["is_final_attempt"] = v.is_final_attempt;
    j["run_id"] = v.run_id;
    j["run_outcome"] = v.run_outcome;
    if (v.serial_number.has_value()) {
        j["serial_number"] = v.serial_number.value();
    }
    if (v.sample.has_value()) {
        j["sample"] = v.sample.value();
    }
}

inline void from_json(const nlohmann::json& j, PhaseListData& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<PhaseGetOutcome>();
    if (j.contains("started_at") && !j["started_at"].is_null()) {
        v.started_at = j["started_at"].get<std::string>();
    }
    if (j.contains("ended_at") && !j["ended_at"].is_null()) {
        v.ended_at = j["ended_at"].get<std::string>();
    }
    if (j.contains("duration_ms") && !j["duration_ms"].is_null()) {
        v.duration_ms = j["duration_ms"].get<int64_t>();
    }
    if (!j.contains("retry_count")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: retry_count", &j);
    }
    v.retry_count = j["retry_count"].get<int64_t>();
    if (!j.contains("is_final_attempt")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: is_final_attempt", &j);
    }
    v.is_final_attempt = j["is_final_attempt"].get<bool>();
    if (!j.contains("run_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: run_id", &j);
    }
    v.run_id = j["run_id"].get<std::string>();
    if (!j.contains("run_outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: run_outcome", &j);
    }
    v.run_outcome = j["run_outcome"].get<LogGetOutcome>();
    if (j.contains("serial_number") && !j["serial_number"].is_null()) {
        v.serial_number = j["serial_number"].get<std::string>();
    }
    if (j.contains("sample") && !j["sample"].is_null()) {
        v.sample = j["sample"].get<Sample>();
    }
}

/// Builder for PhaseListData.
class PhaseListDataBuilder {
public:
    /// Set the `id` field.
    /// Unique identifier for the phase.
    PhaseListDataBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    /// Name of the phase.
    PhaseListDataBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    /// Outcome of the phase.
    PhaseListDataBuilder& outcome(PhaseGetOutcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the phase started.
    PhaseListDataBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `ended_at` field.
    /// ISO 8601 timestamp when the phase ended.
    PhaseListDataBuilder& ended_at(std::string value) {
        ended_at_ = std::move(value);
        return *this;
    }

    /// Set the `duration_ms` field.
    /// Phase duration in milliseconds. Null when start or end is missing.
    PhaseListDataBuilder& duration_ms(int64_t value) {
        duration_ms_ = std::move(value);
        return *this;
    }

    /// Set the `retry_count` field.
    /// Retry attempt number of the phase (0 for the first attempt).
    PhaseListDataBuilder& retry_count(int64_t value) {
        retry_count_ = std::move(value);
        return *this;
    }

    /// Set the `is_final_attempt` field.
    /// True when this is the final attempt of the phase.
    PhaseListDataBuilder& is_final_attempt(bool value) {
        is_final_attempt_ = std::move(value);
        return *this;
    }

    /// Set the `run_id` field.
    /// ID of the run this phase belongs to.
    PhaseListDataBuilder& run_id(std::string value) {
        run_id_ = std::move(value);
        return *this;
    }

    /// Set the `run_outcome` field.
    /// Outcome of the run this phase belongs to.
    PhaseListDataBuilder& run_outcome(LogGetOutcome value) {
        run_outcome_ = std::move(value);
        return *this;
    }

    /// Set the `serial_number` field.
    /// Serial number of the unit tested.
    PhaseListDataBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `sample` field.
    /// Sample class of the unit (golden or failing). Null for regular units.
    PhaseListDataBuilder& sample(Sample value) {
        sample_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    PhaseListData build() const& {
        PhaseListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        result.started_at = started_at_;
        result.ended_at = ended_at_;
        result.duration_ms = duration_ms_;
        if (!retry_count_.has_value()) {
            throw std::runtime_error("missing required field: retry_count");
        }
        result.retry_count = retry_count_.value();
        if (!is_final_attempt_.has_value()) {
            throw std::runtime_error("missing required field: is_final_attempt");
        }
        result.is_final_attempt = is_final_attempt_.value();
        if (!run_id_.has_value()) {
            throw std::runtime_error("missing required field: run_id");
        }
        result.run_id = run_id_.value();
        if (!run_outcome_.has_value()) {
            throw std::runtime_error("missing required field: run_outcome");
        }
        result.run_outcome = run_outcome_.value();
        result.serial_number = serial_number_;
        result.sample = sample_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    PhaseListData build() && {
        PhaseListData result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        result.started_at = std::move(started_at_);
        result.ended_at = std::move(ended_at_);
        result.duration_ms = std::move(duration_ms_);
        if (!retry_count_.has_value()) {
            throw std::runtime_error("missing required field: retry_count");
        }
        result.retry_count = std::move(retry_count_.value());
        if (!is_final_attempt_.has_value()) {
            throw std::runtime_error("missing required field: is_final_attempt");
        }
        result.is_final_attempt = std::move(is_final_attempt_.value());
        if (!run_id_.has_value()) {
            throw std::runtime_error("missing required field: run_id");
        }
        result.run_id = std::move(run_id_.value());
        if (!run_outcome_.has_value()) {
            throw std::runtime_error("missing required field: run_outcome");
        }
        result.run_outcome = std::move(run_outcome_.value());
        result.serial_number = std::move(serial_number_);
        result.sample = std::move(sample_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> name_;
    std::optional<PhaseGetOutcome> outcome_;
    std::optional<std::string> started_at_;
    std::optional<std::string> ended_at_;
    std::optional<int64_t> duration_ms_;
    std::optional<int64_t> retry_count_;
    std::optional<bool> is_final_attempt_;
    std::optional<std::string> run_id_;
    std::optional<LogGetOutcome> run_outcome_;
    std::optional<std::string> serial_number_;
    std::optional<Sample> sample_;
};

} // namespace tofupilot
