// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Overall result of the phase execution. Use PASS when phase succeeds, FAIL when phase fails but execution completed successfully, ERROR when phase execution fails, SKIP when phase was not executed.
enum class PhasesOutcome {
    Pass,
    Fail,
    Skip,
    Error,
};

NLOHMANN_JSON_SERIALIZE_ENUM(PhasesOutcome, {
    { PhasesOutcome::Pass, "PASS" },
    { PhasesOutcome::Fail, "FAIL" },
    { PhasesOutcome::Skip, "SKIP" },
    { PhasesOutcome::Error, "ERROR" },
})

inline std::string to_string(PhasesOutcome e) {
    switch (e) {
        case PhasesOutcome::Pass: return "PASS";
        case PhasesOutcome::Fail: return "FAIL";
        case PhasesOutcome::Skip: return "SKIP";
        case PhasesOutcome::Error: return "ERROR";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
