// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/environment.hpp"
#include "tofupilot/models/list_sort_order.hpp"
#include "tofupilot/models/log_get_outcome.hpp"
#include "tofupilot/models/phase_get_outcome.hpp"
#include "tofupilot/models/phase_list_query_param_sample.hpp"
#include "tofupilot/models/phase_list_sort_by.hpp"

namespace tofupilot {

struct PhaseListRequest {
    /// Procedure to list phases for. Required: phases are scoped to a single procedure.
    std::string procedure_id;
    std::optional<std::vector<std::string>> names;
    std::optional<std::vector<PhaseGetOutcome>> outcomes;
    std::optional<std::string> started_after;
    std::optional<std::string> started_before;
    std::optional<bool> exclude_retries;
    std::optional<std::vector<LogGetOutcome>> run_outcomes;
    std::optional<std::vector<std::string>> ids;
    std::optional<std::string> duration_min;
    std::optional<std::string> duration_max;
    std::optional<std::vector<std::string>> deployment_ids;
    std::optional<std::vector<std::string>> procedure_versions;
    std::optional<std::vector<Environment>> environments;
    std::optional<std::vector<std::string>> operated_by_ids;
    std::optional<std::vector<std::string>> created_by_station_ids;
    std::optional<std::vector<std::string>> created_by_user_ids;
    std::optional<std::vector<std::string>> serial_numbers;
    std::optional<std::vector<std::string>> part_numbers;
    std::optional<std::vector<std::string>> revision_numbers;
    std::optional<std::vector<std::string>> batch_numbers;
    std::optional<std::vector<PhaseListQueryParamSample>> samples;
    /// Field to sort results by.
    std::optional<PhaseListSortBy> sort_by;
    /// Sort order direction.
    std::optional<ListSortOrder> sort_order;
    /// Maximum number of phases to return.
    std::optional<int64_t> limit;
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    std::optional<int64_t> cursor;
};

inline void to_json(nlohmann::json& j, const PhaseListRequest& v) {
    j = nlohmann::json::object();
    j["procedure_id"] = v.procedure_id;
    if (v.names.has_value()) {
        j["names"] = v.names.value();
    }
    if (v.outcomes.has_value()) {
        j["outcomes"] = v.outcomes.value();
    }
    if (v.started_after.has_value()) {
        j["started_after"] = v.started_after.value();
    }
    if (v.started_before.has_value()) {
        j["started_before"] = v.started_before.value();
    }
    if (v.exclude_retries.has_value()) {
        j["exclude_retries"] = v.exclude_retries.value();
    }
    if (v.run_outcomes.has_value()) {
        j["run_outcomes"] = v.run_outcomes.value();
    }
    if (v.ids.has_value()) {
        j["ids"] = v.ids.value();
    }
    if (v.duration_min.has_value()) {
        j["duration_min"] = v.duration_min.value();
    }
    if (v.duration_max.has_value()) {
        j["duration_max"] = v.duration_max.value();
    }
    if (v.deployment_ids.has_value()) {
        j["deployment_ids"] = v.deployment_ids.value();
    }
    if (v.procedure_versions.has_value()) {
        j["procedure_versions"] = v.procedure_versions.value();
    }
    if (v.environments.has_value()) {
        j["environments"] = v.environments.value();
    }
    if (v.operated_by_ids.has_value()) {
        j["operated_by_ids"] = v.operated_by_ids.value();
    }
    if (v.created_by_station_ids.has_value()) {
        j["created_by_station_ids"] = v.created_by_station_ids.value();
    }
    if (v.created_by_user_ids.has_value()) {
        j["created_by_user_ids"] = v.created_by_user_ids.value();
    }
    if (v.serial_numbers.has_value()) {
        j["serial_numbers"] = v.serial_numbers.value();
    }
    if (v.part_numbers.has_value()) {
        j["part_numbers"] = v.part_numbers.value();
    }
    if (v.revision_numbers.has_value()) {
        j["revision_numbers"] = v.revision_numbers.value();
    }
    if (v.batch_numbers.has_value()) {
        j["batch_numbers"] = v.batch_numbers.value();
    }
    if (v.samples.has_value()) {
        j["samples"] = v.samples.value();
    }
    if (v.sort_by.has_value()) {
        j["sort_by"] = v.sort_by.value();
    }
    if (v.sort_order.has_value()) {
        j["sort_order"] = v.sort_order.value();
    }
    if (v.limit.has_value()) {
        j["limit"] = v.limit.value();
    }
    if (v.cursor.has_value()) {
        j["cursor"] = v.cursor.value();
    }
}

inline void from_json(const nlohmann::json& j, PhaseListRequest& v) {
    if (!j.contains("procedure_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure_id", &j);
    }
    v.procedure_id = j["procedure_id"].get<std::string>();
    if (j.contains("names") && !j["names"].is_null()) {
        v.names = j["names"].get<std::vector<std::string>>();
    }
    if (j.contains("outcomes") && !j["outcomes"].is_null()) {
        v.outcomes = j["outcomes"].get<std::vector<PhaseGetOutcome>>();
    }
    if (j.contains("started_after") && !j["started_after"].is_null()) {
        v.started_after = j["started_after"].get<std::string>();
    }
    if (j.contains("started_before") && !j["started_before"].is_null()) {
        v.started_before = j["started_before"].get<std::string>();
    }
    if (j.contains("exclude_retries") && !j["exclude_retries"].is_null()) {
        v.exclude_retries = j["exclude_retries"].get<bool>();
    }
    if (j.contains("run_outcomes") && !j["run_outcomes"].is_null()) {
        v.run_outcomes = j["run_outcomes"].get<std::vector<LogGetOutcome>>();
    }
    if (j.contains("ids") && !j["ids"].is_null()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
    if (j.contains("duration_min") && !j["duration_min"].is_null()) {
        v.duration_min = j["duration_min"].get<std::string>();
    }
    if (j.contains("duration_max") && !j["duration_max"].is_null()) {
        v.duration_max = j["duration_max"].get<std::string>();
    }
    if (j.contains("deployment_ids") && !j["deployment_ids"].is_null()) {
        v.deployment_ids = j["deployment_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("procedure_versions") && !j["procedure_versions"].is_null()) {
        v.procedure_versions = j["procedure_versions"].get<std::vector<std::string>>();
    }
    if (j.contains("environments") && !j["environments"].is_null()) {
        v.environments = j["environments"].get<std::vector<Environment>>();
    }
    if (j.contains("operated_by_ids") && !j["operated_by_ids"].is_null()) {
        v.operated_by_ids = j["operated_by_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("created_by_station_ids") && !j["created_by_station_ids"].is_null()) {
        v.created_by_station_ids = j["created_by_station_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("created_by_user_ids") && !j["created_by_user_ids"].is_null()) {
        v.created_by_user_ids = j["created_by_user_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("serial_numbers") && !j["serial_numbers"].is_null()) {
        v.serial_numbers = j["serial_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("part_numbers") && !j["part_numbers"].is_null()) {
        v.part_numbers = j["part_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("revision_numbers") && !j["revision_numbers"].is_null()) {
        v.revision_numbers = j["revision_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("batch_numbers") && !j["batch_numbers"].is_null()) {
        v.batch_numbers = j["batch_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("samples") && !j["samples"].is_null()) {
        v.samples = j["samples"].get<std::vector<PhaseListQueryParamSample>>();
    }
    if (j.contains("sort_by") && !j["sort_by"].is_null()) {
        v.sort_by = j["sort_by"].get<PhaseListSortBy>();
    }
    if (j.contains("sort_order") && !j["sort_order"].is_null()) {
        v.sort_order = j["sort_order"].get<ListSortOrder>();
    }
    if (j.contains("limit") && !j["limit"].is_null()) {
        v.limit = j["limit"].get<int64_t>();
    }
    if (j.contains("cursor") && !j["cursor"].is_null()) {
        v.cursor = j["cursor"].get<int64_t>();
    }
}

/// Builder for PhaseListRequest.
class PhaseListRequestBuilder {
public:
    /// Set the `procedure_id` field.
    /// Procedure to list phases for. Required: phases are scoped to a single procedure.
    PhaseListRequestBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }

    /// Set the `names` field.
    PhaseListRequestBuilder& names(std::vector<std::string> value) {
        names_ = std::move(value);
        return *this;
    }

    /// Set the `outcomes` field.
    PhaseListRequestBuilder& outcomes(std::vector<PhaseGetOutcome> value) {
        outcomes_ = std::move(value);
        return *this;
    }

    /// Set the `started_after` field.
    PhaseListRequestBuilder& started_after(std::string value) {
        started_after_ = std::move(value);
        return *this;
    }

    /// Set the `started_before` field.
    PhaseListRequestBuilder& started_before(std::string value) {
        started_before_ = std::move(value);
        return *this;
    }

    /// Set the `exclude_retries` field.
    PhaseListRequestBuilder& exclude_retries(bool value) {
        exclude_retries_ = std::move(value);
        return *this;
    }

    /// Set the `run_outcomes` field.
    PhaseListRequestBuilder& run_outcomes(std::vector<LogGetOutcome> value) {
        run_outcomes_ = std::move(value);
        return *this;
    }

    /// Set the `ids` field.
    PhaseListRequestBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    /// Set the `duration_min` field.
    PhaseListRequestBuilder& duration_min(std::string value) {
        duration_min_ = std::move(value);
        return *this;
    }

    /// Set the `duration_max` field.
    PhaseListRequestBuilder& duration_max(std::string value) {
        duration_max_ = std::move(value);
        return *this;
    }

    /// Set the `deployment_ids` field.
    PhaseListRequestBuilder& deployment_ids(std::vector<std::string> value) {
        deployment_ids_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_versions` field.
    PhaseListRequestBuilder& procedure_versions(std::vector<std::string> value) {
        procedure_versions_ = std::move(value);
        return *this;
    }

    /// Set the `environments` field.
    PhaseListRequestBuilder& environments(std::vector<Environment> value) {
        environments_ = std::move(value);
        return *this;
    }

    /// Set the `operated_by_ids` field.
    PhaseListRequestBuilder& operated_by_ids(std::vector<std::string> value) {
        operated_by_ids_ = std::move(value);
        return *this;
    }

    /// Set the `created_by_station_ids` field.
    PhaseListRequestBuilder& created_by_station_ids(std::vector<std::string> value) {
        created_by_station_ids_ = std::move(value);
        return *this;
    }

    /// Set the `created_by_user_ids` field.
    PhaseListRequestBuilder& created_by_user_ids(std::vector<std::string> value) {
        created_by_user_ids_ = std::move(value);
        return *this;
    }

    /// Set the `serial_numbers` field.
    PhaseListRequestBuilder& serial_numbers(std::vector<std::string> value) {
        serial_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `part_numbers` field.
    PhaseListRequestBuilder& part_numbers(std::vector<std::string> value) {
        part_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `revision_numbers` field.
    PhaseListRequestBuilder& revision_numbers(std::vector<std::string> value) {
        revision_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `batch_numbers` field.
    PhaseListRequestBuilder& batch_numbers(std::vector<std::string> value) {
        batch_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `samples` field.
    PhaseListRequestBuilder& samples(std::vector<PhaseListQueryParamSample> value) {
        samples_ = std::move(value);
        return *this;
    }

    /// Set the `sort_by` field.
    /// Field to sort results by.
    PhaseListRequestBuilder& sort_by(PhaseListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }

    /// Set the `sort_order` field.
    /// Sort order direction.
    PhaseListRequestBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }

    /// Set the `limit` field.
    /// Maximum number of phases to return.
    PhaseListRequestBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }

    /// Set the `cursor` field.
    /// Cursor for pagination. Use next_cursor from the previous response to fetch the next page.
    PhaseListRequestBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    PhaseListRequest build() const& {
        PhaseListRequest result;
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = procedure_id_.value();
        result.names = names_;
        result.outcomes = outcomes_;
        result.started_after = started_after_;
        result.started_before = started_before_;
        result.exclude_retries = exclude_retries_;
        result.run_outcomes = run_outcomes_;
        result.ids = ids_;
        result.duration_min = duration_min_;
        result.duration_max = duration_max_;
        result.deployment_ids = deployment_ids_;
        result.procedure_versions = procedure_versions_;
        result.environments = environments_;
        result.operated_by_ids = operated_by_ids_;
        result.created_by_station_ids = created_by_station_ids_;
        result.created_by_user_ids = created_by_user_ids_;
        result.serial_numbers = serial_numbers_;
        result.part_numbers = part_numbers_;
        result.revision_numbers = revision_numbers_;
        result.batch_numbers = batch_numbers_;
        result.samples = samples_;
        result.sort_by = sort_by_;
        result.sort_order = sort_order_;
        result.limit = limit_;
        result.cursor = cursor_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    PhaseListRequest build() && {
        PhaseListRequest result;
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = std::move(procedure_id_.value());
        result.names = std::move(names_);
        result.outcomes = std::move(outcomes_);
        result.started_after = std::move(started_after_);
        result.started_before = std::move(started_before_);
        result.exclude_retries = std::move(exclude_retries_);
        result.run_outcomes = std::move(run_outcomes_);
        result.ids = std::move(ids_);
        result.duration_min = std::move(duration_min_);
        result.duration_max = std::move(duration_max_);
        result.deployment_ids = std::move(deployment_ids_);
        result.procedure_versions = std::move(procedure_versions_);
        result.environments = std::move(environments_);
        result.operated_by_ids = std::move(operated_by_ids_);
        result.created_by_station_ids = std::move(created_by_station_ids_);
        result.created_by_user_ids = std::move(created_by_user_ids_);
        result.serial_numbers = std::move(serial_numbers_);
        result.part_numbers = std::move(part_numbers_);
        result.revision_numbers = std::move(revision_numbers_);
        result.batch_numbers = std::move(batch_numbers_);
        result.samples = std::move(samples_);
        result.sort_by = std::move(sort_by_);
        result.sort_order = std::move(sort_order_);
        result.limit = std::move(limit_);
        result.cursor = std::move(cursor_);
        return result;
    }

private:
    std::optional<std::string> procedure_id_;
    std::optional<std::vector<std::string>> names_;
    std::optional<std::vector<PhaseGetOutcome>> outcomes_;
    std::optional<std::string> started_after_;
    std::optional<std::string> started_before_;
    std::optional<bool> exclude_retries_;
    std::optional<std::vector<LogGetOutcome>> run_outcomes_;
    std::optional<std::vector<std::string>> ids_;
    std::optional<std::string> duration_min_;
    std::optional<std::string> duration_max_;
    std::optional<std::vector<std::string>> deployment_ids_;
    std::optional<std::vector<std::string>> procedure_versions_;
    std::optional<std::vector<Environment>> environments_;
    std::optional<std::vector<std::string>> operated_by_ids_;
    std::optional<std::vector<std::string>> created_by_station_ids_;
    std::optional<std::vector<std::string>> created_by_user_ids_;
    std::optional<std::vector<std::string>> serial_numbers_;
    std::optional<std::vector<std::string>> part_numbers_;
    std::optional<std::vector<std::string>> revision_numbers_;
    std::optional<std::vector<std::string>> batch_numbers_;
    std::optional<std::vector<PhaseListQueryParamSample>> samples_;
    std::optional<PhaseListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
};

} // namespace tofupilot
