// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct ProcedureDeleteVersionRequest {
    /// ID of the procedure that owns this version
    std::string procedure_id;
    /// Version tag to delete
    std::string tag;
};

inline void to_json(nlohmann::json& j, const ProcedureDeleteVersionRequest& v) {
    j = nlohmann::json::object();
    j["procedure_id"] = v.procedure_id;
    j["tag"] = v.tag;
}

inline void from_json(const nlohmann::json& j, ProcedureDeleteVersionRequest& v) {
    if (!j.contains("procedure_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure_id", &j);
    }
    v.procedure_id = j["procedure_id"].get<std::string>();
    if (!j.contains("tag")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: tag", &j);
    }
    v.tag = j["tag"].get<std::string>();
}

} // namespace tofupilot
