// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/provider.hpp"

namespace tofupilot {

struct ProcedureListLinkedRepository {
    /// Unique identifier for the linked repository.
    std::string id;
    /// Name of the repository.
    std::string name;
    /// Full name of the repository (owner/repo).
    std::string full_name;
    Provider provider;
};

inline void to_json(nlohmann::json& j, const ProcedureListLinkedRepository& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["fullName"] = v.full_name;
    j["provider"] = v.provider;
}

inline void from_json(const nlohmann::json& j, ProcedureListLinkedRepository& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("fullName")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: fullName", &j);
    }
    v.full_name = j["fullName"].get<std::string>();
    if (!j.contains("provider")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: provider", &j);
    }
    v.provider = j["provider"].get<Provider>();
}

} // namespace tofupilot
