// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct ProcedureListMeta {
    /// Whether there are more results available for pagination.
    bool has_more;
    /// Cursor value to fetch the next page of results. Use this value as the cursor parameter in the next request. Null if no more results available.
    std::optional<int64_t> next_cursor;
};

inline void to_json(nlohmann::json& j, const ProcedureListMeta& v) {
    j = nlohmann::json::object();
    j["has_more"] = v.has_more;
    if (v.next_cursor.has_value()) {
        j["next_cursor"] = v.next_cursor.value();
    }
}

inline void from_json(const nlohmann::json& j, ProcedureListMeta& v) {
    if (!j.contains("has_more")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: has_more", &j);
    }
    v.has_more = j["has_more"].get<bool>();
    if (j.contains("next_cursor") && !j["next_cursor"].is_null()) {
        v.next_cursor = j["next_cursor"].get<int64_t>();
    }
}

/// Builder for ProcedureListMeta.
class ProcedureListMetaBuilder {
public:
    /// Set the `has_more` field.
    /// Whether there are more results available for pagination.
    ProcedureListMetaBuilder& has_more(bool value) {
        has_more_ = std::move(value);
        return *this;
    }

    /// Set the `next_cursor` field.
    /// Cursor value to fetch the next page of results. Use this value as the cursor parameter in the next request. Null if no more results available.
    ProcedureListMetaBuilder& next_cursor(int64_t value) {
        next_cursor_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    ProcedureListMeta build() const& {
        ProcedureListMeta result;
        if (!has_more_.has_value()) {
            throw std::runtime_error("missing required field: has_more");
        }
        result.has_more = has_more_.value();
        result.next_cursor = next_cursor_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    ProcedureListMeta build() && {
        ProcedureListMeta result;
        if (!has_more_.has_value()) {
            throw std::runtime_error("missing required field: has_more");
        }
        result.has_more = std::move(has_more_.value());
        result.next_cursor = std::move(next_cursor_);
        return result;
    }

private:
    std::optional<bool> has_more_;
    std::optional<int64_t> next_cursor_;
};

} // namespace tofupilot
