// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/procedure_get_unit.hpp"

namespace tofupilot {

struct ProcedureGetRecentRuns {
    /// Run ID.
    std::string id;
    /// ISO 8601 timestamp when the run started.
    std::string started_at;
    /// Run outcome.
    Outcome outcome;
    /// Unit information.
    std::optional<ProcedureGetUnit> unit;
};

inline void to_json(nlohmann::json& j, const ProcedureGetRecentRuns& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["started_at"] = v.started_at;
    j["outcome"] = v.outcome;
    if (v.unit.has_value()) {
        j["unit"] = v.unit.value();
    }
}

inline void from_json(const nlohmann::json& j, ProcedureGetRecentRuns& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("started_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: started_at", &j);
    }
    v.started_at = j["started_at"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<Outcome>();
    if (j.contains("unit") && !j["unit"].is_null()) {
        v.unit = j["unit"].get<ProcedureGetUnit>();
    }
}

/// Builder for ProcedureGetRecentRuns.
class ProcedureGetRecentRunsBuilder {
public:
    /// Set the `id` field.
    /// Run ID.
    ProcedureGetRecentRunsBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the run started.
    ProcedureGetRecentRunsBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    /// Run outcome.
    ProcedureGetRecentRunsBuilder& outcome(Outcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `unit` field.
    /// Unit information.
    ProcedureGetRecentRunsBuilder& unit(ProcedureGetUnit value) {
        unit_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    ProcedureGetRecentRuns build() const& {
        ProcedureGetRecentRuns result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = started_at_.value();
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        result.unit = unit_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    ProcedureGetRecentRuns build() && {
        ProcedureGetRecentRuns result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = std::move(started_at_.value());
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        result.unit = std::move(unit_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> started_at_;
    std::optional<Outcome> outcome_;
    std::optional<ProcedureGetUnit> unit_;
};

} // namespace tofupilot
