// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct ProcedureGetUnit {
    /// Unit serial number.
    std::string serial_number;
};

inline void to_json(nlohmann::json& j, const ProcedureGetUnit& v) {
    j = nlohmann::json::object();
    j["serial_number"] = v.serial_number;
}

inline void from_json(const nlohmann::json& j, ProcedureGetUnit& v) {
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
}

} // namespace tofupilot
