// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct ProcedureUpdateRequestBody {
    /// New name for the procedure.
    std::string name;
};

inline void to_json(nlohmann::json& j, const ProcedureUpdateRequestBody& v) {
    j = nlohmann::json::object();
    j["name"] = v.name;
}

inline void from_json(const nlohmann::json& j, ProcedureUpdateRequestBody& v) {
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
}

} // namespace tofupilot
