// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/procedure_create_version_request_body.hpp"

namespace tofupilot {

struct ProcedureCreateVersionRequest {
    /// The ID of the procedure this version belongs to
    std::string procedure_id;
    ProcedureCreateVersionRequestBody request_body;
};

inline void to_json(nlohmann::json& j, const ProcedureCreateVersionRequest& v) {
    j = nlohmann::json::object();
    j["procedure_id"] = v.procedure_id;
    j["request_body"] = v.request_body;
}

inline void from_json(const nlohmann::json& j, ProcedureCreateVersionRequest& v) {
    if (!j.contains("procedure_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure_id", &j);
    }
    v.procedure_id = j["procedure_id"].get<std::string>();
    if (!j.contains("request_body")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: request_body", &j);
    }
    v.request_body = j["request_body"].get<ProcedureCreateVersionRequestBody>();
}

} // namespace tofupilot
