// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct RunGetSubUnits {
    /// Unit ID.
    std::string id;
    /// Unit serial number.
    std::string serial_number;
    /// Part number of the sub-unit.
    std::string part_number;
    /// Part name of the sub-unit.
    std::optional<std::string> part_name;
};

inline void to_json(nlohmann::json& j, const RunGetSubUnits& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["serial_number"] = v.serial_number;
    j["part_number"] = v.part_number;
    if (v.part_name.has_value()) {
        j["part_name"] = v.part_name.value();
    }
}

inline void from_json(const nlohmann::json& j, RunGetSubUnits& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
    if (!j.contains("part_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: part_number", &j);
    }
    v.part_number = j["part_number"].get<std::string>();
    if (j.contains("part_name") && !j["part_name"].is_null()) {
        v.part_name = j["part_name"].get<std::string>();
    }
}

/// Builder for RunGetSubUnits.
class RunGetSubUnitsBuilder {
public:
    /// Set the `id` field.
    /// Unit ID.
    RunGetSubUnitsBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `serial_number` field.
    /// Unit serial number.
    RunGetSubUnitsBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `part_number` field.
    /// Part number of the sub-unit.
    RunGetSubUnitsBuilder& part_number(std::string value) {
        part_number_ = std::move(value);
        return *this;
    }

    /// Set the `part_name` field.
    /// Part name of the sub-unit.
    RunGetSubUnitsBuilder& part_name(std::string value) {
        part_name_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunGetSubUnits build() const& {
        RunGetSubUnits result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = serial_number_.value();
        if (!part_number_.has_value()) {
            throw std::runtime_error("missing required field: part_number");
        }
        result.part_number = part_number_.value();
        result.part_name = part_name_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunGetSubUnits build() && {
        RunGetSubUnits result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = std::move(serial_number_.value());
        if (!part_number_.has_value()) {
            throw std::runtime_error("missing required field: part_number");
        }
        result.part_number = std::move(part_number_.value());
        result.part_name = std::move(part_name_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> serial_number_;
    std::optional<std::string> part_number_;
    std::optional<std::string> part_name_;
};

} // namespace tofupilot
