// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Revision information for this unit.
struct RunListRevision {
    /// Revision ID.
    std::string id;
    /// Revision number.
    std::string number;
};

inline void to_json(nlohmann::json& j, const RunListRevision& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["number"] = v.number;
}

inline void from_json(const nlohmann::json& j, RunListRevision& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: number", &j);
    }
    v.number = j["number"].get<std::string>();
}

} // namespace tofupilot
