// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/run_list_version.hpp"

namespace tofupilot {

/// Test procedure associated with this run.
struct RunListProcedure {
    /// Procedure ID.
    std::string id;
    /// Procedure name.
    std::string name;
    /// Version of the procedure used for this run.
    std::optional<RunListVersion> version;
};

inline void to_json(nlohmann::json& j, const RunListProcedure& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    if (v.version.has_value()) {
        j["version"] = v.version.value();
    }
}

inline void from_json(const nlohmann::json& j, RunListProcedure& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (j.contains("version") && !j["version"].is_null()) {
        v.version = j["version"].get<RunListVersion>();
    }
}

/// Builder for RunListProcedure.
class RunListProcedureBuilder {
public:
    /// Set the `id` field.
    /// Procedure ID.
    RunListProcedureBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    /// Procedure name.
    RunListProcedureBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `version` field.
    /// Version of the procedure used for this run.
    RunListProcedureBuilder& version(RunListVersion value) {
        version_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunListProcedure build() const& {
        RunListProcedure result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        result.version = version_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunListProcedure build() && {
        RunListProcedure result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        result.version = std::move(version_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> name_;
    std::optional<RunListVersion> version_;
};

} // namespace tofupilot
