// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/level.hpp"

namespace tofupilot {

struct RunGetLogs {
    std::string id;
    Level level;
    std::string timestamp;
    std::string message;
    std::string source_file;
    int64_t line_number;
};

inline void to_json(nlohmann::json& j, const RunGetLogs& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["level"] = v.level;
    j["timestamp"] = v.timestamp;
    j["message"] = v.message;
    j["source_file"] = v.source_file;
    j["line_number"] = v.line_number;
}

inline void from_json(const nlohmann::json& j, RunGetLogs& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("level")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: level", &j);
    }
    v.level = j["level"].get<Level>();
    if (!j.contains("timestamp")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: timestamp", &j);
    }
    v.timestamp = j["timestamp"].get<std::string>();
    if (!j.contains("message")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: message", &j);
    }
    v.message = j["message"].get<std::string>();
    if (!j.contains("source_file")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: source_file", &j);
    }
    v.source_file = j["source_file"].get<std::string>();
    if (!j.contains("line_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: line_number", &j);
    }
    v.line_number = j["line_number"].get<int64_t>();
}

} // namespace tofupilot
