// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/phases_outcome.hpp"
#include "tofupilot/models/run_create_measurements.hpp"

namespace tofupilot {

struct RunCreatePhases {
    /// Name identifier for the test phase. Each phase should have a descriptive name that identifies the specific stage of testing being performed. Analytics at phase level are computed using this name as unique identifier.
    std::string name;
    /// Overall result of the phase execution. Use PASS when phase succeeds, FAIL when phase fails but execution completed successfully, ERROR when phase execution fails, SKIP when phase was not executed.
    PhasesOutcome outcome;
    /// ISO 8601 timestamp when the phase execution began.
    std::string started_at;
    /// ISO 8601 timestamp when the phase execution completed.
    std::string ended_at;
    NullableField<std::string> docstring;
    NullableField<std::vector<RunCreateMeasurements>> measurements;
    /// Zero-based retry attempt index for this phase. 0 = first attempt, 1 = first retry, etc. When a phase is retried, all attempts are stored with the same name and increasing retry_count.
    std::optional<int64_t> retry_count;
};

inline void to_json(nlohmann::json& j, const RunCreatePhases& v) {
    j = nlohmann::json::object();
    j["name"] = v.name;
    j["outcome"] = v.outcome;
    j["started_at"] = v.started_at;
    j["ended_at"] = v.ended_at;
    if (!v.docstring.is_absent()) {
        if (v.docstring.is_null()) {
            j["docstring"] = nullptr;
        } else {
            j["docstring"] = v.docstring.get();
        }
    }
    if (!v.measurements.is_absent()) {
        if (v.measurements.is_null()) {
            j["measurements"] = nullptr;
        } else {
            j["measurements"] = v.measurements.get();
        }
    }
    if (v.retry_count.has_value()) {
        j["retry_count"] = v.retry_count.value();
    }
}

inline void from_json(const nlohmann::json& j, RunCreatePhases& v) {
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<PhasesOutcome>();
    if (!j.contains("started_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: started_at", &j);
    }
    v.started_at = j["started_at"].get<std::string>();
    if (!j.contains("ended_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: ended_at", &j);
    }
    v.ended_at = j["ended_at"].get<std::string>();
    if (j.contains("docstring")) {
        if (j["docstring"].is_null()) {
            v.docstring = NullableField<std::string>::make_null();
        } else {
            v.docstring = NullableField<std::string>::value(j["docstring"].get<std::string>());
        }
    }
    if (j.contains("measurements")) {
        if (j["measurements"].is_null()) {
            v.measurements = NullableField<std::vector<RunCreateMeasurements>>::make_null();
        } else {
            v.measurements = NullableField<std::vector<RunCreateMeasurements>>::value(j["measurements"].get<std::vector<RunCreateMeasurements>>());
        }
    }
    if (j.contains("retry_count") && !j["retry_count"].is_null()) {
        v.retry_count = j["retry_count"].get<int64_t>();
    }
}

/// Builder for RunCreatePhases.
class RunCreatePhasesBuilder {
public:
    /// Set the `name` field.
    /// Name identifier for the test phase. Each phase should have a descriptive name that identifies the specific stage of testing being performed. Analytics at phase level are computed using this name as unique identifier.
    RunCreatePhasesBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    /// Overall result of the phase execution. Use PASS when phase succeeds, FAIL when phase fails but execution completed successfully, ERROR when phase execution fails, SKIP when phase was not executed.
    RunCreatePhasesBuilder& outcome(PhasesOutcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the phase execution began.
    RunCreatePhasesBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `ended_at` field.
    /// ISO 8601 timestamp when the phase execution completed.
    RunCreatePhasesBuilder& ended_at(std::string value) {
        ended_at_ = std::move(value);
        return *this;
    }

    /// Set the `docstring` field.
    RunCreatePhasesBuilder& docstring(std::string value) {
        docstring_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `docstring` to null.
    RunCreatePhasesBuilder& docstring_null() {
        docstring_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `measurements` field.
    RunCreatePhasesBuilder& measurements(std::vector<RunCreateMeasurements> value) {
        measurements_ = NullableField<std::vector<RunCreateMeasurements>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `measurements` to null.
    RunCreatePhasesBuilder& measurements_null() {
        measurements_ = NullableField<std::vector<RunCreateMeasurements>>::make_null();
        return *this;
    }

    /// Set the `retry_count` field.
    /// Zero-based retry attempt index for this phase. 0 = first attempt, 1 = first retry, etc. When a phase is retried, all attempts are stored with the same name and increasing retry_count.
    RunCreatePhasesBuilder& retry_count(int64_t value) {
        retry_count_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunCreatePhases build() const& {
        RunCreatePhases result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = started_at_.value();
        if (!ended_at_.has_value()) {
            throw std::runtime_error("missing required field: ended_at");
        }
        result.ended_at = ended_at_.value();
        result.docstring = docstring_;
        result.measurements = measurements_;
        result.retry_count = retry_count_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunCreatePhases build() && {
        RunCreatePhases result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = std::move(started_at_.value());
        if (!ended_at_.has_value()) {
            throw std::runtime_error("missing required field: ended_at");
        }
        result.ended_at = std::move(ended_at_.value());
        result.docstring = std::move(docstring_);
        result.measurements = std::move(measurements_);
        result.retry_count = std::move(retry_count_);
        return result;
    }

private:
    std::optional<std::string> name_;
    std::optional<PhasesOutcome> outcome_;
    std::optional<std::string> started_at_;
    std::optional<std::string> ended_at_;
    NullableField<std::string> docstring_;
    NullableField<std::vector<RunCreateMeasurements>> measurements_;
    std::optional<int64_t> retry_count_;
};

} // namespace tofupilot
