// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include "tofupilot/models/run_get_value.hpp"

namespace tofupilot {

/// Alias for RunGetValue.
using RunCreateValue = RunGetValue;

} // namespace tofupilot
