// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include "tofupilot/models/run_create_expected_value.hpp"

namespace tofupilot {

/// Alias for RunCreateExpectedValue.
using RunCreateYAxisAggregationsExpectedValue = RunCreateExpectedValue;

} // namespace tofupilot
