// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/run_create_logs.hpp"
#include "tofupilot/models/run_create_phases.hpp"

namespace tofupilot {

struct RunCreateRequest {
    /// Overall test result. Use PASS when test succeeds, FAIL when test fails but script execution completed successfully, ERROR when script execution fails, TIMEOUT when test exceeds time limit, ABORTED for manual script interruption.
    Outcome outcome;
    /// Procedure ID. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    std::string procedure_id;
    NullableField<std::string> procedure_version;
    /// Email address of the operator who executed the test run. The operator must exist as a user in the system. The run will be linked to this user to track who performed the test.
    std::optional<std::string> operated_by;
    /// ISO 8601 timestamp when the test run began execution. This timestamp will be used to track when the test execution started and for historical analysis of test runs. A separate created_at timestamp is stored internally server side to track upload date.
    std::string started_at;
    /// ISO 8601 timestamp when the test run finished execution.
    std::string ended_at;
    /// Unique serial number of the unit under test. Matched case-insensitively. If no unit with this serial number exists, one will be created.
    std::string serial_number;
    /// Component part number for the unit. Matched case-insensitively. This field is required if the part number cannot be extracted from the serial number (as set in the settings). This field takes precedence over extraction from serial number. A component with the provided or extracted part number will be created if one does not exist.
    std::optional<std::string> part_number;
    /// Hardware revision identifier for the unit. Matched case-insensitively. If none exist, a revision with this number will be created. If no revision is specified, the unit will be linked to the default revision of the part number.
    std::optional<std::string> revision_number;
    /// Production batch identifier for grouping units manufactured together. Matched case-insensitively. If none exist, a batch with this batch number will be created. If no batch number is specified, the unit will not be linked to any batch.
    std::optional<std::string> batch_number;
    /// Array of sub-unit serial numbers that are part of this main unit. Matched case-insensitively. Each sub-unit must already exist and will be linked as a sub-component of the main unit under test. If no sub-units are specified, the unit will be created without sub-unit relationships.
    std::optional<std::vector<std::string>> sub_units;
    /// Additional notes or documentation about this test run.
    std::optional<std::string> docstring;
    /// Array of test phases with measurements and results. Each phase represents a distinct stage of the test execution with timing information, outcome status, and optional measurements. If no phases are specified, the run will be created without phase-level organization of test data.
    std::optional<std::vector<RunCreatePhases>> phases;
    /// Array of log messages generated during the test execution. Each log entry captures events, errors, and diagnostic information with severity levels and source code references. If no logs are specified, the run will be created without log entries.
    std::optional<std::vector<RunCreateLogs>> logs;
};

inline void to_json(nlohmann::json& j, const RunCreateRequest& v) {
    j = nlohmann::json::object();
    j["outcome"] = v.outcome;
    j["procedure_id"] = v.procedure_id;
    if (!v.procedure_version.is_absent()) {
        if (v.procedure_version.is_null()) {
            j["procedure_version"] = nullptr;
        } else {
            j["procedure_version"] = v.procedure_version.get();
        }
    }
    if (v.operated_by.has_value()) {
        j["operated_by"] = v.operated_by.value();
    }
    j["started_at"] = v.started_at;
    j["ended_at"] = v.ended_at;
    j["serial_number"] = v.serial_number;
    if (v.part_number.has_value()) {
        j["part_number"] = v.part_number.value();
    }
    if (v.revision_number.has_value()) {
        j["revision_number"] = v.revision_number.value();
    }
    if (v.batch_number.has_value()) {
        j["batch_number"] = v.batch_number.value();
    }
    if (v.sub_units.has_value()) {
        j["sub_units"] = v.sub_units.value();
    }
    if (v.docstring.has_value()) {
        j["docstring"] = v.docstring.value();
    }
    if (v.phases.has_value()) {
        j["phases"] = v.phases.value();
    }
    if (v.logs.has_value()) {
        j["logs"] = v.logs.value();
    }
}

inline void from_json(const nlohmann::json& j, RunCreateRequest& v) {
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<Outcome>();
    if (!j.contains("procedure_id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: procedure_id", &j);
    }
    v.procedure_id = j["procedure_id"].get<std::string>();
    if (j.contains("procedure_version")) {
        if (j["procedure_version"].is_null()) {
            v.procedure_version = NullableField<std::string>::make_null();
        } else {
            v.procedure_version = NullableField<std::string>::value(j["procedure_version"].get<std::string>());
        }
    }
    if (j.contains("operated_by") && !j["operated_by"].is_null()) {
        v.operated_by = j["operated_by"].get<std::string>();
    }
    if (!j.contains("started_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: started_at", &j);
    }
    v.started_at = j["started_at"].get<std::string>();
    if (!j.contains("ended_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: ended_at", &j);
    }
    v.ended_at = j["ended_at"].get<std::string>();
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
    if (j.contains("part_number") && !j["part_number"].is_null()) {
        v.part_number = j["part_number"].get<std::string>();
    }
    if (j.contains("revision_number") && !j["revision_number"].is_null()) {
        v.revision_number = j["revision_number"].get<std::string>();
    }
    if (j.contains("batch_number") && !j["batch_number"].is_null()) {
        v.batch_number = j["batch_number"].get<std::string>();
    }
    if (j.contains("sub_units") && !j["sub_units"].is_null()) {
        v.sub_units = j["sub_units"].get<std::vector<std::string>>();
    }
    if (j.contains("docstring") && !j["docstring"].is_null()) {
        v.docstring = j["docstring"].get<std::string>();
    }
    if (j.contains("phases") && !j["phases"].is_null()) {
        v.phases = j["phases"].get<std::vector<RunCreatePhases>>();
    }
    if (j.contains("logs") && !j["logs"].is_null()) {
        v.logs = j["logs"].get<std::vector<RunCreateLogs>>();
    }
}

/// Builder for RunCreateRequest.
class RunCreateRequestBuilder {
public:
    /// Set the `outcome` field.
    /// Overall test result. Use PASS when test succeeds, FAIL when test fails but script execution completed successfully, ERROR when script execution fails, TIMEOUT when test exceeds time limit, ABORTED for manual script interruption.
    RunCreateRequestBuilder& outcome(Outcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_id` field.
    /// Procedure ID. Create the procedure in the app first, then find the auto-generated ID on the procedure page.
    RunCreateRequestBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_version` field.
    RunCreateRequestBuilder& procedure_version(std::string value) {
        procedure_version_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `procedure_version` to null.
    RunCreateRequestBuilder& procedure_version_null() {
        procedure_version_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `operated_by` field.
    /// Email address of the operator who executed the test run. The operator must exist as a user in the system. The run will be linked to this user to track who performed the test.
    RunCreateRequestBuilder& operated_by(std::string value) {
        operated_by_ = std::move(value);
        return *this;
    }

    /// Set the `started_at` field.
    /// ISO 8601 timestamp when the test run began execution. This timestamp will be used to track when the test execution started and for historical analysis of test runs. A separate created_at timestamp is stored internally server side to track upload date.
    RunCreateRequestBuilder& started_at(std::string value) {
        started_at_ = std::move(value);
        return *this;
    }

    /// Set the `ended_at` field.
    /// ISO 8601 timestamp when the test run finished execution.
    RunCreateRequestBuilder& ended_at(std::string value) {
        ended_at_ = std::move(value);
        return *this;
    }

    /// Set the `serial_number` field.
    /// Unique serial number of the unit under test. Matched case-insensitively. If no unit with this serial number exists, one will be created.
    RunCreateRequestBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `part_number` field.
    /// Component part number for the unit. Matched case-insensitively. This field is required if the part number cannot be extracted from the serial number (as set in the settings). This field takes precedence over extraction from serial number. A component with the provided or extracted part number will be created if one does not exist.
    RunCreateRequestBuilder& part_number(std::string value) {
        part_number_ = std::move(value);
        return *this;
    }

    /// Set the `revision_number` field.
    /// Hardware revision identifier for the unit. Matched case-insensitively. If none exist, a revision with this number will be created. If no revision is specified, the unit will be linked to the default revision of the part number.
    RunCreateRequestBuilder& revision_number(std::string value) {
        revision_number_ = std::move(value);
        return *this;
    }

    /// Set the `batch_number` field.
    /// Production batch identifier for grouping units manufactured together. Matched case-insensitively. If none exist, a batch with this batch number will be created. If no batch number is specified, the unit will not be linked to any batch.
    RunCreateRequestBuilder& batch_number(std::string value) {
        batch_number_ = std::move(value);
        return *this;
    }

    /// Set the `sub_units` field.
    /// Array of sub-unit serial numbers that are part of this main unit. Matched case-insensitively. Each sub-unit must already exist and will be linked as a sub-component of the main unit under test. If no sub-units are specified, the unit will be created without sub-unit relationships.
    RunCreateRequestBuilder& sub_units(std::vector<std::string> value) {
        sub_units_ = std::move(value);
        return *this;
    }

    /// Set the `docstring` field.
    /// Additional notes or documentation about this test run.
    RunCreateRequestBuilder& docstring(std::string value) {
        docstring_ = std::move(value);
        return *this;
    }

    /// Set the `phases` field.
    /// Array of test phases with measurements and results. Each phase represents a distinct stage of the test execution with timing information, outcome status, and optional measurements. If no phases are specified, the run will be created without phase-level organization of test data.
    RunCreateRequestBuilder& phases(std::vector<RunCreatePhases> value) {
        phases_ = std::move(value);
        return *this;
    }

    /// Set the `logs` field.
    /// Array of log messages generated during the test execution. Each log entry captures events, errors, and diagnostic information with severity levels and source code references. If no logs are specified, the run will be created without log entries.
    RunCreateRequestBuilder& logs(std::vector<RunCreateLogs> value) {
        logs_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunCreateRequest build() const& {
        RunCreateRequest result;
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = procedure_id_.value();
        result.procedure_version = procedure_version_;
        result.operated_by = operated_by_;
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = started_at_.value();
        if (!ended_at_.has_value()) {
            throw std::runtime_error("missing required field: ended_at");
        }
        result.ended_at = ended_at_.value();
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = serial_number_.value();
        result.part_number = part_number_;
        result.revision_number = revision_number_;
        result.batch_number = batch_number_;
        result.sub_units = sub_units_;
        result.docstring = docstring_;
        result.phases = phases_;
        result.logs = logs_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunCreateRequest build() && {
        RunCreateRequest result;
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        if (!procedure_id_.has_value()) {
            throw std::runtime_error("missing required field: procedure_id");
        }
        result.procedure_id = std::move(procedure_id_.value());
        result.procedure_version = std::move(procedure_version_);
        result.operated_by = std::move(operated_by_);
        if (!started_at_.has_value()) {
            throw std::runtime_error("missing required field: started_at");
        }
        result.started_at = std::move(started_at_.value());
        if (!ended_at_.has_value()) {
            throw std::runtime_error("missing required field: ended_at");
        }
        result.ended_at = std::move(ended_at_.value());
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = std::move(serial_number_.value());
        result.part_number = std::move(part_number_);
        result.revision_number = std::move(revision_number_);
        result.batch_number = std::move(batch_number_);
        result.sub_units = std::move(sub_units_);
        result.docstring = std::move(docstring_);
        result.phases = std::move(phases_);
        result.logs = std::move(logs_);
        return result;
    }

private:
    std::optional<Outcome> outcome_;
    std::optional<std::string> procedure_id_;
    NullableField<std::string> procedure_version_;
    std::optional<std::string> operated_by_;
    std::optional<std::string> started_at_;
    std::optional<std::string> ended_at_;
    std::optional<std::string> serial_number_;
    std::optional<std::string> part_number_;
    std::optional<std::string> revision_number_;
    std::optional<std::string> batch_number_;
    std::optional<std::vector<std::string>> sub_units_;
    std::optional<std::string> docstring_;
    std::optional<std::vector<RunCreatePhases>> phases_;
    std::optional<std::vector<RunCreateLogs>> logs_;
};

} // namespace tofupilot
