// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Overall test result. Use PASS when test succeeds, FAIL when test fails but script execution completed successfully, ERROR when script execution fails, TIMEOUT when test exceeds time limit, ABORTED for manual script interruption.
enum class RunGetOutcome {
    Pass,
    Fail,
    Error,
    Timeout,
    Aborted,
};

NLOHMANN_JSON_SERIALIZE_ENUM(RunGetOutcome, {
    { RunGetOutcome::Pass, "PASS" },
    { RunGetOutcome::Fail, "FAIL" },
    { RunGetOutcome::Error, "ERROR" },
    { RunGetOutcome::Timeout, "TIMEOUT" },
    { RunGetOutcome::Aborted, "ABORTED" },
})

inline std::string to_string(RunGetOutcome e) {
    switch (e) {
        case RunGetOutcome::Pass: return "PASS";
        case RunGetOutcome::Fail: return "FAIL";
        case RunGetOutcome::Error: return "ERROR";
        case RunGetOutcome::Timeout: return "TIMEOUT";
        case RunGetOutcome::Aborted: return "ABORTED";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
