// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/run_create_aggregations.hpp"
#include "tofupilot/models/run_create_validators.hpp"

namespace tofupilot {

/// Data series with numeric data, unit, and optional validators/aggregations.
struct RunCreateXAxis {
    /// Array of numeric data points for this axis.
    std::vector<double> data;
    /// Unit for this axis.
    NullableField<std::string> units;
    /// Description of this data series.
    NullableField<std::string> description;
    /// Validators for this specific axis/series.
    NullableField<std::vector<RunCreateValidators>> validators;
    /// Aggregations computed over this axis data (min, max, avg, etc.).
    NullableField<std::vector<RunCreateAggregations>> aggregations;
};

inline void to_json(nlohmann::json& j, const RunCreateXAxis& v) {
    j = nlohmann::json::object();
    j["data"] = v.data;
    if (!v.units.is_absent()) {
        if (v.units.is_null()) {
            j["units"] = nullptr;
        } else {
            j["units"] = v.units.get();
        }
    }
    if (!v.description.is_absent()) {
        if (v.description.is_null()) {
            j["description"] = nullptr;
        } else {
            j["description"] = v.description.get();
        }
    }
    if (!v.validators.is_absent()) {
        if (v.validators.is_null()) {
            j["validators"] = nullptr;
        } else {
            j["validators"] = v.validators.get();
        }
    }
    if (!v.aggregations.is_absent()) {
        if (v.aggregations.is_null()) {
            j["aggregations"] = nullptr;
        } else {
            j["aggregations"] = v.aggregations.get();
        }
    }
}

inline void from_json(const nlohmann::json& j, RunCreateXAxis& v) {
    if (j.contains("data") && j["data"].is_array()) {
        v.data = j["data"].get<std::vector<double>>();
    }
    if (j.contains("units")) {
        if (j["units"].is_null()) {
            v.units = NullableField<std::string>::make_null();
        } else {
            v.units = NullableField<std::string>::value(j["units"].get<std::string>());
        }
    }
    if (j.contains("description")) {
        if (j["description"].is_null()) {
            v.description = NullableField<std::string>::make_null();
        } else {
            v.description = NullableField<std::string>::value(j["description"].get<std::string>());
        }
    }
    if (j.contains("validators")) {
        if (j["validators"].is_null()) {
            v.validators = NullableField<std::vector<RunCreateValidators>>::make_null();
        } else {
            v.validators = NullableField<std::vector<RunCreateValidators>>::value(j["validators"].get<std::vector<RunCreateValidators>>());
        }
    }
    if (j.contains("aggregations")) {
        if (j["aggregations"].is_null()) {
            v.aggregations = NullableField<std::vector<RunCreateAggregations>>::make_null();
        } else {
            v.aggregations = NullableField<std::vector<RunCreateAggregations>>::value(j["aggregations"].get<std::vector<RunCreateAggregations>>());
        }
    }
}

/// Builder for RunCreateXAxis.
class RunCreateXAxisBuilder {
public:
    /// Set the `data` field.
    /// Array of numeric data points for this axis.
    RunCreateXAxisBuilder& data(std::vector<double> value) {
        data_ = std::move(value);
        return *this;
    }

    /// Set the `units` field.
    /// Unit for this axis.
    RunCreateXAxisBuilder& units(std::string value) {
        units_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `units` to null.
    RunCreateXAxisBuilder& units_null() {
        units_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `description` field.
    /// Description of this data series.
    RunCreateXAxisBuilder& description(std::string value) {
        description_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `description` to null.
    RunCreateXAxisBuilder& description_null() {
        description_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `validators` field.
    /// Validators for this specific axis/series.
    RunCreateXAxisBuilder& validators(std::vector<RunCreateValidators> value) {
        validators_ = NullableField<std::vector<RunCreateValidators>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `validators` to null.
    RunCreateXAxisBuilder& validators_null() {
        validators_ = NullableField<std::vector<RunCreateValidators>>::make_null();
        return *this;
    }

    /// Set the `aggregations` field.
    /// Aggregations computed over this axis data (min, max, avg, etc.).
    RunCreateXAxisBuilder& aggregations(std::vector<RunCreateAggregations> value) {
        aggregations_ = NullableField<std::vector<RunCreateAggregations>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `aggregations` to null.
    RunCreateXAxisBuilder& aggregations_null() {
        aggregations_ = NullableField<std::vector<RunCreateAggregations>>::make_null();
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunCreateXAxis build() const& {
        RunCreateXAxis result;
        if (data_.has_value()) {
            result.data = data_.value();
        }
        result.units = units_;
        result.description = description_;
        result.validators = validators_;
        result.aggregations = aggregations_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunCreateXAxis build() && {
        RunCreateXAxis result;
        if (data_.has_value()) {
            result.data = std::move(data_.value());
        }
        result.units = std::move(units_);
        result.description = std::move(description_);
        result.validators = std::move(validators_);
        result.aggregations = std::move(aggregations_);
        return result;
    }

private:
    std::optional<std::vector<double>> data_;
    NullableField<std::string> units_;
    NullableField<std::string> description_;
    NullableField<std::vector<RunCreateValidators>> validators_;
    NullableField<std::vector<RunCreateAggregations>> aggregations_;
};

} // namespace tofupilot
