// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/validators_outcome.hpp"

namespace tofupilot {

/// Validator result with outcome and comparison details.
struct RunGetValidators {
    /// Validation result: PASS, FAIL, or UNSET.
    ValidatorsOutcome outcome;
    /// Comparison operator used for validation.
    std::optional<std::string> operator_;
    /// Expected value for comparison. Type depends on measurement type.
    std::optional<nlohmann::json> expected_value;
    /// Human-readable expression string for display.
    std::string expression;
    /// Whether this validator is decisive (if it fails, measurement fails). False for marginal/warning validators.
    std::optional<bool> is_decisive;
    /// True if validator only has expression (no structured operator/expected_value).
    bool is_expression_only;
    /// Synthetic expression from operator+expected_value for analytics tooltip. Null if expression-only.
    std::optional<std::string> analytics_expression;
    /// True if user provided a custom expression (shown in italic with analytics tooltip).
    bool has_custom_expression;
};

inline void to_json(nlohmann::json& j, const RunGetValidators& v) {
    j = nlohmann::json::object();
    j["outcome"] = v.outcome;
    if (v.operator_.has_value()) {
        j["operator"] = v.operator_.value();
    }
    if (v.expected_value.has_value()) {
        j["expected_value"] = v.expected_value.value();
    }
    j["expression"] = v.expression;
    if (v.is_decisive.has_value()) {
        j["is_decisive"] = v.is_decisive.value();
    }
    j["is_expression_only"] = v.is_expression_only;
    if (v.analytics_expression.has_value()) {
        j["analytics_expression"] = v.analytics_expression.value();
    }
    j["has_custom_expression"] = v.has_custom_expression;
}

inline void from_json(const nlohmann::json& j, RunGetValidators& v) {
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<ValidatorsOutcome>();
    if (j.contains("operator") && !j["operator"].is_null()) {
        v.operator_ = j["operator"].get<std::string>();
    }
    if (j.contains("expected_value") && !j["expected_value"].is_null()) {
        v.expected_value = j["expected_value"].get<nlohmann::json>();
    }
    if (!j.contains("expression")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: expression", &j);
    }
    v.expression = j["expression"].get<std::string>();
    if (j.contains("is_decisive") && !j["is_decisive"].is_null()) {
        v.is_decisive = j["is_decisive"].get<bool>();
    }
    if (!j.contains("is_expression_only")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: is_expression_only", &j);
    }
    v.is_expression_only = j["is_expression_only"].get<bool>();
    if (j.contains("analytics_expression") && !j["analytics_expression"].is_null()) {
        v.analytics_expression = j["analytics_expression"].get<std::string>();
    }
    if (!j.contains("has_custom_expression")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: has_custom_expression", &j);
    }
    v.has_custom_expression = j["has_custom_expression"].get<bool>();
}

/// Builder for RunGetValidators.
class RunGetValidatorsBuilder {
public:
    /// Set the `outcome` field.
    /// Validation result: PASS, FAIL, or UNSET.
    RunGetValidatorsBuilder& outcome(ValidatorsOutcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `operator` field.
    /// Comparison operator used for validation.
    RunGetValidatorsBuilder& operator_(std::string value) {
        operator__ = std::move(value);
        return *this;
    }

    /// Set the `expected_value` field.
    /// Expected value for comparison. Type depends on measurement type.
    RunGetValidatorsBuilder& expected_value(nlohmann::json value) {
        expected_value_ = std::move(value);
        return *this;
    }

    /// Set the `expression` field.
    /// Human-readable expression string for display.
    RunGetValidatorsBuilder& expression(std::string value) {
        expression_ = std::move(value);
        return *this;
    }

    /// Set the `is_decisive` field.
    /// Whether this validator is decisive (if it fails, measurement fails). False for marginal/warning validators.
    RunGetValidatorsBuilder& is_decisive(bool value) {
        is_decisive_ = std::move(value);
        return *this;
    }

    /// Set the `is_expression_only` field.
    /// True if validator only has expression (no structured operator/expected_value).
    RunGetValidatorsBuilder& is_expression_only(bool value) {
        is_expression_only_ = std::move(value);
        return *this;
    }

    /// Set the `analytics_expression` field.
    /// Synthetic expression from operator+expected_value for analytics tooltip. Null if expression-only.
    RunGetValidatorsBuilder& analytics_expression(std::string value) {
        analytics_expression_ = std::move(value);
        return *this;
    }

    /// Set the `has_custom_expression` field.
    /// True if user provided a custom expression (shown in italic with analytics tooltip).
    RunGetValidatorsBuilder& has_custom_expression(bool value) {
        has_custom_expression_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunGetValidators build() const& {
        RunGetValidators result;
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        result.operator_ = operator__;
        result.expected_value = expected_value_;
        if (!expression_.has_value()) {
            throw std::runtime_error("missing required field: expression");
        }
        result.expression = expression_.value();
        result.is_decisive = is_decisive_;
        if (!is_expression_only_.has_value()) {
            throw std::runtime_error("missing required field: is_expression_only");
        }
        result.is_expression_only = is_expression_only_.value();
        result.analytics_expression = analytics_expression_;
        if (!has_custom_expression_.has_value()) {
            throw std::runtime_error("missing required field: has_custom_expression");
        }
        result.has_custom_expression = has_custom_expression_.value();
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunGetValidators build() && {
        RunGetValidators result;
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        result.operator_ = std::move(operator__);
        result.expected_value = std::move(expected_value_);
        if (!expression_.has_value()) {
            throw std::runtime_error("missing required field: expression");
        }
        result.expression = std::move(expression_.value());
        result.is_decisive = std::move(is_decisive_);
        if (!is_expression_only_.has_value()) {
            throw std::runtime_error("missing required field: is_expression_only");
        }
        result.is_expression_only = std::move(is_expression_only_.value());
        result.analytics_expression = std::move(analytics_expression_);
        if (!has_custom_expression_.has_value()) {
            throw std::runtime_error("missing required field: has_custom_expression");
        }
        result.has_custom_expression = std::move(has_custom_expression_.value());
        return result;
    }

private:
    std::optional<ValidatorsOutcome> outcome_;
    std::optional<std::string> operator__;
    std::optional<nlohmann::json> expected_value_;
    std::optional<std::string> expression_;
    std::optional<bool> is_decisive_;
    std::optional<bool> is_expression_only_;
    std::optional<std::string> analytics_expression_;
    std::optional<bool> has_custom_expression_;
};

} // namespace tofupilot
