// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Computed aggregation value. Type depends on aggregation type.
using RunGetValue = std::variant<
    double,
    std::string,
    bool
>;

inline void to_json(nlohmann::json& j, const RunGetValue& v) {
    std::visit([&j](const auto& val) { j = val; }, v);
}

inline void from_json(const nlohmann::json& j, RunGetValue& v) {
    if (j.is_number()) { v = j.get<double>(); return; }
    if (j.is_string()) { v = j.get<std::string>(); return; }
    if (j.is_boolean()) { v = j.get<bool>(); return; }
    throw nlohmann::json::type_error::create(302, "cannot convert JSON to RunGetValue", &j);
}

} // namespace tofupilot
