// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Operator of this run: a linked organization member (id/email set) or a declared free-text name (id/email null). Only returned if `all` or `operated_by` is included.
struct RunListOperatedBy {
    /// Operator user ID. Null when the operator is a declared name without a TofuPilot account.
    std::optional<std::string> id;
    /// Operator display name: the account name for linked operators, the declared free-text value otherwise.
    std::optional<std::string> name;
    /// Operator email address. Null for declared names (unverified operators have no account email).
    std::optional<std::string> email;
};

inline void to_json(nlohmann::json& j, const RunListOperatedBy& v) {
    j = nlohmann::json::object();
    if (v.id.has_value()) {
        j["id"] = v.id.value();
    }
    if (v.name.has_value()) {
        j["name"] = v.name.value();
    }
    if (v.email.has_value()) {
        j["email"] = v.email.value();
    }
}

inline void from_json(const nlohmann::json& j, RunListOperatedBy& v) {
    if (j.contains("id") && !j["id"].is_null()) {
        v.id = j["id"].get<std::string>();
    }
    if (j.contains("name") && !j["name"].is_null()) {
        v.name = j["name"].get<std::string>();
    }
    if (j.contains("email") && !j["email"].is_null()) {
        v.email = j["email"].get<std::string>();
    }
}

/// Builder for RunListOperatedBy.
class RunListOperatedByBuilder {
public:
    /// Set the `id` field.
    /// Operator user ID. Null when the operator is a declared name without a TofuPilot account.
    RunListOperatedByBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    /// Operator display name: the account name for linked operators, the declared free-text value otherwise.
    RunListOperatedByBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `email` field.
    /// Operator email address. Null for declared names (unverified operators have no account email).
    RunListOperatedByBuilder& email(std::string value) {
        email_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunListOperatedBy build() const& {
        RunListOperatedBy result;
        result.id = id_;
        result.name = name_;
        result.email = email_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunListOperatedBy build() && {
        RunListOperatedBy result;
        result.id = std::move(id_);
        result.name = std::move(name_);
        result.email = std::move(email_);
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> name_;
    std::optional<std::string> email_;
};

} // namespace tofupilot
