// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// [LEGACY for multi-dim] Units of measurement. For structured multi-dimensional, use units within x_axis/y_axis instead.
using RunCreateUnits = std::variant<
    std::string,
    std::vector<std::string>
>;

inline void to_json(nlohmann::json& j, const RunCreateUnits& v) {
    std::visit([&j](const auto& val) { j = val; }, v);
}

inline void from_json(const nlohmann::json& j, RunCreateUnits& v) {
    if (j.is_string()) { v = j.get<std::string>(); return; }
    if (j.is_array()) { v = j.get<std::vector<std::string>>(); return; }
    throw nlohmann::json::type_error::create(302, "cannot convert JSON to RunCreateUnits", &j);
}

} // namespace tofupilot
