// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Run attachment created successfully
struct RunCreateAttachmentResponse {
    /// Unique identifier of the created attachment. Use this to reference the attachment in subsequent API calls.
    std::string id;
    /// Temporary pre-signed URL to upload the file directly to storage. Send a PUT request with the raw file bytes and appropriate Content-Type header. The URL expires after 60 seconds.
    std::string upload_url;
};

inline void to_json(nlohmann::json& j, const RunCreateAttachmentResponse& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["upload_url"] = v.upload_url;
}

inline void from_json(const nlohmann::json& j, RunCreateAttachmentResponse& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("upload_url")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: upload_url", &j);
    }
    v.upload_url = j["upload_url"].get<std::string>();
}

} // namespace tofupilot
