// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"
#include "tofupilot/models/run_create_measurements_aggregations.hpp"
#include "tofupilot/models/run_create_measurements_validators.hpp"
#include "tofupilot/models/run_create_x_axis.hpp"
#include "tofupilot/models/run_create_y_axis.hpp"
#include "tofupilot/models/validators_outcome.hpp"

namespace tofupilot {

struct RunCreateMeasurements {
    /// Name identifier for the measurement. Each measurement should have a descriptive name that identifies the specific data point being captured. Analytics at measurement level are computed using this name as unique identifier.
    std::string name;
    /// Result of the measurement validation. Use PASS when measurement meets all criteria, FAIL when measurement is outside acceptable limits or validation fails, UNSET when no validation was performed.
    ValidatorsOutcome outcome;
    /// X-axis data series for multi-dimensional measurements. Use with y_axis for structured multi-dimensional data with per-axis validators/aggregations.
    NullableField<RunCreateXAxis> x_axis;
    /// Y-axis data series (one or more) for multi-dimensional measurements. Each series can have its own validators and aggregations.
    NullableField<std::vector<RunCreateYAxis>> y_axis;
    NullableField<nlohmann::json> measured_value;
    /// [LEGACY for multi-dim] Units of measurement. For structured multi-dimensional, use units within x_axis/y_axis instead.
    NullableField<nlohmann::json> units;
    /// Use validators with operator ">=" instead. Will be converted to a validator automatically.
    std::optional<double> lower_limit;
    /// Use validators with operator "<=" instead. Will be converted to a validator automatically.
    std::optional<double> upper_limit;
    NullableField<std::vector<RunCreateMeasurementsValidators>> validators;
    NullableField<std::vector<RunCreateMeasurementsAggregations>> aggregations;
    NullableField<std::string> docstring;
};

inline void to_json(nlohmann::json& j, const RunCreateMeasurements& v) {
    j = nlohmann::json::object();
    j["name"] = v.name;
    j["outcome"] = v.outcome;
    if (!v.x_axis.is_absent()) {
        if (v.x_axis.is_null()) {
            j["x_axis"] = nullptr;
        } else {
            j["x_axis"] = v.x_axis.get();
        }
    }
    if (!v.y_axis.is_absent()) {
        if (v.y_axis.is_null()) {
            j["y_axis"] = nullptr;
        } else {
            j["y_axis"] = v.y_axis.get();
        }
    }
    if (!v.measured_value.is_absent()) {
        if (v.measured_value.is_null()) {
            j["measured_value"] = nullptr;
        } else {
            j["measured_value"] = v.measured_value.get();
        }
    }
    if (!v.units.is_absent()) {
        if (v.units.is_null()) {
            j["units"] = nullptr;
        } else {
            j["units"] = v.units.get();
        }
    }
    if (v.lower_limit.has_value()) {
        j["lower_limit"] = v.lower_limit.value();
    }
    if (v.upper_limit.has_value()) {
        j["upper_limit"] = v.upper_limit.value();
    }
    if (!v.validators.is_absent()) {
        if (v.validators.is_null()) {
            j["validators"] = nullptr;
        } else {
            j["validators"] = v.validators.get();
        }
    }
    if (!v.aggregations.is_absent()) {
        if (v.aggregations.is_null()) {
            j["aggregations"] = nullptr;
        } else {
            j["aggregations"] = v.aggregations.get();
        }
    }
    if (!v.docstring.is_absent()) {
        if (v.docstring.is_null()) {
            j["docstring"] = nullptr;
        } else {
            j["docstring"] = v.docstring.get();
        }
    }
}

inline void from_json(const nlohmann::json& j, RunCreateMeasurements& v) {
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("outcome")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: outcome", &j);
    }
    v.outcome = j["outcome"].get<ValidatorsOutcome>();
    if (j.contains("x_axis")) {
        if (j["x_axis"].is_null()) {
            v.x_axis = NullableField<RunCreateXAxis>::make_null();
        } else {
            v.x_axis = NullableField<RunCreateXAxis>::value(j["x_axis"].get<RunCreateXAxis>());
        }
    }
    if (j.contains("y_axis")) {
        if (j["y_axis"].is_null()) {
            v.y_axis = NullableField<std::vector<RunCreateYAxis>>::make_null();
        } else {
            v.y_axis = NullableField<std::vector<RunCreateYAxis>>::value(j["y_axis"].get<std::vector<RunCreateYAxis>>());
        }
    }
    if (j.contains("measured_value")) {
        if (j["measured_value"].is_null()) {
            v.measured_value = NullableField<nlohmann::json>::make_null();
        } else {
            v.measured_value = NullableField<nlohmann::json>::value(j["measured_value"].get<nlohmann::json>());
        }
    }
    if (j.contains("units")) {
        if (j["units"].is_null()) {
            v.units = NullableField<nlohmann::json>::make_null();
        } else {
            v.units = NullableField<nlohmann::json>::value(j["units"].get<nlohmann::json>());
        }
    }
    if (j.contains("lower_limit") && !j["lower_limit"].is_null()) {
        v.lower_limit = j["lower_limit"].get<double>();
    }
    if (j.contains("upper_limit") && !j["upper_limit"].is_null()) {
        v.upper_limit = j["upper_limit"].get<double>();
    }
    if (j.contains("validators")) {
        if (j["validators"].is_null()) {
            v.validators = NullableField<std::vector<RunCreateMeasurementsValidators>>::make_null();
        } else {
            v.validators = NullableField<std::vector<RunCreateMeasurementsValidators>>::value(j["validators"].get<std::vector<RunCreateMeasurementsValidators>>());
        }
    }
    if (j.contains("aggregations")) {
        if (j["aggregations"].is_null()) {
            v.aggregations = NullableField<std::vector<RunCreateMeasurementsAggregations>>::make_null();
        } else {
            v.aggregations = NullableField<std::vector<RunCreateMeasurementsAggregations>>::value(j["aggregations"].get<std::vector<RunCreateMeasurementsAggregations>>());
        }
    }
    if (j.contains("docstring")) {
        if (j["docstring"].is_null()) {
            v.docstring = NullableField<std::string>::make_null();
        } else {
            v.docstring = NullableField<std::string>::value(j["docstring"].get<std::string>());
        }
    }
}

/// Builder for RunCreateMeasurements.
class RunCreateMeasurementsBuilder {
public:
    /// Set the `name` field.
    /// Name identifier for the measurement. Each measurement should have a descriptive name that identifies the specific data point being captured. Analytics at measurement level are computed using this name as unique identifier.
    RunCreateMeasurementsBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `outcome` field.
    /// Result of the measurement validation. Use PASS when measurement meets all criteria, FAIL when measurement is outside acceptable limits or validation fails, UNSET when no validation was performed.
    RunCreateMeasurementsBuilder& outcome(ValidatorsOutcome value) {
        outcome_ = std::move(value);
        return *this;
    }

    /// Set the `x_axis` field.
    /// X-axis data series for multi-dimensional measurements. Use with y_axis for structured multi-dimensional data with per-axis validators/aggregations.
    RunCreateMeasurementsBuilder& x_axis(RunCreateXAxis value) {
        x_axis_ = NullableField<RunCreateXAxis>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `x_axis` to null.
    RunCreateMeasurementsBuilder& x_axis_null() {
        x_axis_ = NullableField<RunCreateXAxis>::make_null();
        return *this;
    }

    /// Set the `y_axis` field.
    /// Y-axis data series (one or more) for multi-dimensional measurements. Each series can have its own validators and aggregations.
    RunCreateMeasurementsBuilder& y_axis(std::vector<RunCreateYAxis> value) {
        y_axis_ = NullableField<std::vector<RunCreateYAxis>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `y_axis` to null.
    RunCreateMeasurementsBuilder& y_axis_null() {
        y_axis_ = NullableField<std::vector<RunCreateYAxis>>::make_null();
        return *this;
    }

    /// Set the `measured_value` field.
    RunCreateMeasurementsBuilder& measured_value(nlohmann::json value) {
        measured_value_ = NullableField<nlohmann::json>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `measured_value` to null.
    RunCreateMeasurementsBuilder& measured_value_null() {
        measured_value_ = NullableField<nlohmann::json>::make_null();
        return *this;
    }

    /// Set the `units` field.
    /// [LEGACY for multi-dim] Units of measurement. For structured multi-dimensional, use units within x_axis/y_axis instead.
    RunCreateMeasurementsBuilder& units(nlohmann::json value) {
        units_ = NullableField<nlohmann::json>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `units` to null.
    RunCreateMeasurementsBuilder& units_null() {
        units_ = NullableField<nlohmann::json>::make_null();
        return *this;
    }

    /// Set the `lower_limit` field.
    /// Use validators with operator ">=" instead. Will be converted to a validator automatically.
    RunCreateMeasurementsBuilder& lower_limit(double value) {
        lower_limit_ = std::move(value);
        return *this;
    }

    /// Set the `upper_limit` field.
    /// Use validators with operator "<=" instead. Will be converted to a validator automatically.
    RunCreateMeasurementsBuilder& upper_limit(double value) {
        upper_limit_ = std::move(value);
        return *this;
    }

    /// Set the `validators` field.
    RunCreateMeasurementsBuilder& validators(std::vector<RunCreateMeasurementsValidators> value) {
        validators_ = NullableField<std::vector<RunCreateMeasurementsValidators>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `validators` to null.
    RunCreateMeasurementsBuilder& validators_null() {
        validators_ = NullableField<std::vector<RunCreateMeasurementsValidators>>::make_null();
        return *this;
    }

    /// Set the `aggregations` field.
    RunCreateMeasurementsBuilder& aggregations(std::vector<RunCreateMeasurementsAggregations> value) {
        aggregations_ = NullableField<std::vector<RunCreateMeasurementsAggregations>>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `aggregations` to null.
    RunCreateMeasurementsBuilder& aggregations_null() {
        aggregations_ = NullableField<std::vector<RunCreateMeasurementsAggregations>>::make_null();
        return *this;
    }

    /// Set the `docstring` field.
    RunCreateMeasurementsBuilder& docstring(std::string value) {
        docstring_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `docstring` to null.
    RunCreateMeasurementsBuilder& docstring_null() {
        docstring_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    RunCreateMeasurements build() const& {
        RunCreateMeasurements result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = outcome_.value();
        result.x_axis = x_axis_;
        result.y_axis = y_axis_;
        result.measured_value = measured_value_;
        result.units = units_;
        result.lower_limit = lower_limit_;
        result.upper_limit = upper_limit_;
        result.validators = validators_;
        result.aggregations = aggregations_;
        result.docstring = docstring_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    RunCreateMeasurements build() && {
        RunCreateMeasurements result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        if (!outcome_.has_value()) {
            throw std::runtime_error("missing required field: outcome");
        }
        result.outcome = std::move(outcome_.value());
        result.x_axis = std::move(x_axis_);
        result.y_axis = std::move(y_axis_);
        result.measured_value = std::move(measured_value_);
        result.units = std::move(units_);
        result.lower_limit = std::move(lower_limit_);
        result.upper_limit = std::move(upper_limit_);
        result.validators = std::move(validators_);
        result.aggregations = std::move(aggregations_);
        result.docstring = std::move(docstring_);
        return result;
    }

private:
    std::optional<std::string> name_;
    std::optional<ValidatorsOutcome> outcome_;
    NullableField<RunCreateXAxis> x_axis_;
    NullableField<std::vector<RunCreateYAxis>> y_axis_;
    NullableField<nlohmann::json> measured_value_;
    NullableField<nlohmann::json> units_;
    std::optional<double> lower_limit_;
    std::optional<double> upper_limit_;
    NullableField<std::vector<RunCreateMeasurementsValidators>> validators_;
    NullableField<std::vector<RunCreateMeasurementsAggregations>> aggregations_;
    NullableField<std::string> docstring_;
};

} // namespace tofupilot
