// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/level.hpp"

namespace tofupilot {

struct RunCreateLogs {
    /// Severity level of the log message following standard system logging levels. Use DEBUG for detailed diagnostic information, INFO for general execution information, WARNING for unexpected events or potential issues, ERROR for serious problems that prevented function execution, CRITICAL for severe errors that may cause program termination.
    Level level;
    /// ISO 8601 timestamp when the log message was generated.
    std::string timestamp;
    /// Content of the log message. Contains the actual log text describing the event, error, or information being logged. Messages longer than 10,000 characters will be truncated.
    std::string message;
    /// Name or path of the source file where the log message originated. Helps identify the code location that generated the log entry.
    std::string source_file;
    /// Line number in the source file where the log message was generated. Used for debugging and tracing log origins.
    int64_t line_number;
};

inline void to_json(nlohmann::json& j, const RunCreateLogs& v) {
    j = nlohmann::json::object();
    j["level"] = v.level;
    j["timestamp"] = v.timestamp;
    j["message"] = v.message;
    j["source_file"] = v.source_file;
    j["line_number"] = v.line_number;
}

inline void from_json(const nlohmann::json& j, RunCreateLogs& v) {
    if (!j.contains("level")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: level", &j);
    }
    v.level = j["level"].get<Level>();
    if (!j.contains("timestamp")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: timestamp", &j);
    }
    v.timestamp = j["timestamp"].get<std::string>();
    if (!j.contains("message")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: message", &j);
    }
    v.message = j["message"].get<std::string>();
    if (!j.contains("source_file")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: source_file", &j);
    }
    v.source_file = j["source_file"].get<std::string>();
    if (!j.contains("line_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: line_number", &j);
    }
    v.line_number = j["line_number"].get<int64_t>();
}

} // namespace tofupilot
