// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Expected value for comparison. Type depends on operator.
using RunCreateExpectedValue = std::variant<
    bool,
    double,
    std::string,
    std::vector<double>,
    std::vector<std::string>
>;

inline void to_json(nlohmann::json& j, const RunCreateExpectedValue& v) {
    std::visit([&j](const auto& val) { j = val; }, v);
}

inline void from_json(const nlohmann::json& j, RunCreateExpectedValue& v) {
    if (j.is_boolean()) { v = j.get<bool>(); return; }
    if (j.is_number()) { v = j.get<double>(); return; }
    if (j.is_string()) { v = j.get<std::string>(); return; }
    if (j.is_array()) { v = j.get<std::vector<double>>(); return; }
    if (j.is_array()) { v = j.get<std::vector<std::string>>(); return; }
    throw nlohmann::json::type_error::create(302, "cannot convert JSON to RunCreateExpectedValue", &j);
}

} // namespace tofupilot
