// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Reference-sample classification. 'golden' marks a known-good reference unit; 'failing' marks a known-faulty reference unit. Both are excluded from production analytics aggregates (FPY, Cpk, throughput) by default. Omit or null for regular production units.
enum class Sample {
    Golden,
    Failing,
};

NLOHMANN_JSON_SERIALIZE_ENUM(Sample, {
    { Sample::Golden, "golden" },
    { Sample::Failing, "failing" },
})

inline std::string to_string(Sample e) {
    switch (e) {
        case Sample::Golden: return "golden";
        case Sample::Failing: return "failing";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
