// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/station_update_request_body.hpp"

namespace tofupilot {

struct StationUpdateRequest {
    /// Unique identifier of the station to update
    std::string id;
    StationUpdateRequestBody request_body;
};

inline void to_json(nlohmann::json& j, const StationUpdateRequest& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["request_body"] = v.request_body;
}

inline void from_json(const nlohmann::json& j, StationUpdateRequest& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("request_body")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: request_body", &j);
    }
    v.request_body = j["request_body"].get<StationUpdateRequestBody>();
}

} // namespace tofupilot
