// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct StationGetCurrentCommit {
    /// Git commit SHA
    std::string sha;
    /// Git commit message
    std::string message;
    /// Git branch name
    std::optional<std::string> branch;
};

inline void to_json(nlohmann::json& j, const StationGetCurrentCommit& v) {
    j = nlohmann::json::object();
    j["sha"] = v.sha;
    j["message"] = v.message;
    if (v.branch.has_value()) {
        j["branch"] = v.branch.value();
    }
}

inline void from_json(const nlohmann::json& j, StationGetCurrentCommit& v) {
    if (!j.contains("sha")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: sha", &j);
    }
    v.sha = j["sha"].get<std::string>();
    if (!j.contains("message")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: message", &j);
    }
    v.message = j["message"].get<std::string>();
    if (j.contains("branch") && !j["branch"].is_null()) {
        v.branch = j["branch"].get<std::string>();
    }
}

/// Builder for StationGetCurrentCommit.
class StationGetCurrentCommitBuilder {
public:
    /// Set the `sha` field.
    /// Git commit SHA
    StationGetCurrentCommitBuilder& sha(std::string value) {
        sha_ = std::move(value);
        return *this;
    }

    /// Set the `message` field.
    /// Git commit message
    StationGetCurrentCommitBuilder& message(std::string value) {
        message_ = std::move(value);
        return *this;
    }

    /// Set the `branch` field.
    /// Git branch name
    StationGetCurrentCommitBuilder& branch(std::string value) {
        branch_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationGetCurrentCommit build() const& {
        StationGetCurrentCommit result;
        if (!sha_.has_value()) {
            throw std::runtime_error("missing required field: sha");
        }
        result.sha = sha_.value();
        if (!message_.has_value()) {
            throw std::runtime_error("missing required field: message");
        }
        result.message = message_.value();
        result.branch = branch_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationGetCurrentCommit build() && {
        StationGetCurrentCommit result;
        if (!sha_.has_value()) {
            throw std::runtime_error("missing required field: sha");
        }
        result.sha = std::move(sha_.value());
        if (!message_.has_value()) {
            throw std::runtime_error("missing required field: message");
        }
        result.message = std::move(message_.value());
        result.branch = std::move(branch_);
        return result;
    }

private:
    std::optional<std::string> sha_;
    std::optional<std::string> message_;
    std::optional<std::string> branch_;
};

} // namespace tofupilot
