// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct StationCreateRequest {
    /// Name of the station
    std::string name;
    /// Optional procedure ID to link the station to
    std::optional<std::string> procedure_id;
};

inline void to_json(nlohmann::json& j, const StationCreateRequest& v) {
    j = nlohmann::json::object();
    j["name"] = v.name;
    if (v.procedure_id.has_value()) {
        j["procedure_id"] = v.procedure_id.value();
    }
}

inline void from_json(const nlohmann::json& j, StationCreateRequest& v) {
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (j.contains("procedure_id") && !j["procedure_id"].is_null()) {
        v.procedure_id = j["procedure_id"].get<std::string>();
    }
}

/// Builder for StationCreateRequest.
class StationCreateRequestBuilder {
public:
    /// Set the `name` field.
    /// Name of the station
    StationCreateRequestBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_id` field.
    /// Optional procedure ID to link the station to
    StationCreateRequestBuilder& procedure_id(std::string value) {
        procedure_id_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationCreateRequest build() const& {
        StationCreateRequest result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        result.procedure_id = procedure_id_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationCreateRequest build() && {
        StationCreateRequest result;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        result.procedure_id = std::move(procedure_id_);
        return result;
    }

private:
    std::optional<std::string> name_;
    std::optional<std::string> procedure_id_;
};

} // namespace tofupilot
