// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/station_get_commit.hpp"
#include "tofupilot/models/station_get_repository.hpp"

namespace tofupilot {

struct StationGetDeployment {
    /// When the procedure was deployed
    std::string deployed_at;
    std::optional<StationGetCommit> commit;
    std::optional<StationGetRepository> repository;
};

inline void to_json(nlohmann::json& j, const StationGetDeployment& v) {
    j = nlohmann::json::object();
    j["deployed_at"] = v.deployed_at;
    if (v.commit.has_value()) {
        j["commit"] = v.commit.value();
    }
    if (v.repository.has_value()) {
        j["repository"] = v.repository.value();
    }
}

inline void from_json(const nlohmann::json& j, StationGetDeployment& v) {
    if (!j.contains("deployed_at")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: deployed_at", &j);
    }
    v.deployed_at = j["deployed_at"].get<std::string>();
    if (j.contains("commit") && !j["commit"].is_null()) {
        v.commit = j["commit"].get<StationGetCommit>();
    }
    if (j.contains("repository") && !j["repository"].is_null()) {
        v.repository = j["repository"].get<StationGetRepository>();
    }
}

/// Builder for StationGetDeployment.
class StationGetDeploymentBuilder {
public:
    /// Set the `deployed_at` field.
    /// When the procedure was deployed
    StationGetDeploymentBuilder& deployed_at(std::string value) {
        deployed_at_ = std::move(value);
        return *this;
    }

    /// Set the `commit` field.
    StationGetDeploymentBuilder& commit(StationGetCommit value) {
        commit_ = std::move(value);
        return *this;
    }

    /// Set the `repository` field.
    StationGetDeploymentBuilder& repository(StationGetRepository value) {
        repository_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationGetDeployment build() const& {
        StationGetDeployment result;
        if (!deployed_at_.has_value()) {
            throw std::runtime_error("missing required field: deployed_at");
        }
        result.deployed_at = deployed_at_.value();
        result.commit = commit_;
        result.repository = repository_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationGetDeployment build() && {
        StationGetDeployment result;
        if (!deployed_at_.has_value()) {
            throw std::runtime_error("missing required field: deployed_at");
        }
        result.deployed_at = std::move(deployed_at_.value());
        result.commit = std::move(commit_);
        result.repository = std::move(repository_);
        return result;
    }

private:
    std::optional<std::string> deployed_at_;
    std::optional<StationGetCommit> commit_;
    std::optional<StationGetRepository> repository_;
};

} // namespace tofupilot
