// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/station_get_procedures.hpp"
#include "tofupilot/models/station_get_team.hpp"

namespace tofupilot {

/// Station retrieved successfully
struct StationGetResponse {
    /// Unique identifier of the station
    std::string id;
    /// Name of the station
    std::string name;
    /// API key prefix for the station (full key only shown on creation)
    std::optional<std::string> api_key;
    /// Procedures linked to this station with recent run counts
    std::vector<StationGetProcedures> procedures;
    /// Slug of the organization this station belongs to
    std::string organization_slug;
    /// Current connection status of the station
    std::optional<std::string> connection_status;
    /// Team this station is assigned to
    std::optional<StationGetTeam> team;
};

inline void to_json(nlohmann::json& j, const StationGetResponse& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    if (v.api_key.has_value()) {
        j["api_key"] = v.api_key.value();
    }
    j["procedures"] = v.procedures;
    j["organization_slug"] = v.organization_slug;
    if (v.connection_status.has_value()) {
        j["connection_status"] = v.connection_status.value();
    }
    if (v.team.has_value()) {
        j["team"] = v.team.value();
    }
}

inline void from_json(const nlohmann::json& j, StationGetResponse& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (j.contains("api_key") && !j["api_key"].is_null()) {
        v.api_key = j["api_key"].get<std::string>();
    }
    if (j.contains("procedures") && j["procedures"].is_array()) {
        v.procedures = j["procedures"].get<std::vector<StationGetProcedures>>();
    }
    if (!j.contains("organization_slug")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: organization_slug", &j);
    }
    v.organization_slug = j["organization_slug"].get<std::string>();
    if (j.contains("connection_status") && !j["connection_status"].is_null()) {
        v.connection_status = j["connection_status"].get<std::string>();
    }
    if (j.contains("team") && !j["team"].is_null()) {
        v.team = j["team"].get<StationGetTeam>();
    }
}

} // namespace tofupilot
