// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct StationListProcedures {
    /// Procedure ID
    std::string id;
    /// Procedure identifier
    std::optional<std::string> identifier;
    /// Procedure name
    std::string name;
};

inline void to_json(nlohmann::json& j, const StationListProcedures& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    if (v.identifier.has_value()) {
        j["identifier"] = v.identifier.value();
    }
    j["name"] = v.name;
}

inline void from_json(const nlohmann::json& j, StationListProcedures& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (j.contains("identifier") && !j["identifier"].is_null()) {
        v.identifier = j["identifier"].get<std::string>();
    }
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
}

/// Builder for StationListProcedures.
class StationListProceduresBuilder {
public:
    /// Set the `id` field.
    /// Procedure ID
    StationListProceduresBuilder& id(std::string value) {
        id_ = std::move(value);
        return *this;
    }

    /// Set the `identifier` field.
    /// Procedure identifier
    StationListProceduresBuilder& identifier(std::string value) {
        identifier_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    /// Procedure name
    StationListProceduresBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationListProcedures build() const& {
        StationListProcedures result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = id_.value();
        result.identifier = identifier_;
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationListProcedures build() && {
        StationListProcedures result;
        if (!id_.has_value()) {
            throw std::runtime_error("missing required field: id");
        }
        result.id = std::move(id_.value());
        result.identifier = std::move(identifier_);
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        return result;
    }

private:
    std::optional<std::string> id_;
    std::optional<std::string> identifier_;
    std::optional<std::string> name_;
};

} // namespace tofupilot
