// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/station_list_data.hpp"
#include "tofupilot/models/station_list_meta.hpp"

namespace tofupilot {

/// Stations retrieved successfully
struct StationListResponse {
    /// List of stations matching the search criteria
    std::vector<StationListData> data;
    /// Pagination metadata
    StationListMeta meta;
};

inline void to_json(nlohmann::json& j, const StationListResponse& v) {
    j = nlohmann::json::object();
    j["data"] = v.data;
    j["meta"] = v.meta;
}

inline void from_json(const nlohmann::json& j, StationListResponse& v) {
    if (j.contains("data") && j["data"].is_array()) {
        v.data = j["data"].get<std::vector<StationListData>>();
    }
    if (!j.contains("meta")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: meta", &j);
    }
    v.meta = j["meta"].get<StationListMeta>();
}

} // namespace tofupilot
