// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct StationListRequest {
    /// Number of stations to return per page
    std::optional<int64_t> limit;
    std::optional<int64_t> cursor;
    std::optional<std::string> search_query;
    std::optional<std::vector<std::string>> procedure_ids;
    /// Filter stations by custom metadata. Supports up to 5 keys per request. Per-key operators: string `{in: [...]}`/`{contains: "..."}`, number `{gte, lte, gt, lt, eq}`, bool `{eq: true|false}`.
    std::optional<std::map<std::string, nlohmann::json>> metadata;
    /// When true, includes the custom metadata object on each station in the response. Defaults to false to keep payloads small.
    std::optional<bool> include_metadata;
};

inline void to_json(nlohmann::json& j, const StationListRequest& v) {
    j = nlohmann::json::object();
    if (v.limit.has_value()) {
        j["limit"] = v.limit.value();
    }
    if (v.cursor.has_value()) {
        j["cursor"] = v.cursor.value();
    }
    if (v.search_query.has_value()) {
        j["search_query"] = v.search_query.value();
    }
    if (v.procedure_ids.has_value()) {
        j["procedure_ids"] = v.procedure_ids.value();
    }
    if (v.metadata.has_value()) {
        j["metadata"] = v.metadata.value();
    }
    if (v.include_metadata.has_value()) {
        j["include_metadata"] = v.include_metadata.value();
    }
}

inline void from_json(const nlohmann::json& j, StationListRequest& v) {
    if (j.contains("limit") && !j["limit"].is_null()) {
        v.limit = j["limit"].get<int64_t>();
    }
    if (j.contains("cursor") && !j["cursor"].is_null()) {
        v.cursor = j["cursor"].get<int64_t>();
    }
    if (j.contains("search_query") && !j["search_query"].is_null()) {
        v.search_query = j["search_query"].get<std::string>();
    }
    if (j.contains("procedure_ids") && !j["procedure_ids"].is_null()) {
        v.procedure_ids = j["procedure_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("metadata") && !j["metadata"].is_null()) {
        v.metadata = j["metadata"].get<std::map<std::string, nlohmann::json>>();
    }
    if (j.contains("include_metadata") && !j["include_metadata"].is_null()) {
        v.include_metadata = j["include_metadata"].get<bool>();
    }
}

/// Builder for StationListRequest.
class StationListRequestBuilder {
public:
    /// Set the `limit` field.
    /// Number of stations to return per page
    StationListRequestBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }

    /// Set the `cursor` field.
    StationListRequestBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    /// Set the `search_query` field.
    StationListRequestBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_ids` field.
    StationListRequestBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }

    /// Set the `metadata` field.
    /// Filter stations by custom metadata. Supports up to 5 keys per request. Per-key operators: string `{in: [...]}`/`{contains: "..."}`, number `{gte, lte, gt, lt, eq}`, bool `{eq: true|false}`.
    StationListRequestBuilder& metadata(std::map<std::string, nlohmann::json> value) {
        metadata_ = std::move(value);
        return *this;
    }

    /// Set the `include_metadata` field.
    /// When true, includes the custom metadata object on each station in the response. Defaults to false to keep payloads small.
    StationListRequestBuilder& include_metadata(bool value) {
        include_metadata_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationListRequest build() const& {
        StationListRequest result;
        result.limit = limit_;
        result.cursor = cursor_;
        result.search_query = search_query_;
        result.procedure_ids = procedure_ids_;
        result.metadata = metadata_;
        result.include_metadata = include_metadata_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationListRequest build() && {
        StationListRequest result;
        result.limit = std::move(limit_);
        result.cursor = std::move(cursor_);
        result.search_query = std::move(search_query_);
        result.procedure_ids = std::move(procedure_ids_);
        result.metadata = std::move(metadata_);
        result.include_metadata = std::move(include_metadata_);
        return result;
    }

private:
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<std::map<std::string, nlohmann::json>> metadata_;
    std::optional<bool> include_metadata_;
};

} // namespace tofupilot
