// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/provider.hpp"

namespace tofupilot {

struct StationGetCurrentRepository {
    /// Repository owner
    std::string owner;
    /// Repository name
    std::string name;
    /// Git provider
    Provider provider;
    /// GitLab project ID (only for GitLab repos)
    std::optional<double> gitlab_project_id;
};

inline void to_json(nlohmann::json& j, const StationGetCurrentRepository& v) {
    j = nlohmann::json::object();
    j["owner"] = v.owner;
    j["name"] = v.name;
    j["provider"] = v.provider;
    if (v.gitlab_project_id.has_value()) {
        j["gitlab_project_id"] = v.gitlab_project_id.value();
    }
}

inline void from_json(const nlohmann::json& j, StationGetCurrentRepository& v) {
    if (!j.contains("owner")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: owner", &j);
    }
    v.owner = j["owner"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("provider")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: provider", &j);
    }
    v.provider = j["provider"].get<Provider>();
    if (j.contains("gitlab_project_id") && !j["gitlab_project_id"].is_null()) {
        v.gitlab_project_id = j["gitlab_project_id"].get<double>();
    }
}

/// Builder for StationGetCurrentRepository.
class StationGetCurrentRepositoryBuilder {
public:
    /// Set the `owner` field.
    /// Repository owner
    StationGetCurrentRepositoryBuilder& owner(std::string value) {
        owner_ = std::move(value);
        return *this;
    }

    /// Set the `name` field.
    /// Repository name
    StationGetCurrentRepositoryBuilder& name(std::string value) {
        name_ = std::move(value);
        return *this;
    }

    /// Set the `provider` field.
    /// Git provider
    StationGetCurrentRepositoryBuilder& provider(Provider value) {
        provider_ = std::move(value);
        return *this;
    }

    /// Set the `gitlab_project_id` field.
    /// GitLab project ID (only for GitLab repos)
    StationGetCurrentRepositoryBuilder& gitlab_project_id(double value) {
        gitlab_project_id_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    StationGetCurrentRepository build() const& {
        StationGetCurrentRepository result;
        if (!owner_.has_value()) {
            throw std::runtime_error("missing required field: owner");
        }
        result.owner = owner_.value();
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = name_.value();
        if (!provider_.has_value()) {
            throw std::runtime_error("missing required field: provider");
        }
        result.provider = provider_.value();
        result.gitlab_project_id = gitlab_project_id_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    StationGetCurrentRepository build() && {
        StationGetCurrentRepository result;
        if (!owner_.has_value()) {
            throw std::runtime_error("missing required field: owner");
        }
        result.owner = std::move(owner_.value());
        if (!name_.has_value()) {
            throw std::runtime_error("missing required field: name");
        }
        result.name = std::move(name_.value());
        if (!provider_.has_value()) {
            throw std::runtime_error("missing required field: provider");
        }
        result.provider = std::move(provider_.value());
        result.gitlab_project_id = std::move(gitlab_project_id_);
        return result;
    }

private:
    std::optional<std::string> owner_;
    std::optional<std::string> name_;
    std::optional<Provider> provider_;
    std::optional<double> gitlab_project_id_;
};

} // namespace tofupilot
