// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct UnitDeleteAttachmentRequest {
    /// Serial number of the unit. Matched case-insensitively.
    std::string serial_number;
    /// Attachment IDs to delete
    std::vector<std::string> ids;
};

inline void to_json(nlohmann::json& j, const UnitDeleteAttachmentRequest& v) {
    j = nlohmann::json::object();
    j["serial_number"] = v.serial_number;
    j["ids"] = v.ids;
}

inline void from_json(const nlohmann::json& j, UnitDeleteAttachmentRequest& v) {
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
    if (j.contains("ids") && j["ids"].is_array()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
}

/// Builder for UnitDeleteAttachmentRequest.
class UnitDeleteAttachmentRequestBuilder {
public:
    /// Set the `serial_number` field.
    /// Serial number of the unit. Matched case-insensitively.
    UnitDeleteAttachmentRequestBuilder& serial_number(std::string value) {
        serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `ids` field.
    /// Attachment IDs to delete
    UnitDeleteAttachmentRequestBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    UnitDeleteAttachmentRequest build() const& {
        UnitDeleteAttachmentRequest result;
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = serial_number_.value();
        if (ids_.has_value()) {
            result.ids = ids_.value();
        }
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    UnitDeleteAttachmentRequest build() && {
        UnitDeleteAttachmentRequest result;
        if (!serial_number_.has_value()) {
            throw std::runtime_error("missing required field: serial_number");
        }
        result.serial_number = std::move(serial_number_.value());
        if (ids_.has_value()) {
            result.ids = std::move(ids_.value());
        }
        return result;
    }

private:
    std::optional<std::string> serial_number_;
    std::optional<std::vector<std::string>> ids_;
};

} // namespace tofupilot
