// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/nullable.hpp"

namespace tofupilot {

struct UnitUpdateRequestBody {
    /// New serial number for the unit.
    std::optional<std::string> new_serial_number;
    /// New part number for the unit.
    std::optional<std::string> part_number;
    /// New revision number for the unit.
    std::optional<std::string> revision_number;
    /// New batch number for the unit. Set to null to remove batch.
    NullableField<std::string> batch_number;
    /// Array of upload IDs to attach to the unit.
    std::optional<std::vector<std::string>> attachments;
    /// Reference-sample classification. 'golden' marks a known-good reference unit; 'failing' marks a known-faulty reference unit. Both are excluded from production analytics by default. Set to null to clear and treat as a production unit.
    NullableField<std::string> sample;
    /// Custom metadata to upsert on the unit. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key. Pass `metadata_replace: true` to drop all keys not present.
    std::optional<std::map<std::string, nlohmann::json>> metadata;
    /// When true, removes any metadata keys not present in `metadata`. Default: false (PATCH).
    std::optional<bool> metadata_replace;
};

inline void to_json(nlohmann::json& j, const UnitUpdateRequestBody& v) {
    j = nlohmann::json::object();
    if (v.new_serial_number.has_value()) {
        j["new_serial_number"] = v.new_serial_number.value();
    }
    if (v.part_number.has_value()) {
        j["part_number"] = v.part_number.value();
    }
    if (v.revision_number.has_value()) {
        j["revision_number"] = v.revision_number.value();
    }
    if (!v.batch_number.is_absent()) {
        if (v.batch_number.is_null()) {
            j["batch_number"] = nullptr;
        } else {
            j["batch_number"] = v.batch_number.get();
        }
    }
    if (v.attachments.has_value()) {
        j["attachments"] = v.attachments.value();
    }
    if (!v.sample.is_absent()) {
        if (v.sample.is_null()) {
            j["sample"] = nullptr;
        } else {
            j["sample"] = v.sample.get();
        }
    }
    if (v.metadata.has_value()) {
        j["metadata"] = v.metadata.value();
    }
    if (v.metadata_replace.has_value()) {
        j["metadata_replace"] = v.metadata_replace.value();
    }
}

inline void from_json(const nlohmann::json& j, UnitUpdateRequestBody& v) {
    if (j.contains("new_serial_number") && !j["new_serial_number"].is_null()) {
        v.new_serial_number = j["new_serial_number"].get<std::string>();
    }
    if (j.contains("part_number") && !j["part_number"].is_null()) {
        v.part_number = j["part_number"].get<std::string>();
    }
    if (j.contains("revision_number") && !j["revision_number"].is_null()) {
        v.revision_number = j["revision_number"].get<std::string>();
    }
    if (j.contains("batch_number")) {
        if (j["batch_number"].is_null()) {
            v.batch_number = NullableField<std::string>::make_null();
        } else {
            v.batch_number = NullableField<std::string>::value(j["batch_number"].get<std::string>());
        }
    }
    if (j.contains("attachments") && !j["attachments"].is_null()) {
        v.attachments = j["attachments"].get<std::vector<std::string>>();
    }
    if (j.contains("sample")) {
        if (j["sample"].is_null()) {
            v.sample = NullableField<std::string>::make_null();
        } else {
            v.sample = NullableField<std::string>::value(j["sample"].get<std::string>());
        }
    }
    if (j.contains("metadata") && !j["metadata"].is_null()) {
        v.metadata = j["metadata"].get<std::map<std::string, nlohmann::json>>();
    }
    if (j.contains("metadata_replace") && !j["metadata_replace"].is_null()) {
        v.metadata_replace = j["metadata_replace"].get<bool>();
    }
}

/// Builder for UnitUpdateRequestBody.
class UnitUpdateRequestBodyBuilder {
public:
    /// Set the `new_serial_number` field.
    /// New serial number for the unit.
    UnitUpdateRequestBodyBuilder& new_serial_number(std::string value) {
        new_serial_number_ = std::move(value);
        return *this;
    }

    /// Set the `part_number` field.
    /// New part number for the unit.
    UnitUpdateRequestBodyBuilder& part_number(std::string value) {
        part_number_ = std::move(value);
        return *this;
    }

    /// Set the `revision_number` field.
    /// New revision number for the unit.
    UnitUpdateRequestBodyBuilder& revision_number(std::string value) {
        revision_number_ = std::move(value);
        return *this;
    }

    /// Set the `batch_number` field.
    /// New batch number for the unit. Set to null to remove batch.
    UnitUpdateRequestBodyBuilder& batch_number(std::string value) {
        batch_number_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `batch_number` to null.
    UnitUpdateRequestBodyBuilder& batch_number_null() {
        batch_number_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `attachments` field.
    /// Array of upload IDs to attach to the unit.
    UnitUpdateRequestBodyBuilder& attachments(std::vector<std::string> value) {
        attachments_ = std::move(value);
        return *this;
    }

    /// Set the `sample` field.
    /// Reference-sample classification. 'golden' marks a known-good reference unit; 'failing' marks a known-faulty reference unit. Both are excluded from production analytics by default. Set to null to clear and treat as a production unit.
    UnitUpdateRequestBodyBuilder& sample(std::string value) {
        sample_ = NullableField<std::string>::value(std::move(value));
        return *this;
    }

    /// Explicitly set `sample` to null.
    UnitUpdateRequestBodyBuilder& sample_null() {
        sample_ = NullableField<std::string>::make_null();
        return *this;
    }

    /// Set the `metadata` field.
    /// Custom metadata to upsert on the unit. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key. Pass `metadata_replace: true` to drop all keys not present.
    UnitUpdateRequestBodyBuilder& metadata(std::map<std::string, nlohmann::json> value) {
        metadata_ = std::move(value);
        return *this;
    }

    /// Set the `metadata_replace` field.
    /// When true, removes any metadata keys not present in `metadata`. Default: false (PATCH).
    UnitUpdateRequestBodyBuilder& metadata_replace(bool value) {
        metadata_replace_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    UnitUpdateRequestBody build() const& {
        UnitUpdateRequestBody result;
        result.new_serial_number = new_serial_number_;
        result.part_number = part_number_;
        result.revision_number = revision_number_;
        result.batch_number = batch_number_;
        result.attachments = attachments_;
        result.sample = sample_;
        result.metadata = metadata_;
        result.metadata_replace = metadata_replace_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    UnitUpdateRequestBody build() && {
        UnitUpdateRequestBody result;
        result.new_serial_number = std::move(new_serial_number_);
        result.part_number = std::move(part_number_);
        result.revision_number = std::move(revision_number_);
        result.batch_number = std::move(batch_number_);
        result.attachments = std::move(attachments_);
        result.sample = std::move(sample_);
        result.metadata = std::move(metadata_);
        result.metadata_replace = std::move(metadata_replace_);
        return result;
    }

private:
    std::optional<std::string> new_serial_number_;
    std::optional<std::string> part_number_;
    std::optional<std::string> revision_number_;
    NullableField<std::string> batch_number_;
    std::optional<std::vector<std::string>> attachments_;
    NullableField<std::string> sample_;
    std::optional<std::map<std::string, nlohmann::json>> metadata_;
    std::optional<bool> metadata_replace_;
};

} // namespace tofupilot
