// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct UnitListChildren {
    /// Unique identifier for the child unit.
    std::string id;
    /// Serial number of the child unit.
    std::string serial_number;
};

inline void to_json(nlohmann::json& j, const UnitListChildren& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["serial_number"] = v.serial_number;
}

inline void from_json(const nlohmann::json& j, UnitListChildren& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
}

} // namespace tofupilot
