// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Unit attachments deleted successfully
struct UnitDeleteAttachmentResponse {
    /// IDs of attachments that were deleted
    std::vector<std::string> ids;
};

inline void to_json(nlohmann::json& j, const UnitDeleteAttachmentResponse& v) {
    j = nlohmann::json::object();
    j["ids"] = v.ids;
}

inline void from_json(const nlohmann::json& j, UnitDeleteAttachmentResponse& v) {
    if (j.contains("ids") && j["ids"].is_array()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
}

} // namespace tofupilot
