// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/unit_update_request_body.hpp"

namespace tofupilot {

struct UnitUpdateRequest {
    /// Serial number of the unit to update.
    std::string serial_number;
    UnitUpdateRequestBody request_body;
};

inline void to_json(nlohmann::json& j, const UnitUpdateRequest& v) {
    j = nlohmann::json::object();
    j["serial_number"] = v.serial_number;
    j["request_body"] = v.request_body;
}

inline void from_json(const nlohmann::json& j, UnitUpdateRequest& v) {
    if (!j.contains("serial_number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: serial_number", &j);
    }
    v.serial_number = j["serial_number"].get<std::string>();
    if (!j.contains("request_body")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: request_body", &j);
    }
    v.request_body = j["request_body"].get<UnitUpdateRequestBody>();
}

} // namespace tofupilot
