// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <string>

#include <nlohmann/json.hpp>

namespace tofupilot {

/// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
enum class UnitListSortBy {
    SerialNumber,
    CreatedAt,
    LastRunAt,
    PartNumber,
    LastRunProcedure,
};

NLOHMANN_JSON_SERIALIZE_ENUM(UnitListSortBy, {
    { UnitListSortBy::SerialNumber, "serial_number" },
    { UnitListSortBy::CreatedAt, "created_at" },
    { UnitListSortBy::LastRunAt, "last_run_at" },
    { UnitListSortBy::PartNumber, "part_number" },
    { UnitListSortBy::LastRunProcedure, "last_run_procedure" },
})

inline std::string to_string(UnitListSortBy e) {
    switch (e) {
        case UnitListSortBy::SerialNumber: return "serial_number";
        case UnitListSortBy::CreatedAt: return "created_at";
        case UnitListSortBy::LastRunAt: return "last_run_at";
        case UnitListSortBy::PartNumber: return "part_number";
        case UnitListSortBy::LastRunProcedure: return "last_run_procedure";
    }
    return "unknown"; // unreachable — silences compiler warning without hiding -Wswitch
}

} // namespace tofupilot
