// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/list_sort_order.hpp"
#include "tofupilot/models/outcome.hpp"
#include "tofupilot/models/unit_list_sort_by.hpp"

namespace tofupilot {

struct UnitListRequest {
    std::optional<std::string> search_query;
    std::optional<std::vector<std::string>> ids;
    std::optional<std::vector<std::string>> serial_numbers;
    std::optional<std::vector<std::string>> part_numbers;
    std::optional<std::vector<std::string>> revision_numbers;
    std::optional<std::vector<std::string>> batch_numbers;
    std::optional<std::vector<std::string>> procedure_ids;
    std::optional<std::vector<Outcome>> outcomes;
    std::optional<std::string> started_after;
    std::optional<std::string> started_before;
    std::optional<bool> latest_only;
    std::optional<int64_t> run_count_min;
    std::optional<int64_t> run_count_max;
    std::optional<std::string> created_after;
    std::optional<std::string> created_before;
    std::optional<std::vector<std::string>> created_by_user_ids;
    std::optional<std::vector<std::string>> created_by_station_ids;
    std::optional<bool> exclude_units_with_parent;
    /// Maximum number of units to return.
    std::optional<int64_t> limit;
    std::optional<int64_t> cursor;
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    std::optional<UnitListSortBy> sort_by;
    /// Sort order direction.
    std::optional<ListSortOrder> sort_order;
};

inline void to_json(nlohmann::json& j, const UnitListRequest& v) {
    j = nlohmann::json::object();
    if (v.search_query.has_value()) {
        j["search_query"] = v.search_query.value();
    }
    if (v.ids.has_value()) {
        j["ids"] = v.ids.value();
    }
    if (v.serial_numbers.has_value()) {
        j["serial_numbers"] = v.serial_numbers.value();
    }
    if (v.part_numbers.has_value()) {
        j["part_numbers"] = v.part_numbers.value();
    }
    if (v.revision_numbers.has_value()) {
        j["revision_numbers"] = v.revision_numbers.value();
    }
    if (v.batch_numbers.has_value()) {
        j["batch_numbers"] = v.batch_numbers.value();
    }
    if (v.procedure_ids.has_value()) {
        j["procedure_ids"] = v.procedure_ids.value();
    }
    if (v.outcomes.has_value()) {
        j["outcomes"] = v.outcomes.value();
    }
    if (v.started_after.has_value()) {
        j["started_after"] = v.started_after.value();
    }
    if (v.started_before.has_value()) {
        j["started_before"] = v.started_before.value();
    }
    if (v.latest_only.has_value()) {
        j["latest_only"] = v.latest_only.value();
    }
    if (v.run_count_min.has_value()) {
        j["run_count_min"] = v.run_count_min.value();
    }
    if (v.run_count_max.has_value()) {
        j["run_count_max"] = v.run_count_max.value();
    }
    if (v.created_after.has_value()) {
        j["created_after"] = v.created_after.value();
    }
    if (v.created_before.has_value()) {
        j["created_before"] = v.created_before.value();
    }
    if (v.created_by_user_ids.has_value()) {
        j["created_by_user_ids"] = v.created_by_user_ids.value();
    }
    if (v.created_by_station_ids.has_value()) {
        j["created_by_station_ids"] = v.created_by_station_ids.value();
    }
    if (v.exclude_units_with_parent.has_value()) {
        j["exclude_units_with_parent"] = v.exclude_units_with_parent.value();
    }
    if (v.limit.has_value()) {
        j["limit"] = v.limit.value();
    }
    if (v.cursor.has_value()) {
        j["cursor"] = v.cursor.value();
    }
    if (v.sort_by.has_value()) {
        j["sort_by"] = v.sort_by.value();
    }
    if (v.sort_order.has_value()) {
        j["sort_order"] = v.sort_order.value();
    }
}

inline void from_json(const nlohmann::json& j, UnitListRequest& v) {
    if (j.contains("search_query") && !j["search_query"].is_null()) {
        v.search_query = j["search_query"].get<std::string>();
    }
    if (j.contains("ids") && !j["ids"].is_null()) {
        v.ids = j["ids"].get<std::vector<std::string>>();
    }
    if (j.contains("serial_numbers") && !j["serial_numbers"].is_null()) {
        v.serial_numbers = j["serial_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("part_numbers") && !j["part_numbers"].is_null()) {
        v.part_numbers = j["part_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("revision_numbers") && !j["revision_numbers"].is_null()) {
        v.revision_numbers = j["revision_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("batch_numbers") && !j["batch_numbers"].is_null()) {
        v.batch_numbers = j["batch_numbers"].get<std::vector<std::string>>();
    }
    if (j.contains("procedure_ids") && !j["procedure_ids"].is_null()) {
        v.procedure_ids = j["procedure_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("outcomes") && !j["outcomes"].is_null()) {
        v.outcomes = j["outcomes"].get<std::vector<Outcome>>();
    }
    if (j.contains("started_after") && !j["started_after"].is_null()) {
        v.started_after = j["started_after"].get<std::string>();
    }
    if (j.contains("started_before") && !j["started_before"].is_null()) {
        v.started_before = j["started_before"].get<std::string>();
    }
    if (j.contains("latest_only") && !j["latest_only"].is_null()) {
        v.latest_only = j["latest_only"].get<bool>();
    }
    if (j.contains("run_count_min") && !j["run_count_min"].is_null()) {
        v.run_count_min = j["run_count_min"].get<int64_t>();
    }
    if (j.contains("run_count_max") && !j["run_count_max"].is_null()) {
        v.run_count_max = j["run_count_max"].get<int64_t>();
    }
    if (j.contains("created_after") && !j["created_after"].is_null()) {
        v.created_after = j["created_after"].get<std::string>();
    }
    if (j.contains("created_before") && !j["created_before"].is_null()) {
        v.created_before = j["created_before"].get<std::string>();
    }
    if (j.contains("created_by_user_ids") && !j["created_by_user_ids"].is_null()) {
        v.created_by_user_ids = j["created_by_user_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("created_by_station_ids") && !j["created_by_station_ids"].is_null()) {
        v.created_by_station_ids = j["created_by_station_ids"].get<std::vector<std::string>>();
    }
    if (j.contains("exclude_units_with_parent") && !j["exclude_units_with_parent"].is_null()) {
        v.exclude_units_with_parent = j["exclude_units_with_parent"].get<bool>();
    }
    if (j.contains("limit") && !j["limit"].is_null()) {
        v.limit = j["limit"].get<int64_t>();
    }
    if (j.contains("cursor") && !j["cursor"].is_null()) {
        v.cursor = j["cursor"].get<int64_t>();
    }
    if (j.contains("sort_by") && !j["sort_by"].is_null()) {
        v.sort_by = j["sort_by"].get<UnitListSortBy>();
    }
    if (j.contains("sort_order") && !j["sort_order"].is_null()) {
        v.sort_order = j["sort_order"].get<ListSortOrder>();
    }
}

/// Builder for UnitListRequest.
class UnitListRequestBuilder {
public:
    /// Set the `search_query` field.
    UnitListRequestBuilder& search_query(std::string value) {
        search_query_ = std::move(value);
        return *this;
    }

    /// Set the `ids` field.
    UnitListRequestBuilder& ids(std::vector<std::string> value) {
        ids_ = std::move(value);
        return *this;
    }

    /// Set the `serial_numbers` field.
    UnitListRequestBuilder& serial_numbers(std::vector<std::string> value) {
        serial_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `part_numbers` field.
    UnitListRequestBuilder& part_numbers(std::vector<std::string> value) {
        part_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `revision_numbers` field.
    UnitListRequestBuilder& revision_numbers(std::vector<std::string> value) {
        revision_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `batch_numbers` field.
    UnitListRequestBuilder& batch_numbers(std::vector<std::string> value) {
        batch_numbers_ = std::move(value);
        return *this;
    }

    /// Set the `procedure_ids` field.
    UnitListRequestBuilder& procedure_ids(std::vector<std::string> value) {
        procedure_ids_ = std::move(value);
        return *this;
    }

    /// Set the `outcomes` field.
    UnitListRequestBuilder& outcomes(std::vector<Outcome> value) {
        outcomes_ = std::move(value);
        return *this;
    }

    /// Set the `started_after` field.
    UnitListRequestBuilder& started_after(std::string value) {
        started_after_ = std::move(value);
        return *this;
    }

    /// Set the `started_before` field.
    UnitListRequestBuilder& started_before(std::string value) {
        started_before_ = std::move(value);
        return *this;
    }

    /// Set the `latest_only` field.
    UnitListRequestBuilder& latest_only(bool value) {
        latest_only_ = std::move(value);
        return *this;
    }

    /// Set the `run_count_min` field.
    UnitListRequestBuilder& run_count_min(int64_t value) {
        run_count_min_ = std::move(value);
        return *this;
    }

    /// Set the `run_count_max` field.
    UnitListRequestBuilder& run_count_max(int64_t value) {
        run_count_max_ = std::move(value);
        return *this;
    }

    /// Set the `created_after` field.
    UnitListRequestBuilder& created_after(std::string value) {
        created_after_ = std::move(value);
        return *this;
    }

    /// Set the `created_before` field.
    UnitListRequestBuilder& created_before(std::string value) {
        created_before_ = std::move(value);
        return *this;
    }

    /// Set the `created_by_user_ids` field.
    UnitListRequestBuilder& created_by_user_ids(std::vector<std::string> value) {
        created_by_user_ids_ = std::move(value);
        return *this;
    }

    /// Set the `created_by_station_ids` field.
    UnitListRequestBuilder& created_by_station_ids(std::vector<std::string> value) {
        created_by_station_ids_ = std::move(value);
        return *this;
    }

    /// Set the `exclude_units_with_parent` field.
    UnitListRequestBuilder& exclude_units_with_parent(bool value) {
        exclude_units_with_parent_ = std::move(value);
        return *this;
    }

    /// Set the `limit` field.
    /// Maximum number of units to return.
    UnitListRequestBuilder& limit(int64_t value) {
        limit_ = std::move(value);
        return *this;
    }

    /// Set the `cursor` field.
    UnitListRequestBuilder& cursor(int64_t value) {
        cursor_ = std::move(value);
        return *this;
    }

    /// Set the `sort_by` field.
    /// Field to sort results by. last_run_at sorts by most recent test run date. last_run_procedure sorts by procedure name of the last run.
    UnitListRequestBuilder& sort_by(UnitListSortBy value) {
        sort_by_ = std::move(value);
        return *this;
    }

    /// Set the `sort_order` field.
    /// Sort order direction.
    UnitListRequestBuilder& sort_order(ListSortOrder value) {
        sort_order_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    UnitListRequest build() const& {
        UnitListRequest result;
        result.search_query = search_query_;
        result.ids = ids_;
        result.serial_numbers = serial_numbers_;
        result.part_numbers = part_numbers_;
        result.revision_numbers = revision_numbers_;
        result.batch_numbers = batch_numbers_;
        result.procedure_ids = procedure_ids_;
        result.outcomes = outcomes_;
        result.started_after = started_after_;
        result.started_before = started_before_;
        result.latest_only = latest_only_;
        result.run_count_min = run_count_min_;
        result.run_count_max = run_count_max_;
        result.created_after = created_after_;
        result.created_before = created_before_;
        result.created_by_user_ids = created_by_user_ids_;
        result.created_by_station_ids = created_by_station_ids_;
        result.exclude_units_with_parent = exclude_units_with_parent_;
        result.limit = limit_;
        result.cursor = cursor_;
        result.sort_by = sort_by_;
        result.sort_order = sort_order_;
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    UnitListRequest build() && {
        UnitListRequest result;
        result.search_query = std::move(search_query_);
        result.ids = std::move(ids_);
        result.serial_numbers = std::move(serial_numbers_);
        result.part_numbers = std::move(part_numbers_);
        result.revision_numbers = std::move(revision_numbers_);
        result.batch_numbers = std::move(batch_numbers_);
        result.procedure_ids = std::move(procedure_ids_);
        result.outcomes = std::move(outcomes_);
        result.started_after = std::move(started_after_);
        result.started_before = std::move(started_before_);
        result.latest_only = std::move(latest_only_);
        result.run_count_min = std::move(run_count_min_);
        result.run_count_max = std::move(run_count_max_);
        result.created_after = std::move(created_after_);
        result.created_before = std::move(created_before_);
        result.created_by_user_ids = std::move(created_by_user_ids_);
        result.created_by_station_ids = std::move(created_by_station_ids_);
        result.exclude_units_with_parent = std::move(exclude_units_with_parent_);
        result.limit = std::move(limit_);
        result.cursor = std::move(cursor_);
        result.sort_by = std::move(sort_by_);
        result.sort_order = std::move(sort_order_);
        return result;
    }

private:
    std::optional<std::string> search_query_;
    std::optional<std::vector<std::string>> ids_;
    std::optional<std::vector<std::string>> serial_numbers_;
    std::optional<std::vector<std::string>> part_numbers_;
    std::optional<std::vector<std::string>> revision_numbers_;
    std::optional<std::vector<std::string>> batch_numbers_;
    std::optional<std::vector<std::string>> procedure_ids_;
    std::optional<std::vector<Outcome>> outcomes_;
    std::optional<std::string> started_after_;
    std::optional<std::string> started_before_;
    std::optional<bool> latest_only_;
    std::optional<int64_t> run_count_min_;
    std::optional<int64_t> run_count_max_;
    std::optional<std::string> created_after_;
    std::optional<std::string> created_before_;
    std::optional<std::vector<std::string>> created_by_user_ids_;
    std::optional<std::vector<std::string>> created_by_station_ids_;
    std::optional<bool> exclude_units_with_parent_;
    std::optional<int64_t> limit_;
    std::optional<int64_t> cursor_;
    std::optional<UnitListSortBy> sort_by_;
    std::optional<ListSortOrder> sort_order_;
};

} // namespace tofupilot
