// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

struct UnitDeleteRequest {
    /// Array of unit serial numbers to delete.
    std::vector<std::string> serial_numbers;
};

inline void to_json(nlohmann::json& j, const UnitDeleteRequest& v) {
    j = nlohmann::json::object();
    j["serial_numbers"] = v.serial_numbers;
}

inline void from_json(const nlohmann::json& j, UnitDeleteRequest& v) {
    if (j.contains("serial_numbers") && j["serial_numbers"].is_array()) {
        v.serial_numbers = j["serial_numbers"].get<std::vector<std::string>>();
    }
}

/// Builder for UnitDeleteRequest.
class UnitDeleteRequestBuilder {
public:
    /// Set the `serial_numbers` field.
    /// Array of unit serial numbers to delete.
    UnitDeleteRequestBuilder& serial_numbers(std::vector<std::string> value) {
        serial_numbers_ = std::move(value);
        return *this;
    }

    /// Build the struct. Throws std::runtime_error if required fields are missing.
    UnitDeleteRequest build() const& {
        UnitDeleteRequest result;
        if (serial_numbers_.has_value()) {
            result.serial_numbers = serial_numbers_.value();
        }
        return result;
    }

    /// Build the struct (move overload). Throws std::runtime_error if required fields are missing.
    UnitDeleteRequest build() && {
        UnitDeleteRequest result;
        if (serial_numbers_.has_value()) {
            result.serial_numbers = std::move(serial_numbers_.value());
        }
        return result;
    }

private:
    std::optional<std::vector<std::string>> serial_numbers_;
};

} // namespace tofupilot
