// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Response for successful unit deletion
struct UnitDeleteResponse {
    /// IDs of units that were successfully deleted
    std::vector<std::string> id;
};

inline void to_json(nlohmann::json& j, const UnitDeleteResponse& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
}

inline void from_json(const nlohmann::json& j, UnitDeleteResponse& v) {
    if (j.contains("id") && j["id"].is_array()) {
        v.id = j["id"].get<std::vector<std::string>>();
    }
}

} // namespace tofupilot
