// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>


namespace tofupilot {

/// Child unit added successfully
struct UnitAddChildResponse {
    /// ID of the child unit that was added
    std::string id;
};

inline void to_json(nlohmann::json& j, const UnitAddChildResponse& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
}

inline void from_json(const nlohmann::json& j, UnitAddChildResponse& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
}

} // namespace tofupilot
