// Auto-generated by TofuPilot SDK Generator. DO NOT EDIT.

#pragma once

#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "tofupilot/models/unit_list_revision.hpp"

namespace tofupilot {

/// Part information with the specific revision this unit is built from.
struct UnitListPart {
    /// Unique identifier for the part.
    std::string id;
    /// Part number.
    std::string number;
    /// Human-readable part name.
    std::string name;
    /// Revision information for this part. Every unit must have a specific revision.
    UnitListRevision revision;
};

inline void to_json(nlohmann::json& j, const UnitListPart& v) {
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["number"] = v.number;
    j["name"] = v.name;
    j["revision"] = v.revision;
}

inline void from_json(const nlohmann::json& j, UnitListPart& v) {
    if (!j.contains("id")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: id", &j);
    }
    v.id = j["id"].get<std::string>();
    if (!j.contains("number")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: number", &j);
    }
    v.number = j["number"].get<std::string>();
    if (!j.contains("name")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: name", &j);
    }
    v.name = j["name"].get<std::string>();
    if (!j.contains("revision")) {
        throw nlohmann::json::other_error::create(501,
            "missing required field in response: revision", &j);
    }
    v.revision = j["revision"].get<UnitListRevision>();
}

} // namespace tofupilot
